/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WCAPP_H
#define XTCW_WCAPP_H
#include <X11/CoreP.h>
#include <xtcw/Wcap.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} WcapClassPart;

typedef struct _WcapClassRec {
CoreClassPart core_class;
WcapClassPart wcap_class;
} WcapClassRec;

typedef struct {
/* resources */
XtCallbackList  callback;
int  grab;
/* private state */
Bool  cap;
GC  gc_copy;
int  pic_w;
int  pic_h;
shimg_t * im;
XtIntervalId  autoupd_id;
} WcapPart;

typedef struct _WcapRec {
CorePart core;
WcapPart wcap;
} WcapRec;

externalref WcapClassRec wcapClassRec;

_XFUNCPROTOEND
#endif /* XTCW_WCAPP_H */
