/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WCAP_H
#define XTCW_WCAP_H
#include <X11/Core.h>
_XFUNCPROTOBEGIN
#ifndef XtNcallback
#define XtNcallback "callback"
#endif
#ifndef XtCCallback
#define XtCCallback "Callback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNgrab
#define XtNgrab "grab"
#endif
#ifndef XtCGrab
#define XtCGrab "Grab"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

typedef struct _WcapClassRec *WcapWidgetClass;
typedef struct _WcapRec *WcapWidget;
externalref WidgetClass wcapWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WCAP_H */
