/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_DIGTAB_H
#define XTCW_DIGTAB_H
#include <../widgets/Gridbox.h>
_XFUNCPROTOBEGIN
#ifndef XtNpin_config
#define XtNpin_config "pin_config"
#endif
#ifndef XtCPin_config
#define XtCPin_config "Pin_config"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNpin_status
#define XtNpin_status "pin_status"
#endif
#ifndef XtCPin_status
#define XtCPin_status "Pin_status"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNcallback
#define XtNcallback "callback"
#endif
#ifndef XtCCallback
#define XtCCallback "Callback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

typedef struct _DigTabClassRec *DigTabWidgetClass;
typedef struct _DigTabRec *DigTabWidget;
externalref WidgetClass digTabWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_DIGTAB_H */
