/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_KAROED_H
#define XTCW_KAROED_H
#include <xtcw/Wheel.h>
_XFUNCPROTOBEGIN
#ifndef XtNlocked
#define XtNlocked "locked"
#endif
#ifndef XtCLocked
#define XtCLocked "Locked"
#endif
#ifndef XtRBool
#define XtRBool "Bool"
#endif

#ifndef XtNlines
#define XtNlines "lines"
#endif
#ifndef XtCLines
#define XtCLines "Lines"
#endif
#ifndef XtRStringMArray
#define XtRStringMArray "StringMArray"
#endif

#ifndef XtNmin_lines
#define XtNmin_lines "min_lines"
#endif
#ifndef XtCMin_lines
#define XtCMin_lines "Min_lines"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNgrid_width
#define XtNgrid_width "grid_width"
#endif
#ifndef XtCGrid_width
#define XtCGrid_width "Grid_width"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNgrid_height
#define XtNgrid_height "grid_height"
#endif
#ifndef XtCGrid_height
#define XtCGrid_height "Grid_height"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNauto_resize
#define XtNauto_resize "auto_resize"
#endif
#ifndef XtCAuto_resize
#define XtCAuto_resize "Auto_resize"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

typedef struct _KaroEdClassRec *KaroEdWidgetClass;
typedef struct _KaroEdRec *KaroEdWidget;
externalref WidgetClass karoEdWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_KAROED_H */
