/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_KAROEDP_H
#define XTCW_KAROEDP_H
#include <xtcw/WheelP.h>
#include <xtcw/KaroEd.h>
_XFUNCPROTOBEGIN
#define debug 5 



typedef struct {
/* methods */
/* class variables */
Atom  XA_UTF8_STRING;
} KaroEdClassPart;

typedef struct _KaroEdClassRec {
CoreClassPart core_class;
WheelClassPart wheel_class;
KaroEdClassPart karoEd_class;
} KaroEdClassRec;

typedef struct {
/* resources */
Bool  locked;
StringMArray  lines;
int  min_lines;
int  grid_width;
int  grid_height;
int  auto_resize;
/* private state */
int  drag_last_y;
int  drag_last_x;
int  drag_update;
int  top_x;
int  top_y;
int  grid_pix_width;
int  grid_pix_height;
int  value;
Bool  do_init;
XftDraw * draw;
Bool  selection;
Bool  selection_visible;
int  selectionText;
XRectangle  rsel;
XRectangle  rsel_old;
} KaroEdPart;

typedef struct _KaroEdRec {
CorePart core;
WheelPart wheel;
KaroEdPart karoEd;
} KaroEdRec;

externalref KaroEdClassRec karoEdClassRec;

_XFUNCPROTOEND
#endif /* XTCW_KAROEDP_H */
