/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_QVLABELP_H
#define XTCW_QVLABELP_H
#include <../widgets/GridboxP.h>
#include <xtcw/Qvlabel.h>
_XFUNCPROTOBEGIN
typedef struct {
/* Constraint resources */
/* Private constraint variables */
int dummy;
} QvlabelConstraintPart;

typedef struct _QvlabelConstraintRec {
GridboxConstraintPart gridbox;
QvlabelConstraintPart qvlabel;
} QvlabelConstraintRec;


typedef struct {
/* methods */
/* class variables */
int dummy;
} QvlabelClassPart;

typedef struct _QvlabelClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
ConstraintClassPart constraint_class;
GridboxClassPart gridbox_class;
QvlabelClassPart qvlabel_class;
} QvlabelClassRec;

typedef struct {
/* resources */
String  label;
QVar  var;
QVar  enable;
/* private state */
} QvlabelPart;

typedef struct _QvlabelRec {
CorePart core;
CompositePart composite;
ConstraintPart constraint;
GridboxPart gridbox;
QvlabelPart qvlabel;
} QvlabelRec;

externalref QvlabelClassRec qvlabelClassRec;

_XFUNCPROTOEND
#endif /* XTCW_QVLABELP_H */
