/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_QVLABEL_H
#define XTCW_QVLABEL_H
#include <../widgets/Gridbox.h>
_XFUNCPROTOBEGIN
#ifndef XtNlabel
#define XtNlabel "label"
#endif
#ifndef XtCLabel
#define XtCLabel "Label"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNvar
#define XtNvar "var"
#endif
#ifndef XtCVar
#define XtCVar "Var"
#endif
#ifndef XtRQVar
#define XtRQVar "QVar"
#endif

#ifndef XtNenable
#define XtNenable "enable"
#endif
#ifndef XtCEnable
#define XtCEnable "Enable"
#endif
#ifndef XtRQVar
#define XtRQVar "QVar"
#endif

typedef struct _QvlabelClassRec *QvlabelWidgetClass;
typedef struct _QvlabelRec *QvlabelWidget;
externalref WidgetClass qvlabelWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_QVLABEL_H */
