/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_RADIO2_H
#define XTCW_RADIO2_H
#include <../widgets/Gridbox.h>
_XFUNCPROTOBEGIN
#ifndef XtNlst
#define XtNlst "lst"
#endif
#ifndef XtCLst
#define XtCLst "Lst"
#endif
#ifndef XtRStringMArray
#define XtRStringMArray "StringMArray"
#endif

#ifndef XtNvalue
#define XtNvalue "value"
#endif
#ifndef XtCValue
#define XtCValue "Value"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

typedef struct _Radio2ClassRec *Radio2WidgetClass;
typedef struct _Radio2Rec *Radio2Widget;
externalref WidgetClass radio2WidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_RADIO2_H */
