/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_RADIO2P_H
#define XTCW_RADIO2P_H
#include <../widgets/GridboxP.h>
#include <xtcw/Radio2.h>
_XFUNCPROTOBEGIN
typedef struct {
/* Constraint resources */
/* Private constraint variables */
int dummy;
} Radio2ConstraintPart;

typedef struct _Radio2ConstraintRec {
GridboxConstraintPart gridbox;
Radio2ConstraintPart radio2;
} Radio2ConstraintRec;


typedef struct {
/* methods */
/* class variables */
int dummy;
} Radio2ClassPart;

typedef struct _Radio2ClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
ConstraintClassPart constraint_class;
GridboxClassPart gridbox_class;
Radio2ClassPart radio2_class;
} Radio2ClassRec;

typedef struct {
/* resources */
StringMArray  lst;
int  value;
/* private state */
String  radioGroup;
} Radio2Part;

typedef struct _Radio2Rec {
CorePart core;
CompositePart composite;
ConstraintPart constraint;
GridboxPart gridbox;
Radio2Part radio2;
} Radio2Rec;

externalref Radio2ClassRec radio2ClassRec;

_XFUNCPROTOEND
#endif /* XTCW_RADIO2P_H */
