/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_TERMED_H
#define XTCW_TERMED_H
#include <X11/Core.h>
_XFUNCPROTOBEGIN
#ifndef XtNgWidth
#define XtNgWidth "gWidth"
#endif
#ifndef XtCGWidth
#define XtCGWidth "GWidth"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNgHeight
#define XtNgHeight "gHeight"
#endif
#ifndef XtCGHeight
#define XtCGHeight "GHeight"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNsize
#define XtNsize "size"
#endif
#ifndef XtCSize
#define XtCSize "Size"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNselTime
#define XtNselTime "selTime"
#endif
#ifndef XtCSelTime
#define XtCSelTime "SelTime"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNtext
#define XtNtext "text"
#endif
#ifndef XtCText
#define XtCText "Text"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNfg
#define XtNfg "fg"
#endif
#ifndef XtCFg
#define XtCFg "Fg"
#endif
#ifndef XtRXftColor
#define XtRXftColor "XftColor"
#endif

#ifndef XtNbg
#define XtNbg "bg"
#endif
#ifndef XtCBg
#define XtCBg "Bg"
#endif
#ifndef XtRXftColor
#define XtRXftColor "XftColor"
#endif

#ifndef XtNcbg
#define XtNcbg "cbg"
#endif
#ifndef XtCCbg
#define XtCCbg "Cbg"
#endif
#ifndef XtRXftColor
#define XtRXftColor "XftColor"
#endif

#ifndef XtNcfg
#define XtNcfg "cfg"
#endif
#ifndef XtCCfg
#define XtCCfg "Cfg"
#endif
#ifndef XtRXftColor
#define XtRXftColor "XftColor"
#endif

typedef struct _TermEdClassRec *TermEdWidgetClass;
typedef struct _TermEdRec *TermEdWidget;
externalref WidgetClass termEdWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_TERMED_H */
