/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WHEEL_H
#define XTCW_WHEEL_H
#include <X11/Core.h>
_XFUNCPROTOBEGIN
typedef enum {
  STATE_NORMAL = 0,
  STATE_SELECTED = 1,
  STATE_ARMED = 2,
  STATE_MAX = 3
} wheel_state;

typedef enum {
      WHEEL_NOCOMMAND,
      WHEEL_LEFT,
      WHEEL_RIGHT,
      WHEEL_FIRE,
      WHEEL_KEYPAD
} wheel_cmd;

typedef enum {
 COLOR_FG_NORM, COLOR_FG_SEL, COLOR_FG_HI, COLOR_BG_NORM, COLOR_BG_SEL, COLOR_BG_HI
} wheel_colors;

#define COLOR_FG_MAX 3 


typedef enum {
 GC_BG_NORM, GC_BG_SEL, GC_BG_HI
} wheel_gcs;

int  wheel_exec_command(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
int  wheel_sig_recv(
#if NeedFunctionPrototypes
Widget,Widget ,int ,void *,void *
#endif
);
#ifndef XtNxftFont
#define XtNxftFont "xftFont"
#endif
#ifndef XtCXFtFont
#define XtCXFtFont "XFtFont"
#endif
#ifndef XtRXftFont
#define XtRXftFont "XftFont"
#endif

#ifndef XtNcallback
#define XtNcallback "callback"
#endif
#ifndef XtCCallback
#define XtCCallback "Callback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNbg_norm
#define XtNbg_norm "bg_norm"
#endif
#ifndef XtCBg_norm
#define XtCBg_norm "Bg_norm"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNbg_sel
#define XtNbg_sel "bg_sel"
#endif
#ifndef XtCBg_sel
#define XtCBg_sel "Bg_sel"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNbg_hi
#define XtNbg_hi "bg_hi"
#endif
#ifndef XtCBg_hi
#define XtCBg_hi "Bg_hi"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNfg_norm
#define XtNfg_norm "fg_norm"
#endif
#ifndef XtCFg_norm
#define XtCFg_norm "Fg_norm"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNfg_sel
#define XtNfg_sel "fg_sel"
#endif
#ifndef XtCFg_sel
#define XtCFg_sel "Fg_sel"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNfg_hi
#define XtNfg_hi "fg_hi"
#endif
#ifndef XtCFg_hi
#define XtCFg_hi "Fg_hi"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNuser_data
#define XtNuser_data "user_data"
#endif
#ifndef XtCUser_data
#define XtCUser_data "User_data"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNfocus_group
#define XtNfocus_group "focus_group"
#endif
#ifndef XtCFocus_group
#define XtCFocus_group "Focus_group"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNstate
#define XtNstate "state"
#endif
#ifndef XtCState
#define XtCState "State"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNregister_focus_group
#define XtNregister_focus_group "register_focus_group"
#endif
#ifndef XtCRegister_focus_group
#define XtCRegister_focus_group "Register_focus_group"
#endif
#ifndef XtRBoolean
#define XtRBoolean "Boolean"
#endif

typedef struct _WheelClassRec *WheelWidgetClass;
typedef struct _WheelRec *WheelWidget;
externalref WidgetClass wheelWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WHEEL_H */
