/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WLABP_H
#define XTCW_WLABP_H
#include <xtcw/WheelP.h>
#include <xtcw/Wlab.h>
_XFUNCPROTOBEGIN
#define debug 5 


typedef Bool  (*cache_hit_Proc)(
#if NeedFunctionPrototypes
Widget
#endif
);
#define XtInherit_cache_hit ((cache_hit_Proc) _XtInherit)
typedef void  (*minimal_size_Proc)(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#define XtInherit_minimal_size ((minimal_size_Proc) _XtInherit)
typedef void  (*prefered_size_Proc)(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#define XtInherit_prefered_size ((prefered_size_Proc) _XtInherit)

typedef struct {
/* methods */
cache_hit_Proc cache_hit;
minimal_size_Proc minimal_size;
prefered_size_Proc prefered_size;
/* class variables */
} WlabClassPart;

typedef struct _WlabClassRec {
CoreClassPart core_class;
WheelClassPart wheel_class;
WlabClassPart wlab_class;
} WlabClassRec;

typedef struct {
/* resources */
String  label;
int  cornerRoundPercent;
int  innerBorder;
int  update;
/* private state */
int  pm_w;
int  pm_h;
Pixmap  pixmap;
XftDraw * draw;
GC  gc_copy;
XRectangle  r_label;
Bool  do_init;
} WlabPart;

typedef struct _WlabRec {
CorePart core;
WheelPart wheel;
WlabPart wlab;
} WlabRec;

externalref WlabClassRec wlabClassRec;

_XFUNCPROTOEND
#endif /* XTCW_WLABP_H */
