/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WLAB_H
#define XTCW_WLAB_H
#include <xtcw/Wheel.h>
_XFUNCPROTOBEGIN
#ifndef XtNlabel
#define XtNlabel "label"
#endif
#ifndef XtCLabel
#define XtCLabel "Label"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNcornerRoundPercent
#define XtNcornerRoundPercent "cornerRoundPercent"
#endif
#ifndef XtCCornerRoundPercent
#define XtCCornerRoundPercent "CornerRoundPercent"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNinnerBorder
#define XtNinnerBorder "innerBorder"
#endif
#ifndef XtCInnerBorder
#define XtCInnerBorder "InnerBorder"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNupdate
#define XtNupdate "update"
#endif
#ifndef XtCUpdate
#define XtCUpdate "Update"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

typedef struct _WlabClassRec *WlabWidgetClass;
typedef struct _WlabRec *WlabWidget;
externalref WidgetClass wlabWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WLAB_H */
