/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WLABELP_H
#define XTCW_WLABELP_H
#include <xtcw/WheelP.h>
#include <xtcw/Wlabel.h>
_XFUNCPROTOBEGIN
typedef Bool  (*cache_hit_Proc)(
#if NeedFunctionPrototypes
Widget
#endif
);
#define XtInherit_cache_hit ((cache_hit_Proc) _XtInherit)

typedef struct {
/* methods */
cache_hit_Proc cache_hit;
/* class variables */
} WlabelClassPart;

typedef struct _WlabelClassRec {
CoreClassPart core_class;
WheelClassPart wheel_class;
WlabelClassPart wlabel_class;
} WlabelClassRec;

typedef struct {
/* resources */
String  label;
int  cornerRoundPercent;
XtCallbackProc  draw_override;
int  heightIncreasePercent;
int  leftOffsetPercent;
int  update;
/* private state */
XftDraw * draw;
String  label_cache;
Pixmap  pixmap;
GC  gc_copy;
int  state_cache;
Bool  dirty;
} WlabelPart;

typedef struct _WlabelRec {
CorePart core;
WheelPart wheel;
WlabelPart wlabel;
} WlabelRec;

externalref WlabelClassRec wlabelClassRec;

_XFUNCPROTOEND
#endif /* XTCW_WLABELP_H */
