/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WMVARP_H
#define XTCW_WMVARP_H
#include <xtcw/WheelP.h>
#include <xtcw/Wmvar.h>
_XFUNCPROTOBEGIN
#define debug 5 


typedef Bool  (*cache_hit_Proc)(
#if NeedFunctionPrototypes
Widget
#endif
);
#define XtInherit_cache_hit ((cache_hit_Proc) _XtInherit)
typedef void  (*minimal_size_Proc)(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#define XtInherit_minimal_size ((minimal_size_Proc) _XtInherit)
typedef void  (*prefered_size_Proc)(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#define XtInherit_prefered_size ((prefered_size_Proc) _XtInherit)

typedef struct {
/* methods */
cache_hit_Proc cache_hit;
minimal_size_Proc minimal_size;
prefered_size_Proc prefered_size;
/* class variables */
} WmvarClassPart;

typedef struct _WmvarClassRec {
CoreClassPart core_class;
WheelClassPart wheel_class;
WmvarClassPart wmvar_class;
} WmvarClassRec;

typedef struct {
/* resources */
String  label;
int  cornerRoundPercent;
int  innerBorder;
int  update;
/* private state */
int  pm_w;
int  pm_h;
Pixmap  pixmap;
XftDraw * draw;
GC  gc_copy;
XRectangle  r_label;
Bool  do_init;
} WmvarPart;

typedef struct _WmvarRec {
CorePart core;
WheelPart wheel;
WmvarPart wmvar;
} WmvarRec;

externalref WmvarClassRec wmvarClassRec;

_XFUNCPROTOEND
#endif /* XTCW_WMVARP_H */
