/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WSEL_H
#define XTCW_WSEL_H
#include <xtcw/Wlab.h>
_XFUNCPROTOBEGIN
#ifndef XtNvalue
#define XtNvalue "value"
#endif
#ifndef XtCValue
#define XtCValue "Value"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNlocked
#define XtNlocked "locked"
#endif
#ifndef XtCLocked
#define XtCLocked "Locked"
#endif
#ifndef XtRBool
#define XtRBool "Bool"
#endif

#ifndef XtNnames
#define XtNnames "names"
#endif
#ifndef XtCNames
#define XtCNames "Names"
#endif
#ifndef XtRStringMArray
#define XtRStringMArray "StringMArray"
#endif

typedef struct _WselClassRec *WselWidgetClass;
typedef struct _WselRec *WselWidget;
externalref WidgetClass wselWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WSEL_H */
