/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WSELP_H
#define XTCW_WSELP_H
#include <xtcw/WlabP.h>
#include <xtcw/Wsel.h>
_XFUNCPROTOBEGIN

typedef struct {
/* methods */
/* class variables */
int dummy;
} WselClassPart;

typedef struct _WselClassRec {
CoreClassPart core_class;
WheelClassPart wheel_class;
WlabClassPart wlab_class;
WselClassPart wsel_class;
} WselClassRec;

typedef struct {
/* resources */
int  value;
Bool  locked;
StringMArray  names;
/* private state */
int  max_value;
int  drag_last_y;
int  drag_last_x;
int  drag_update;
} WselPart;

typedef struct _WselRec {
CorePart core;
WheelPart wheel;
WlabPart wlab;
WselPart wsel;
} WselRec;

externalref WselClassRec wselClassRec;

_XFUNCPROTOEND
#endif /* XTCW_WSELP_H */
