/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WSEL2P_H
#define XTCW_WSEL2P_H
#include <xtcw/WheelP.h>
#include <xtcw/Wsel2.h>
_XFUNCPROTOBEGIN
#define debug 5 


typedef Bool  (*cache_hit_Proc)(
#if NeedFunctionPrototypes
Widget
#endif
);
#define XtInherit_cache_hit ((cache_hit_Proc) _XtInherit)
typedef void  (*minimal_size_Proc)(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#define XtInherit_minimal_size ((minimal_size_Proc) _XtInherit)
typedef void  (*prefered_size_Proc)(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#define XtInherit_prefered_size ((prefered_size_Proc) _XtInherit)

typedef struct {
/* methods */
cache_hit_Proc cache_hit;
minimal_size_Proc minimal_size;
prefered_size_Proc prefered_size;
/* class variables */
} Wsel2ClassPart;

typedef struct _Wsel2ClassRec {
CoreClassPart core_class;
WheelClassPart wheel_class;
Wsel2ClassPart wsel2_class;
} Wsel2ClassRec;

typedef struct {
/* resources */
int  value;
Bool  locked;
StringMArray  names;
int  cornerRoundPercent;
int  innerBorder;
int  update;
Distance  hgap;
/* private state */
int  last_value;
int  total_width;
int  max_value;
int  pm_w;
int  pm_h;
Pixmap  pixmap;
XftDraw * draw;
GC  gc_copy;
XRectangle  r_label;
Bool  do_init;
int  rects;
} Wsel2Part;

typedef struct _Wsel2Rec {
CorePart core;
WheelPart wheel;
Wsel2Part wsel2;
} Wsel2Rec;

externalref Wsel2ClassRec wsel2ClassRec;

_XFUNCPROTOEND
#endif /* XTCW_WSEL2P_H */
