/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WSEL2_H
#define XTCW_WSEL2_H
#include <xtcw/Wheel.h>
_XFUNCPROTOBEGIN
#ifndef XtNvalue
#define XtNvalue "value"
#endif
#ifndef XtCValue
#define XtCValue "Value"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNlocked
#define XtNlocked "locked"
#endif
#ifndef XtCLocked
#define XtCLocked "Locked"
#endif
#ifndef XtRBool
#define XtRBool "Bool"
#endif

#ifndef XtNnames
#define XtNnames "names"
#endif
#ifndef XtCNames
#define XtCNames "Names"
#endif
#ifndef XtRStringMArray
#define XtRStringMArray "StringMArray"
#endif

#ifndef XtNcornerRoundPercent
#define XtNcornerRoundPercent "cornerRoundPercent"
#endif
#ifndef XtCCornerRoundPercent
#define XtCCornerRoundPercent "CornerRoundPercent"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNinnerBorder
#define XtNinnerBorder "innerBorder"
#endif
#ifndef XtCInnerBorder
#define XtCInnerBorder "InnerBorder"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNupdate
#define XtNupdate "update"
#endif
#ifndef XtCUpdate
#define XtCUpdate "Update"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNhgap
#define XtNhgap "hgap"
#endif
#ifndef XtCHgap
#define XtCHgap "Hgap"
#endif
#ifndef XtRDistance
#define XtRDistance "Distance"
#endif

typedef struct _Wsel2ClassRec *Wsel2WidgetClass;
typedef struct _Wsel2Rec *Wsel2Widget;
externalref WidgetClass wsel2WidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WSEL2_H */
