/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef XTCW_WVIEWQV_H
#define XTCW_WVIEWQV_H
#include <xtcw/Wlabel.h>
_XFUNCPROTOBEGIN
#ifndef XtNvar
#define XtNvar "var"
#endif
#ifndef XtCVar
#define XtCVar "Var"
#endif
#ifndef XtRQVar
#define XtRQVar "QVar"
#endif

#ifndef XtNenable
#define XtNenable "enable"
#endif
#ifndef XtCEnable
#define XtCEnable "Enable"
#endif
#ifndef XtRQVar
#define XtRQVar "QVar"
#endif

typedef struct _WviewQVClassRec *WviewQVWidgetClass;
typedef struct _WviewQVRec *WviewQVWidget;
externalref WidgetClass wviewQVWidgetClass;
_XFUNCPROTOEND
#endif /* XTCW_WVIEWQV_H */
