/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef VEXMO_WTXT_H
#define VEXMO_WTXT_H
#include <X11/Core.h>
_XFUNCPROTOBEGIN
#ifndef XtNfontName
#define XtNfontName "fontName"
#endif
#ifndef XtCFontName
#define XtCFontName "FontName"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNforeground
#define XtNforeground "foreground"
#endif
#ifndef XtCForeground
#define XtCForeground "Foreground"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNcursorColor
#define XtNcursorColor "cursorColor"
#endif
#ifndef XtCCursorColor
#define XtCCursorColor "CursorColor"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNlineWidth
#define XtNlineWidth "lineWidth"
#endif
#ifndef XtCLineWidth
#define XtCLineWidth "LineWidth"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcornerRoundPercent
#define XtNcornerRoundPercent "cornerRoundPercent"
#endif
#ifndef XtCCornerRoundPercent
#define XtCCornerRoundPercent "CornerRoundPercent"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcallback
#define XtNcallback "callback"
#endif
#ifndef XtCCallback
#define XtCCallback "Callback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNlabel
#define XtNlabel "label"
#endif
#ifndef XtCLabel
#define XtCLabel "Label"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

typedef struct _WtxtClassRec *WtxtWidgetClass;
typedef struct _WtxtRec *WtxtWidget;
externalref WidgetClass wtxtWidgetClass;
_XFUNCPROTOEND
#endif /* VEXMO_WTXT_H */
