/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef VEXMO_WTXTP_H
#define VEXMO_WTXTP_H
#include <X11/CoreP.h>
#include <vexmo/Wtxt.h>
_XFUNCPROTOBEGIN
#define BG 0 


#define FG 1 


#define CRSR 2 


typedef struct { Pixmap data; XRectangle r; } pix_info;
typedef struct {
    int xp,yp;
    int glyph_m;
    int line_m;
    int char_m;
    int unicode;
    struct { int unicode; XGlyphInfo info; } *char_ent;
    struct { int endp,txtp, height,ascent; } *line_ent;
} layout_t;

typedef struct {
/* methods */
/* class variables */
Atom  XA_UTF8_STRING;
} WtxtClassPart;

typedef struct _WtxtClassRec {
CoreClassPart core_class;
WtxtClassPart wtxt_class;
} WtxtClassRec;

typedef struct {
/* resources */
String  fontName;
Pixel  foreground;
Pixel  cursorColor;
int  lineWidth;
int  cornerRoundPercent;
XtCallbackList  callback;
String  label;
/* private state */
layout_t  lay;
XftFont * xftFont;
pix_info  pix;
int  str_m;
int  label_m;
int  glyph_m;
int  glyph_xoff_m;
int  glyphi_m;
XftDraw * draw;
GC  gc[3];
XftColor  xcol[3];
XRectangle  crsr_rect;
XRectangle  txt;
char  crsr_on;
int  crsr_pos;
int  crsr_width;
int  left_char_offset;
int  left_pixel_offset;
int  dirty;
int  dirty_str;
} WtxtPart;

typedef struct _WtxtRec {
CorePart core;
WtxtPart wtxt;
} WtxtRec;

externalref WtxtClassRec wtxtClassRec;

_XFUNCPROTOEND
#endif /* VEXMO_WTXTP_H */
