'\" t
.TH "" 3 "" "Version Unknown To Mankind" "Free Widget Foundation"
.SH NAME
Wlabel
.SH DESCRIPTION

.SS "Public variables"

.ps -2
.TS
center box;
cBsss
lB|lB|lB|lB
l|l|l|l.
Wlabel
Name	Class	Type	Default
XtNlabel	XtCLabel	String 	NULL 
XtNcornerRoundPercent	XtCCornerRoundPercent	int 	0 
XtNdraw_override	XtCDraw_override	XtCallbackProc 	NULL 
XtNheightIncreasePercent	XtCHeightIncreasePercent	int 	0 
XtNleftOffsetPercent	XtCLeftOffsetPercent	int 	5 
XtNupdate	XtCUpdate	int 	0 

.TE
.ps +2


.TP
.I "XtNlabel"



.TP
.I "XtNcornerRoundPercent"



.TP
.I "XtNdraw_override"



.TP
.I "XtNheightIncreasePercent"



.TP
.I "XtNleftOffsetPercent"



.TP
.I "XtNupdate"



.ps -2
.TS
center box;
cBsss
lB|lB|lB|lB
l|l|l|l.
Wheel
Name	Class	Type	Default
XtNxftFont	XtCXFtFont	XftFont	"Sans-22"
XtNcallback	XtCCallback	Callback	NULL 
XtNbg_norm	XtCBg_norm	Pixel	"lightblue"
XtNbg_sel	XtCBg_sel	Pixel	"yellow"
XtNbg_hi	XtCBg_hi	Pixel	"red"
XtNfg_norm	XtCFg_norm	Pixel	"black"
XtNfg_sel	XtCFg_sel	Pixel	"green"
XtNfg_hi	XtCFg_hi	Pixel	"white"
XtNuser_data	XtCUser_data	Int 	0 
XtNfocus_group	XtCFocus_group	String 	""
XtNstate	XtCState	Int 	0 
XtNregister_focus_group	XtCRegister_focus_group	Boolean 	True 

.TE
.ps +2

.ps -2
.TS
center box;
cBsss
lB|lB|lB|lB
l|l|l|l.
Core
Name	Class	Type	Default
XtNx	XtCX	Position 	0 
XtNy	XtCY	Position 	0 
XtNwidth	XtCWidth	Dimension 	0 
XtNheight	XtCHeight	Dimension 	0 
borderWidth	XtCBorderWidth	Dimension 	0 
XtNcolormap	XtCColormap	Colormap 	NULL 
XtNdepth	XtCDepth	Int 	0 
destroyCallback	XtCDestroyCallback	XTCallbackList 	NULL 
XtNsensitive	XtCSensitive	Boolean 	True 
XtNtm	XtCTm	XTTMRec 	NULL 
ancestorSensitive	XtCAncestorSensitive	Boolean 	False 
accelerators	XtCAccelerators	XTTranslations 	NULL 
borderColor	XtCBorderColor	Pixel 	0 
borderPixmap	XtCBorderPixmap	Pixmap 	NULL 
background	XtCBackground	Pixel 	0 
backgroundPixmap	XtCBackgroundPixmap	Pixmap 	NULL 
mappedWhenManaged	XtCMappedWhenManaged	Boolean 	True 
XtNscreen	XtCScreen	Screen *	NULL 

.TE
.ps +2
