/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 864 "KaroEd.widget"
#include <stdint.h>
#line 865 "KaroEd.widget"
#include <X11/Xft/Xft.h>
#line 866 "KaroEd.widget"
#include <X11/Xaw/XawImP.h>
#line 867 "KaroEd.widget"
#include <X11/Xatom.h>
#line 868 "KaroEd.widget"
#include <X11/Xmu/Xmu.h>
#line 869 "KaroEd.widget"
#include "xutil.h"
#line 870 "KaroEd.widget"
#include "converters.h"
#line 871 "KaroEd.widget"
#include "mls.h"
#include <xtcw/KaroEdP.h>
#line 675 "KaroEd.widget"
static void copy_selection(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 689 "KaroEd.widget"
static void insert_selection(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 697 "KaroEd.widget"
static void key_return(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 704 "KaroEd.widget"
static void prev_line(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 715 "KaroEd.widget"
static void next_line(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 725 "KaroEd.widget"
static void backward_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 737 "KaroEd.widget"
static void forward_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 743 "KaroEd.widget"
static void info(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 754 "KaroEd.widget"
static void remove_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 768 "KaroEd.widget"
static void insert_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 785 "KaroEd.widget"
static void selection_clear(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 790 "KaroEd.widget"
static void selection_set(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 801 "KaroEd.widget"
static void highlight(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 806 "KaroEd.widget"
static void reset(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 810 "KaroEd.widget"
static void notify(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 818 "KaroEd.widget"
static void selection_end(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 826 "KaroEd.widget"
static void motion_start(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);

static XtActionsRec actionsList[] = {
{"copy_selection", copy_selection},
{"insert_selection", insert_selection},
{"key_return", key_return},
{"prev_line", prev_line},
{"next_line", next_line},
{"backward_char", backward_char},
{"forward_char", forward_char},
{"info", info},
{"remove_char", remove_char},
{"insert_char", insert_char},
{"selection_clear", selection_clear},
{"selection_set", selection_set},
{"highlight", highlight},
{"reset", reset},
{"notify", notify},
{"selection_end", selection_end},
{"motion_start", motion_start},
};

static char defaultTranslations[] = "\
<EnterWindow>: highlight() \n\
<LeaveWindow>: reset() \n\
<Btn2Down>: info() \n\
<Btn1Down>: selection_set() \n\
<Btn1Motion>: motion_start() \n\
<Btn1Up>: selection_end() \n\
<Key>Right: forward_char() \n\
<Key>Left: backward_char() \n\
<Key>Up: prev_line() \n\
<Key>Down: next_line() \n\
<Key>Delete: remove_char() \n\
<Key>BackSpace: backward_char() remove_char() \n\
<Key>Return: key_return() \n\
<Ctrl>v: insert_selection() \n\
<Key>: insert_char() \n\
";
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 40 "KaroEd.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 70 "KaroEd.widget"
static void resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 76 "KaroEd.widget"
static void realize(
#if NeedFunctionPrototypes
Widget,XtValueMask *,XSetWindowAttributes *
#endif
);
#line 85 "KaroEd.widget"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);
#line 105 "KaroEd.widget"
static void clip_rect(
#if NeedFunctionPrototypes
Widget,XRectangle *
#endif
);
#line 135 "KaroEd.widget"
static void draw_sel_rect(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 169 "KaroEd.widget"
static void draw_rect(
#if NeedFunctionPrototypes
Widget,XRectangle *
#endif
);
#line 180 "KaroEd.widget"
static void selection_draw(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 196 "KaroEd.widget"
static void selection_clear_a(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 209 "KaroEd.widget"
static void redraw_full(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 219 "KaroEd.widget"
static uint32_t  find_charpos(
#if NeedFunctionPrototypes
Widget,int ,int ,int *,int *
#endif
);
#line 250 "KaroEd.widget"
static uint32_t  get_ucs4(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 257 "KaroEd.widget"
static void draw_glyph(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 272 "KaroEd.widget"
static void draw_glyph_color(
#if NeedFunctionPrototypes
Widget,int ,int ,int ,int 
#endif
);
#line 292 "KaroEd.widget"
static String  get_name(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 297 "KaroEd.widget"
static void  normalize_pos(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 303 "KaroEd.widget"
static Bool  coordinate_to_text(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#line 316 "KaroEd.widget"
static void selection_start(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 323 "KaroEd.widget"
static Bool  selection_resize(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 360 "KaroEd.widget"
static void draw_line_from(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 372 "KaroEd.widget"
static int  utf8_strlen(
#if NeedFunctionPrototypes
char *
#endif
);
#line 380 "KaroEd.widget"
static void remove_char_at_cursor(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 405 "KaroEd.widget"
static void insert_char_at_cursor(
#if NeedFunctionPrototypes
Widget,char *,int 
#endif
);
#line 455 "KaroEd.widget"
static void cursor_right(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 466 "KaroEd.widget"
static Bool  cursor_pos1(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 475 "KaroEd.widget"
static Bool  cursor_down(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 485 "KaroEd.widget"
static Bool  current_line_empty(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 493 "KaroEd.widget"
static Bool  remove_current_line(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 502 "KaroEd.widget"
static Bool  insert_line(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 520 "KaroEd.widget"
static char * utf8_skip(
#if NeedFunctionPrototypes
char *,int 
#endif
);
#line 531 "KaroEd.widget"
static Bool  split_line_at_cursor(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 557 "KaroEd.widget"
static void RequestSelection(
#if NeedFunctionPrototypes
Widget,XtPointer ,Atom *,Atom *,XtPointer ,unsigned  long *,int *
#endif
);
#line 568 "KaroEd.widget"
static void utf8_copy_char(
#if NeedFunctionPrototypes
int ,char **
#endif
);
#line 578 "KaroEd.widget"
static Boolean  ConvertSelection(
#if NeedFunctionPrototypes
Widget,Atom *,Atom *,Atom *,XtPointer *,unsigned  long *,int *
#endif
);
#line 619 "KaroEd.widget"
static void LoseSelection(
#if NeedFunctionPrototypes
Widget,Atom *
#endif
);
#line 626 "KaroEd.widget"
static void own_primary_selection(
#if NeedFunctionPrototypes
Widget,ulong 
#endif
);
#line 105 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 105 "KaroEd.widget"
static void clip_rect(Widget self,XRectangle * r)
#else
#line 105 "KaroEd.widget"
static void clip_rect(self,r)Widget self;XRectangle * r;
#endif
#line 106 "KaroEd.widget"
{
    int x0,y0,x1,y1;
    x0 = r->x;
    y0 = r->y;
    x1 = x0 + r->width;
    y1 = y0 + r->height;

    /* oben links ausserhalb */
    if( x0 >= ((KaroEdWidget)self)->karoEd.grid_width || y0 >= ((KaroEdWidget)self)->karoEd.grid_height ) goto empty_rect;

    /* unten rechts ausserhalb */
    if( y1 < 0 || x1 < 0 ) goto empty_rect;

    /* auf window zurechtschneiden */
    if( x0 < 0 ) x0=0;
    if( y0 < 0 ) y0=0;
    if( x1 > ((KaroEdWidget)self)->karoEd.grid_width ) x1 = ((KaroEdWidget)self)->karoEd.grid_width;
    if( y1 > ((KaroEdWidget)self)->karoEd.grid_height) y1 = ((KaroEdWidget)self)->karoEd.grid_height;

    r->x = x0; r->y = y0;
    r->width = x1-x0;
    r->height = y1-y0;
    return;

 empty_rect:
    memset(r, 0, sizeof(*r));
}
#line 135 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 135 "KaroEd.widget"
static void draw_sel_rect(Widget self)
#else
#line 135 "KaroEd.widget"
static void draw_sel_rect(self)Widget self;
#endif
#line 136 "KaroEd.widget"
{
    int x,y,x1,y1;
    XRectangle r1;
    r1 = ((KaroEdWidget)self)->karoEd.rsel; /* neu */
    r1.x -= ((KaroEdWidget)self)->karoEd.top_x;
    r1.y -= ((KaroEdWidget)self)->karoEd.top_y;
    x1 = r1.x + r1.width;
    y1 = r1.y + r1.height;

    XRectangle r2;
    r2 = ((KaroEdWidget)self)->karoEd.rsel_old; /* alt */
    r2.x -= ((KaroEdWidget)self)->karoEd.top_x;
    r2.y -= ((KaroEdWidget)self)->karoEd.top_y;

    /* neu */
    for( x=r1.x; x < x1; x++ )
        for( y=r1.y; y < y1; y++ ) {
            if( rect_is_inside( &r2,x,y ) ) continue;
            draw_glyph(self,x,y);
        }

    /* alt */
    x1 = r2.x + r2.width;
    y1 = r2.y + r2.height;
    for( x=r2.x; x < x1; x++ )
        for( y=r2.y; y < y1; y++ ) {
            if( rect_is_inside( &r1,x,y ) ) continue;
            draw_glyph(self,x,y);
        }
    return;
}
#line 169 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 169 "KaroEd.widget"
static void draw_rect(Widget self,XRectangle * r)
#else
#line 169 "KaroEd.widget"
static void draw_rect(self,r)Widget self;XRectangle * r;
#endif
#line 170 "KaroEd.widget"
{
    int x,x1 = r->x + r->width;
    int y,y1 = r->y + r->height;
    for( x=r->x; x < x1; x++ )
        for( y=r->y; y < y1; y++ )
            draw_glyph(self,x,y);
}
#line 180 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 180 "KaroEd.widget"
static void selection_draw(Widget self)
#else
#line 180 "KaroEd.widget"
static void selection_draw(self)Widget self;
#endif
#line 181 "KaroEd.widget"
{

    if( ((KaroEdWidget)self)->karoEd.selection_visible ) {
        draw_sel_rect(self);
    } else {
        ((KaroEdWidget)self)->karoEd.selection_visible=True;
        XRectangle r = ((KaroEdWidget)self)->karoEd.rsel;
        r.x -= ((KaroEdWidget)self)->karoEd.top_x;
        r.y -= ((KaroEdWidget)self)->karoEd.top_y;
        draw_rect(self,&r);

    }
    ((KaroEdWidget)self)->karoEd.rsel_old = ((KaroEdWidget)self)->karoEd.rsel;
}
#line 196 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 196 "KaroEd.widget"
static void selection_clear_a(Widget self)
#else
#line 196 "KaroEd.widget"
static void selection_clear_a(self)Widget self;
#endif
#line 197 "KaroEd.widget"
{
    if( ((KaroEdWidget)self)->karoEd.selection_visible ) {
        ((KaroEdWidget)self)->karoEd.selection_visible=False;
        memset( & ((KaroEdWidget)self)->karoEd.rsel, 0, sizeof( ((KaroEdWidget)self)->karoEd.rsel ));
        XRectangle r = ((KaroEdWidget)self)->karoEd.rsel_old;
        r.x -= ((KaroEdWidget)self)->karoEd.top_x;
        r.y -= ((KaroEdWidget)self)->karoEd.top_y;
        draw_rect(self,&r);
    }
}
#line 209 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 209 "KaroEd.widget"
static void redraw_full(Widget self)
#else
#line 209 "KaroEd.widget"
static void redraw_full(self)Widget self;
#endif
#line 210 "KaroEd.widget"
{
        int x; int y;
        for( x=0; x < ((KaroEdWidget)self)->karoEd.grid_width; x++ ) {
            for(y=0; y < ((KaroEdWidget)self)->karoEd.grid_height; y++ ) {
                draw_glyph(self,x,y );
            }
        }
}
#line 219 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 219 "KaroEd.widget"
static uint32_t  find_charpos(Widget self,int  x,int  y,int * ret_line,int * ret_charpos)
#else
#line 219 "KaroEd.widget"
static uint32_t  find_charpos(self,x,y,ret_line,ret_charpos)Widget self;int  x;int  y;int * ret_line;int * ret_charpos;
#endif
#line 220 "KaroEd.widget"
{
    int ln = ((KaroEdWidget)self)->karoEd.top_y + y;
    int len, p  = ((KaroEdWidget)self)->karoEd.top_x + x;
    int l;
    uint8_t *string;
    uint32_t ucs4;

    *ret_line = -1;
    *ret_charpos = -1;

    if( ln >= m_len(((KaroEdWidget)self)->karoEd.lines) ) return 0;
    if(ret_line) *ret_line = ln;
    string = (uint8_t *)STR(((KaroEdWidget)self)->karoEd.lines,ln);
    len = strlen( (char*)string);
    while(1) {
            l = FcUtf8ToUcs4 (string, &ucs4, len);
            if( l<= 0 || len <=0 ) return 0;
            if( p <=0 ) {
                if( ret_charpos ) *ret_charpos = string - (uint8_t*)STR(((KaroEdWidget)self)->karoEd.lines,ln);
                return ucs4;
            }

            string += l;
            len -= l;
            p--;
    }

}
#line 250 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 250 "KaroEd.widget"
static uint32_t  get_ucs4(Widget self,int  x,int  y)
#else
#line 250 "KaroEd.widget"
static uint32_t  get_ucs4(self,x,y)Widget self;int  x;int  y;
#endif
#line 251 "KaroEd.widget"
{

    int d1,d2;
    return find_charpos(self,x,y,&d1,&d2);
}
#line 257 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 257 "KaroEd.widget"
static void draw_glyph(Widget self,int  x,int  y)
#else
#line 257 "KaroEd.widget"
static void draw_glyph(self,x,y)Widget self;int  x;int  y;
#endif
#line 258 "KaroEd.widget"
{
    if( x < 0 || x >= ((KaroEdWidget)self)->karoEd.grid_width ) return;
    if( y < 0 || y >= ((KaroEdWidget)self)->karoEd.grid_height ) return;

    int fg = 0;
    int bg = 3;
    if( ((KaroEdWidget)self)->karoEd.selection && rect_is_inside( & ((KaroEdWidget)self)->karoEd.rsel, x + ((KaroEdWidget)self)->karoEd.top_x, y + ((KaroEdWidget)self)->karoEd.top_y ) ) {
        fg = 1;
        bg = 4;
    }

    draw_glyph_color(self,x,y,fg,bg);
}
#line 272 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 272 "KaroEd.widget"
static void draw_glyph_color(Widget self,int  x,int  y,int  fg,int  bg)
#else
#line 272 "KaroEd.widget"
static void draw_glyph_color(self,x,y,fg,bg)Widget self;int  x;int  y;int  fg;int  bg;
#endif
#line 273 "KaroEd.widget"
{
    int x0,y0,w,h;
    uint32_t ucs4, glyph;

    x0 = x * ((KaroEdWidget)self)->karoEd.grid_pix_width;
    y0 = y * ((KaroEdWidget)self)->karoEd.grid_pix_height;
    w = ((KaroEdWidget)self)->karoEd.grid_pix_width;
    h = ((KaroEdWidget)self)->karoEd.grid_pix_height;

    XftDrawRect(((KaroEdWidget)self)->karoEd.draw,((KaroEdWidget)self)->wheel.xft_col+bg, x0,y0,w,h );
    ucs4 = get_ucs4(self, x, y );
    if( ucs4 == 0 || ucs4 == 32 ) return;
    glyph = XftCharIndex ( XtDisplay(self), ((KaroEdWidget)self)->wheel.xftFont, ucs4 );
    XftDrawGlyphs (((KaroEdWidget)self)->karoEd.draw, ((KaroEdWidget)self)->wheel.xft_col+fg, ((KaroEdWidget)self)->wheel.xftFont,
                   x0, y0+((KaroEdWidget)self)->wheel.xftFont->ascent,
                   &glyph, 1);
}
#line 292 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 292 "KaroEd.widget"
static String  get_name(Widget self)
#else
#line 292 "KaroEd.widget"
static String  get_name(self)Widget self;
#endif
#line 293 "KaroEd.widget"
{
          return "";
}
#line 297 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 297 "KaroEd.widget"
static void  normalize_pos(Widget self)
#else
#line 297 "KaroEd.widget"
static void  normalize_pos(self)Widget self;
#endif
#line 298 "KaroEd.widget"
{
        if( ((KaroEdWidget)self)->karoEd.top_x < 0 ) ((KaroEdWidget)self)->karoEd.top_x = 0;
        if( ((KaroEdWidget)self)->karoEd.top_y < 0 ) ((KaroEdWidget)self)->karoEd.top_y = 0;
}
#line 303 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 303 "KaroEd.widget"
static Bool  coordinate_to_text(Widget self,int * x,int * y)
#else
#line 303 "KaroEd.widget"
static Bool  coordinate_to_text(self,x,y)Widget self;int * x;int * y;
#endif
#line 304 "KaroEd.widget"
{
    Bool ret = (*x >= 0) && (*x < ((KaroEdWidget)self)->core.width) && (*y > 0) && (*y < ((KaroEdWidget)self)->core.height);

    *x /= ((KaroEdWidget)self)->karoEd.grid_pix_width;
    *x += ((KaroEdWidget)self)->karoEd.top_x;
    *y /= ((KaroEdWidget)self)->karoEd.grid_pix_height;
    *y += ((KaroEdWidget)self)->karoEd.top_y;

    return ret;

}
#line 316 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 316 "KaroEd.widget"
static void selection_start(Widget self,int  x,int  y)
#else
#line 316 "KaroEd.widget"
static void selection_start(self,x,y)Widget self;int  x;int  y;
#endif
#line 317 "KaroEd.widget"
{
    ((KaroEdWidget)self)->karoEd.selection=True;
    ((KaroEdWidget)self)->karoEd.rsel.x = x; ((KaroEdWidget)self)->karoEd.rsel.width=1;
    ((KaroEdWidget)self)->karoEd.rsel.y = y; ((KaroEdWidget)self)->karoEd.rsel.height=1;
}
#line 323 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 323 "KaroEd.widget"
static Bool  selection_resize(Widget self,int  x,int  y)
#else
#line 323 "KaroEd.widget"
static Bool  selection_resize(self,x,y)Widget self;int  x;int  y;
#endif
#line 324 "KaroEd.widget"
{
    Bool changed = False;
    int w = ((KaroEdWidget)self)->karoEd.rsel.width;
    int h = ((KaroEdWidget)self)->karoEd.rsel.height;
    int x0 = ((KaroEdWidget)self)->karoEd.rsel.x;
    int y0 = ((KaroEdWidget)self)->karoEd.rsel.y;
    int x1 = x0 + w -1;
    int y1 = y0 + h -1;

    if( x > x0 ) x1 = x; else { x1 = x0; x0 = x; }
    if( y > y0 ) y1 = y; else { y1 = y0; y0 = y; }

    w = x1 - x0 +1;
    h = y1 - y0 +1;
    if( ((KaroEdWidget)self)->karoEd.rsel.width != w ) {
        changed = True;
        ((KaroEdWidget)self)->karoEd.rsel.width = w;
    }
    if( ((KaroEdWidget)self)->karoEd.rsel.height != h ) {
        changed = True;
        ((KaroEdWidget)self)->karoEd.rsel.height = h;
    }
    if( ((KaroEdWidget)self)->karoEd.rsel.x != x0 ) {
        changed = True;
        ((KaroEdWidget)self)->karoEd.rsel.x = x0;
    }
    if( ((KaroEdWidget)self)->karoEd.rsel.y != y0 ) {
        changed = True;
        ((KaroEdWidget)self)->karoEd.rsel.y = y0;
    }


    return changed;
}
#line 360 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 360 "KaroEd.widget"
static void draw_line_from(Widget self,int  x,int  y)
#else
#line 360 "KaroEd.widget"
static void draw_line_from(self,x,y)Widget self;int  x;int  y;
#endif
#line 361 "KaroEd.widget"
{

    x -= ((KaroEdWidget)self)->karoEd.top_x;
    y -= ((KaroEdWidget)self)->karoEd.top_y;
    while( x < ((KaroEdWidget)self)->karoEd.grid_width ) {
        draw_glyph(self,x,y);
        x++;
    }
}
#line 372 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 372 "KaroEd.widget"
static int  utf8_strlen(char * s)
#else
#line 372 "KaroEd.widget"
static int  utf8_strlen(s)char * s;
#endif
#line 373 "KaroEd.widget"
{
    int n,w;
    FcUtf8Len((uint8_t*)s,strlen(s), &n, &w );
    return n;
}
#line 380 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 380 "KaroEd.widget"
static void remove_char_at_cursor(Widget self)
#else
#line 380 "KaroEd.widget"
static void remove_char_at_cursor(self)Widget self;
#endif
#line 381 "KaroEd.widget"
{
    uint32_t ucs4;
    int x,y,p,byte_len,byte_pos,w;
    x=((KaroEdWidget)self)->karoEd.rsel.x;
    y=((KaroEdWidget)self)->karoEd.rsel.y;
    if( y >= m_len(((KaroEdWidget)self)->karoEd.lines) ) return;
    char *s = STR(((KaroEdWidget)self)->karoEd.lines,y);
    if( x >= utf8_strlen(s) ) return;

    p=0;
    byte_len = strlen(s) +1;
    byte_pos = 0;
    while(1) {
        w = FcUtf8ToUcs4 ((uint8_t*)s + byte_pos, &ucs4, byte_len - byte_pos);
        if( w <=0 ) return;
        if( p >= x ) break;
        byte_pos+=w; p++;
    }

    memcpy( s+byte_pos, s+byte_pos + w, byte_len - byte_pos - w );
    STR(((KaroEdWidget)self)->karoEd.lines,y) = realloc(s, byte_len - w);
}
#line 405 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 405 "KaroEd.widget"
static void insert_char_at_cursor(Widget self,char * buf,int  len)
#else
#line 405 "KaroEd.widget"
static void insert_char_at_cursor(self,buf,len)Widget self;char * buf;int  len;
#endif
#line 406 "KaroEd.widget"
{
    uint32_t ucs4;
    int p;
    int x,y,w;
    char *s;
    int byte_len;
    int utf8_len;
    int byte_pos;

    x=((KaroEdWidget)self)->karoEd.rsel.x;
    y=((KaroEdWidget)self)->karoEd.rsel.y;

    while( y >= m_len(((KaroEdWidget)self)->karoEd.lines) ) {
        s=strdup("");
        m_put( ((KaroEdWidget)self)->karoEd.lines, &s );
    }


    s=STR(((KaroEdWidget)self)->karoEd.lines,y);
    byte_len = strlen(s);
    utf8_len = utf8_strlen(s);

    /* append data */
    if( x >= utf8_len ) {
        /* fill byte_len .. x */
        int n = x - utf8_len; /* append space */
        s = realloc(s,byte_len+n+len+1);
        while( n-- ) s[byte_len++] = 32;
        memcpy( s+byte_len, buf, len );
        s[byte_len+len] = 0;
        STR(((KaroEdWidget)self)->karoEd.lines,y) = s;
        return;
    }

    /* insert data */
    p=0;
    byte_len = strlen(s) +1;
    byte_pos = 0;
    while( p < x ) {
        w = FcUtf8ToUcs4 ((uint8_t*)s + byte_pos, &ucs4, byte_len - byte_pos);
        if( w <=0 ) break;
        byte_pos+=w; p++;
    }
    s = realloc(s, byte_len+len);
    STR(((KaroEdWidget)self)->karoEd.lines,y) = s;
    memcpy( s + byte_pos + len, s+byte_pos, byte_len - byte_pos );
    memcpy( s + byte_pos, buf, len );
}
#line 455 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 455 "KaroEd.widget"
static void cursor_right(Widget self)
#else
#line 455 "KaroEd.widget"
static void cursor_right(self)Widget self;
#endif
#line 456 "KaroEd.widget"
{
    ((KaroEdWidget)self)->karoEd.rsel.x++;
    if( ((KaroEdWidget)self)->karoEd.rsel.x >= ((KaroEdWidget)self)->karoEd.grid_width ) {
        ((KaroEdWidget)self)->karoEd.top_x = ((KaroEdWidget)self)->karoEd.rsel.x - ((KaroEdWidget)self)->karoEd.grid_width + 1;
        redraw_full(self);
    }
    selection_draw(self);
}
#line 466 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 466 "KaroEd.widget"
static Bool  cursor_pos1(Widget self)
#else
#line 466 "KaroEd.widget"
static Bool  cursor_pos1(self)Widget self;
#endif
#line 467 "KaroEd.widget"
{
    Bool redraw;
    redraw = ( ((KaroEdWidget)self)->karoEd.top_x != 0 );
    ((KaroEdWidget)self)->karoEd.top_x = 0;
    ((KaroEdWidget)self)->karoEd.rsel.x=0;
    return redraw;
}
#line 475 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 475 "KaroEd.widget"
static Bool  cursor_down(Widget self)
#else
#line 475 "KaroEd.widget"
static Bool  cursor_down(self)Widget self;
#endif
#line 476 "KaroEd.widget"
{
    Bool redraw;
    ((KaroEdWidget)self)->karoEd.rsel.y++;
    if( (redraw=((KaroEdWidget)self)->karoEd.rsel.y >= ((KaroEdWidget)self)->karoEd.grid_height) ) {
        ((KaroEdWidget)self)->karoEd.top_y = ((KaroEdWidget)self)->karoEd.rsel.y - ((KaroEdWidget)self)->karoEd.grid_height + 1;
    }
    return redraw;
}
#line 485 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 485 "KaroEd.widget"
static Bool  current_line_empty(Widget self)
#else
#line 485 "KaroEd.widget"
static Bool  current_line_empty(self)Widget self;
#endif
#line 486 "KaroEd.widget"
{
    int ln = ((KaroEdWidget)self)->karoEd.rsel.y;
    if( ln >= m_len(((KaroEdWidget)self)->karoEd.lines) ) return True;
    char *s = STR(((KaroEdWidget)self)->karoEd.lines,ln);
    return *s == 0;
}
#line 493 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 493 "KaroEd.widget"
static Bool  remove_current_line(Widget self)
#else
#line 493 "KaroEd.widget"
static Bool  remove_current_line(self)Widget self;
#endif
#line 494 "KaroEd.widget"
{
    int ln = ((KaroEdWidget)self)->karoEd.rsel.y;
    if( ln >= m_len(((KaroEdWidget)self)->karoEd.lines) ) return False;
    free( STR(((KaroEdWidget)self)->karoEd.lines, ln) );
    m_del(((KaroEdWidget)self)->karoEd.lines,ln);
    return True;
}
#line 502 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 502 "KaroEd.widget"
static Bool  insert_line(Widget self)
#else
#line 502 "KaroEd.widget"
static Bool  insert_line(self)Widget self;
#endif
#line 503 "KaroEd.widget"
{
    char *s;
    int y = ((KaroEdWidget)self)->karoEd.rsel.y;
    if( y < m_len(((KaroEdWidget)self)->karoEd.lines) ) {
        m_ins(((KaroEdWidget)self)->karoEd.lines,y,1);
        STR(((KaroEdWidget)self)->karoEd.lines,y) = strdup("");
    } else {
        while( y >= m_len(((KaroEdWidget)self)->karoEd.lines) ) {
            s=strdup("");
            m_put( ((KaroEdWidget)self)->karoEd.lines, &s );
        }
    }
    return True;

}
#line 520 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 520 "KaroEd.widget"
static char * utf8_skip(char * str,int  cnt)
#else
#line 520 "KaroEd.widget"
static char * utf8_skip(str,cnt)char * str;int  cnt;
#endif
#line 521 "KaroEd.widget"
{
    uint8_t *s = (uint8_t *) str;
    while( cnt && *s ) {
        cnt--;
        s++;
        while( (*s & 0b11000000) == 0b10000000 ) s++; /* utf8 */
    }
    return (char*) s;
}
#line 531 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 531 "KaroEd.widget"
static Bool  split_line_at_cursor(Widget self)
#else
#line 531 "KaroEd.widget"
static Bool  split_line_at_cursor(self)Widget self;
#endif
#line 532 "KaroEd.widget"
{
    int ln = ((KaroEdWidget)self)->karoEd.rsel.y;

    if( ln >= m_len(((KaroEdWidget)self)->karoEd.lines) ) return False;     /* kein text */

    char *s = STR(((KaroEdWidget)self)->karoEd.lines,ln);
    int utf8_len = utf8_strlen(s);
    char *s2, *new_line;
    int crsr_x = ((KaroEdWidget)self)->karoEd.rsel.x;

    if( ((KaroEdWidget)self)->karoEd.rsel.x < utf8_len ) {     /* innerhalb einer zeile */
        s2 = utf8_skip(s, crsr_x);
        new_line = strdup(s2);
        *s2 = 0;
        s = realloc(s, s2-s +1 );
        STR(((KaroEdWidget)self)->karoEd.lines,ln) = s;
    } else new_line = strdup("");  /* am ende einer zeile */

    ln++;
    m_ins(((KaroEdWidget)self)->karoEd.lines,ln,1);
    STR(((KaroEdWidget)self)->karoEd.lines,ln) = new_line;
    return True;
}
#line 557 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 557 "KaroEd.widget"
static void RequestSelection(Widget self,XtPointer  client,Atom * selection,Atom * type,XtPointer  value,unsigned  long * length,int * format)
#else
#line 557 "KaroEd.widget"
static void RequestSelection(self,client,selection,type,value,length,format)Widget self;XtPointer  client;Atom * selection;Atom * type;XtPointer  value;unsigned  long * length;int * format;
#endif
#line 558 "KaroEd.widget"
{
    char *s = value;
    int len = *length;
    if( is_empty(s) || len <= 0 ) return;
    insert_char_at_cursor(self,s,len);
    while( utf8char(&s) != -1 ) cursor_right(self);
    draw_line_from(self, ((KaroEdWidget)self)->karoEd.rsel.x, ((KaroEdWidget)self)->karoEd.rsel.y);
}
#line 568 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 568 "KaroEd.widget"
static void utf8_copy_char(int  buf,char ** strp)
#else
#line 568 "KaroEd.widget"
static void utf8_copy_char(buf,strp)int  buf;char ** strp;
#endif
#line 569 "KaroEd.widget"
{
    char *s = *strp;
    do {
        m_putc(buf,*s++);
    }
    while( (*s & 0b11000000) == 0b10000000 ); /* utf8 */
    *strp = s;
}
#line 578 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 578 "KaroEd.widget"
static Boolean  ConvertSelection(Widget self,Atom * selection,Atom * target,Atom * type,XtPointer * value,unsigned  long * length,int * format)
#else
#line 578 "KaroEd.widget"
static Boolean  ConvertSelection(self,selection,target,type,value,length,format)Widget self;Atom * selection;Atom * target;Atom * type;XtPointer * value;unsigned  long * length;int * format;
#endif
#line 579 "KaroEd.widget"
{

  XSelectionRequestEvent *req = XtGetSelectionRequest(self, *selection, NULL);

  /* client ask for possible types */
  if (*target == XA_TARGETS(XtDisplay(self))) {
      Atom *targetP, *std_targets;
      unsigned long std_length;

      /* get possible targets */
      XmuConvertStandardSelection(self, req->time, selection,
                                  target, type, (XPointer *) & std_targets,
                                  &std_length, format);

      *value = XtMalloc((unsigned) sizeof(Atom) * (std_length + 1));
      targetP = *(Atom **) value;

      *length = std_length + 1;     /* list of standard types */
      *targetP++ = ((KaroEdWidgetClass)self->core.widget_class)->karoEd_class.XA_UTF8_STRING;  /* prefered target */
      /* append standard targets */
      memmove((char *) targetP, (char *) std_targets, sizeof(Atom) * std_length);
      XtFree((char *) std_targets); /* remove original list */
      *type = XA_ATOM;
      *format = sizeof(Atom) * 8;
      return True;
  }
  else if (*target == ((KaroEdWidgetClass)self->core.widget_class)->karoEd_class.XA_UTF8_STRING) {
      *length = (long) m_len(((KaroEdWidget)self)->karoEd.selectionText);
      if( *length ) *value = strdup(m_buf(((KaroEdWidget)self)->karoEd.selectionText));
      else *value = 0;
      *type = ((KaroEdWidgetClass)self->core.widget_class)->karoEd_class.XA_UTF8_STRING;
      *format = 8;
      return True;
  }
  return False;
}
#line 619 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 619 "KaroEd.widget"
static void LoseSelection(Widget self,Atom * selection)
#else
#line 619 "KaroEd.widget"
static void LoseSelection(self,selection)Widget self;Atom * selection;
#endif
#line 620 "KaroEd.widget"
{
  ((KaroEdWidget)self)->karoEd.rsel.width=1;
  ((KaroEdWidget)self)->karoEd.rsel.height=1;
  selection_draw(self);
}
#line 626 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 626 "KaroEd.widget"
static void own_primary_selection(Widget self,ulong  time)
#else
#line 626 "KaroEd.widget"
static void own_primary_selection(self,time)Widget self;ulong  time;
#endif
#line 627 "KaroEd.widget"
{

    int ln = ((KaroEdWidget)self)->karoEd.rsel.y;
    if( ln >= m_len(((KaroEdWidget)self)->karoEd.lines) ) return;     /* kein text */
    char *s = STR(((KaroEdWidget)self)->karoEd.lines,ln);
    int utf8_len = utf8_strlen(s);
    if( ((KaroEdWidget)self)->karoEd.rsel.x >= utf8_len ) return;     /* kein text */
    int char_cnt = ((KaroEdWidget)self)->karoEd.rsel.width;

    /* clear buffer */
    m_clear( ((KaroEdWidget)self)->karoEd.selectionText );
    /* ptr to start of selection */
    s = utf8_skip(s, ((KaroEdWidget)self)->karoEd.rsel.x );
    /* copy selection */
    while( char_cnt ) {
        utf8_copy_char(((KaroEdWidget)self)->karoEd.selectionText, &s);
        char_cnt--;
    }
    m_putc(((KaroEdWidget)self)->karoEd.selectionText,0);

    XtOwnSelection(self, XA_PRIMARY, time,
                   ConvertSelection, LoseSelection, NULL);
    XChangeProperty(XtDisplay(self), DefaultRootWindow(XtDisplay(self)),
                    XA_CUT_BUFFER0, ((KaroEdWidgetClass)self->core.widget_class)->karoEd_class.XA_UTF8_STRING, 8, PropModeReplace,
                    (unsigned char *) m_buf(((KaroEdWidget)self)->karoEd.selectionText),
                    m_len(((KaroEdWidget)self)->karoEd.selectionText));
}

static XtResource resources[] = {
#line 8 "KaroEd.widget"
{XtNlocked,XtCLocked,XtRBool,sizeof(((KaroEdRec*)NULL)->karoEd.locked),XtOffsetOf(KaroEdRec,karoEd.locked),XtRImmediate,(XtPointer)0 },
#line 9 "KaroEd.widget"
{XtNlines,XtCLines,XtRStringMArray,sizeof(((KaroEdRec*)NULL)->karoEd.lines),XtOffsetOf(KaroEdRec,karoEd.lines),XtRImmediate,(XtPointer)0 },
#line 10 "KaroEd.widget"
{XtNmin_lines,XtCMin_lines,XtRInt,sizeof(((KaroEdRec*)NULL)->karoEd.min_lines),XtOffsetOf(KaroEdRec,karoEd.min_lines),XtRImmediate,(XtPointer)1 },
#line 11 "KaroEd.widget"
{XtNgrid_width,XtCGrid_width,XtRInt,sizeof(((KaroEdRec*)NULL)->karoEd.grid_width),XtOffsetOf(KaroEdRec,karoEd.grid_width),XtRImmediate,(XtPointer)1 },
#line 12 "KaroEd.widget"
{XtNgrid_height,XtCGrid_height,XtRInt,sizeof(((KaroEdRec*)NULL)->karoEd.grid_height),XtOffsetOf(KaroEdRec,karoEd.grid_height),XtRImmediate,(XtPointer)1 },
#line 13 "KaroEd.widget"
{XtNauto_resize,XtCAuto_resize,XtRInt,sizeof(((KaroEdRec*)NULL)->karoEd.auto_resize),XtOffsetOf(KaroEdRec,karoEd.auto_resize),XtRImmediate,(XtPointer)1 },
};

KaroEdClassRec karoEdClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &wheelClassRec,
/* class_name   	*/  "KaroEd",
/* widget_size  	*/  sizeof(KaroEdRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  realize,
/* actions      	*/  actionsList,
/* num_actions  	*/  17,
/* resources    	*/  resources,
/* num_resources 	*/  6,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  FALSE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  NULL,
/* resize       	*/  resize,
/* expose       	*/  expose,
/* set_values   	*/  NULL,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  defaultTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* Wheel_class part */
XtInherit_exec_command,
XtInherit_sig_recv,
},
{ /* KaroEd_class part */
/* XA_UTF8_STRING */  0 ,
},
};
WidgetClass karoEdWidgetClass = (WidgetClass) &karoEdClassRec;
/*ARGSUSED*/
#line 675 "KaroEd.widget"
static void copy_selection(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    /*
    XStoreBuffer(display, bytes, nbytes, buffer)
      Display *display;
      char *bytes;
      int nbytes;
      int buffer;
    */


}

/*ARGSUSED*/
#line 689 "KaroEd.widget"
static void insert_selection(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    XtGetSelectionValue(self, XA_PRIMARY, ((KaroEdWidgetClass)self->core.widget_class)->karoEd_class.XA_UTF8_STRING,
                        RequestSelection,
                        NULL, 0 );
}

/*ARGSUSED*/
#line 697 "KaroEd.widget"
static void key_return(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    Bool d = split_line_at_cursor(self) | cursor_down(self) | cursor_pos1(self);
    if( d )  redraw_full(self);
    selection_draw(self);
}

/*ARGSUSED*/
#line 704 "KaroEd.widget"
static void prev_line(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    if( ((KaroEdWidget)self)->karoEd.rsel.y == 0 ) return;
    ((KaroEdWidget)self)->karoEd.rsel.y--;
    if( ((KaroEdWidget)self)->karoEd.rsel.y < ((KaroEdWidget)self)->karoEd.top_y ) {
        ((KaroEdWidget)self)->karoEd.top_y = ((KaroEdWidget)self)->karoEd.rsel.y;
        redraw_full(self);
    }
    selection_draw(self);
}

/*ARGSUSED*/
#line 715 "KaroEd.widget"
static void next_line(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    ((KaroEdWidget)self)->karoEd.rsel.y++;
    if( ((KaroEdWidget)self)->karoEd.rsel.y >= ((KaroEdWidget)self)->karoEd.grid_height ) {
        ((KaroEdWidget)self)->karoEd.top_y = ((KaroEdWidget)self)->karoEd.rsel.y - ((KaroEdWidget)self)->karoEd.grid_height + 1;
        redraw_full(self);
    }
    selection_draw(self);
}

/*ARGSUSED*/
#line 725 "KaroEd.widget"
static void backward_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    if( ((KaroEdWidget)self)->karoEd.rsel.x == 0 ) return;
    ((KaroEdWidget)self)->karoEd.rsel.x--;
    if( ((KaroEdWidget)self)->karoEd.rsel.x < ((KaroEdWidget)self)->karoEd.top_x )
    {
        ((KaroEdWidget)self)->karoEd.top_x = ((KaroEdWidget)self)->karoEd.rsel.x;
        redraw_full(self);
    }
    selection_draw(self);
}

/*ARGSUSED*/
#line 737 "KaroEd.widget"
static void forward_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    cursor_right(self);
}

/*ARGSUSED*/
#line 743 "KaroEd.widget"
static void info(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    int i;
    for(i=0;i<m_len(((KaroEdWidget)self)->karoEd.lines);i++) {

        printf("'%s'\n", STR(((KaroEdWidget)self)->karoEd.lines,i));
    }
    printf("\n");
}

/*ARGSUSED*/
#line 754 "KaroEd.widget"
static void remove_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    /* could be expanded to remove region */
    if( current_line_empty(self) ) {
        remove_current_line(self);
        redraw_full(self);
    }
    else {
        remove_char_at_cursor(self);
        draw_line_from(self, ((KaroEdWidget)self)->karoEd.rsel.x, ((KaroEdWidget)self)->karoEd.rsel.y );
    }
}

/*ARGSUSED*/
#line 768 "KaroEd.widget"
static void insert_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    int len;
    unsigned char buf[32];
    KeySym key_sim;

    len = _XawLookupString(self,(XKeyEvent *) event, (char*)buf,sizeof buf, &key_sim );
    if (len <= 0) return;

    insert_char_at_cursor(self, (char*)buf, len );
    draw_line_from(self, ((KaroEdWidget)self)->karoEd.rsel.x, ((KaroEdWidget)self)->karoEd.rsel.y );
    cursor_right(self);
}

/*ARGSUSED*/
#line 785 "KaroEd.widget"
static void selection_clear(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    selection_clear_a(self);
}

/*ARGSUSED*/
#line 790 "KaroEd.widget"
static void selection_set(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    int y = event->xbutton.y;
    int x = event->xbutton.x;
    coordinate_to_text(self,&x,&y);
    ((KaroEdWidget)self)->karoEd.rsel.x=x; ((KaroEdWidget)self)->karoEd.rsel.width=1;
    ((KaroEdWidget)self)->karoEd.rsel.y=y; ((KaroEdWidget)self)->karoEd.rsel.height=1;
    selection_draw(self);
}

/*ARGSUSED*/
#line 801 "KaroEd.widget"
static void highlight(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
  if( ((KaroEdWidget)self)->karoEd.locked ) return;
}

/*ARGSUSED*/
#line 806 "KaroEd.widget"
static void reset(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
}

/*ARGSUSED*/
#line 810 "KaroEd.widget"
static void notify(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
  if( ((KaroEdWidget)self)->karoEd.locked ) return;
  ((KaroEdWidget)self)->karoEd.value = ((KaroEdWidget)self)->karoEd.value +1;
  XtVaSetValues(self,"label", get_name(self), NULL );
  XtCallCallbackList( self, ((KaroEdWidget)self)->wheel.callback, (XtPointer) ((KaroEdWidget)self)->karoEd.value );
}

/*ARGSUSED*/
#line 818 "KaroEd.widget"
static void selection_end(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    ulong t = (ulong ) event->xbutton.time;
    if( ((KaroEdWidget)self)->karoEd.rsel.width>1 ) own_primary_selection(self,t);
}

/*ARGSUSED*/
#line 826 "KaroEd.widget"
static void motion_start(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
  if( ((KaroEdWidget)self)->karoEd.locked ) return;

  int y = event->xbutton.y;
  int x = event->xbutton.x;
  ulong t = (ulong ) event->xbutton.time;


  int tx = x;
  int ty = y;
  coordinate_to_text(self,&tx,&ty);

  /* drag startete vor über einer sekunde, seitdem keine änderung */
  /* darum: vergessen und neu starten */
  if( ((KaroEdWidget)self)->karoEd.drag_update + 1000 < t ) goto restart_drag;
  ((KaroEdWidget)self)->karoEd.drag_update = t;

  if( selection_resize(self,tx,ty) ) {
      ((KaroEdWidget)self)->karoEd.drag_last_x = x;
      ((KaroEdWidget)self)->karoEd.drag_last_y = y;
      normalize_pos(self);
      selection_draw(self);
  }
  return; /* drag in progress */

  restart_drag:
  ((KaroEdWidget)self)->karoEd.drag_last_y = event->xbutton.y;
  ((KaroEdWidget)self)->karoEd.drag_last_x = event->xbutton.x;
  ((KaroEdWidget)self)->karoEd.drag_update = t;
  selection_start(self,tx,ty);
  selection_draw(self);
}

static void _resolve_inheritance(class)
WidgetClass class;
{
  KaroEdWidgetClass c __attribute__((unused)) = (KaroEdWidgetClass) class;
  KaroEdWidgetClass super __attribute__((unused));
  if (class == karoEdWidgetClass) return;
  super = (KaroEdWidgetClass)class->core_class.superclass;
}
#line 40 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 40 "KaroEd.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 40 "KaroEd.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 41 "KaroEd.widget"
{
    if(! ((KaroEdWidgetClass)self->core.widget_class)->karoEd_class.XA_UTF8_STRING )
        ((KaroEdWidgetClass)self->core.widget_class)->karoEd_class.XA_UTF8_STRING = XInternAtom(XtDisplay(self), "UTF8_STRING", True);

    if( ((KaroEdWidget)self)->karoEd.lines == 0 ) ((KaroEdWidget)self)->karoEd.lines = m_create(10,sizeof(char*));
    ((KaroEdWidget)self)->karoEd.selectionText = m_create(100,1);

    ((KaroEdWidget)self)->karoEd.do_init = 1;
    ((KaroEdWidget)self)->karoEd.top_x = ((KaroEdWidget)self)->karoEd.top_y = 0;
    ((KaroEdWidget)self)->karoEd.rsel.x = 0;
    ((KaroEdWidget)self)->karoEd.rsel.y = 0;
    ((KaroEdWidget)self)->karoEd.rsel.width = 1;
    ((KaroEdWidget)self)->karoEd.rsel.height = 1;
    ((KaroEdWidget)self)->karoEd.rsel_old = ((KaroEdWidget)self)->karoEd.rsel;
    ((KaroEdWidget)self)->karoEd.selection = True;
    ((KaroEdWidget)self)->karoEd.selection_visible = True;

    int w = ((KaroEdWidget)self)->wheel.xftFont->ascent + ((KaroEdWidget)self)->wheel.xftFont->descent;
    ((KaroEdWidget)self)->karoEd.grid_pix_height  = w;
    ((KaroEdWidget)self)->karoEd.grid_pix_width = xft_textwidth(XtDisplay(self), ((KaroEdWidget)self)->wheel.xftFont, "w" );

    if( ((KaroEdWidget)self)->core.height == 0 ) ((KaroEdWidget)self)->core.height = ((KaroEdWidget)self)->karoEd.grid_pix_height * ((KaroEdWidget)self)->karoEd.min_lines;
    if( ((KaroEdWidget)self)->core.width == 0  ) ((KaroEdWidget)self)->core.width = 20;
}
#line 70 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 70 "KaroEd.widget"
static void resize(Widget self)
#else
#line 70 "KaroEd.widget"
static void resize(self)Widget self;
#endif
#line 71 "KaroEd.widget"
{
    /* if( XtIsRealized($) ) reshape_widget($); */
    ((KaroEdWidget)self)->karoEd.do_init=1;
}
#line 76 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 76 "KaroEd.widget"
static void realize(Widget self,XtValueMask * mask,XSetWindowAttributes * attributes)
#else
#line 76 "KaroEd.widget"
static void realize(self,mask,attributes)Widget self;XtValueMask * mask;XSetWindowAttributes * attributes;
#endif
#line 77 "KaroEd.widget"
{
    Display *dpy = XtDisplay(self);
    XtCreateWindow(self, (unsigned int) InputOutput,
        		  (Visual *) CopyFromParent, *mask, attributes);
    ((KaroEdWidget)self)->karoEd.draw = XftDrawCreate(dpy, XtWindow(self),
                       DefaultVisual(dpy, DefaultScreen(dpy)), None);
}
#line 85 "KaroEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 85 "KaroEd.widget"
static void expose(Widget self,XEvent * event,Region  region)
#else
#line 85 "KaroEd.widget"
static void expose(self,event,region)Widget self;XEvent * event;Region  region;
#endif
#line 86 "KaroEd.widget"
{
        if( ((KaroEdWidget)self)->karoEd.do_init ) {
            if( ((KaroEdWidget)self)->karoEd.auto_resize ) {
              ((KaroEdWidget)self)->karoEd.grid_width = ((KaroEdWidget)self)->core.width / ((KaroEdWidget)self)->karoEd.grid_pix_width;
              ((KaroEdWidget)self)->karoEd.grid_height = ((KaroEdWidget)self)->core.height / ((KaroEdWidget)self)->karoEd.grid_pix_height;
            }
            ((KaroEdWidget)self)->karoEd.do_init=0;
         }

        XClearWindow(  XtDisplay(self), XtWindow(self) );
        redraw_full(self);
}
