/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 64 "Radio2.widget"
#include <xtcw/Gridbox.h>
#line 65 "Radio2.widget"
#include <xtcw/Wradio.h>
#line 66 "Radio2.widget"
#include "converters.h"
#line 67 "Radio2.widget"
#include "mls.h"
#include <xtcw/Radio2P.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 16 "Radio2.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 22 "Radio2.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 29 "Radio2.widget"
static void do_layout(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 49 "Radio2.widget"
static void select_child(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#line 57 "Radio2.widget"
static void change_cb(
#if NeedFunctionPrototypes
Widget ,Widget,XtPointer 
#endif
);
#line 29 "Radio2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 29 "Radio2.widget"
static void do_layout(Widget self)
#else
#line 29 "Radio2.widget"
static void do_layout(self)Widget self;
#endif
#line 30 "Radio2.widget"
{
        Widget w;
        int i;
        char *grid = "gridx";
        for( i=0; i<((Radio2Widget)self)->composite.num_children;i++ )
             XtDestroyWidget(((Radio2Widget)self)->composite.children[0]);
        for( i=0; i<m_len(((Radio2Widget)self)->radio2.lst); i++ ) {
             fprintf(stderr,"create %s\n", STR(((Radio2Widget)self)->radio2.lst,i));
             w = XtVaCreateManagedWidget(STR(((Radio2Widget)self)->radio2.lst,i),
                wradioWidgetClass, self,
                grid, i,
                "radioGroup", ((Radio2Widget)self)->radio2.radioGroup,
                "radioData", i,
                NULL );
             XtAddCallback(w, XtNcallback, (void*)change_cb, self );
        }
        select_child(self,((Radio2Widget)self)->radio2.value);
}
#line 49 "Radio2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 49 "Radio2.widget"
static void select_child(Widget self,int  num)
#else
#line 49 "Radio2.widget"
static void select_child(self,num)Widget self;int  num;
#endif
#line 50 "Radio2.widget"
{
        ((Radio2Widget)self)->radio2.value=num;
        if( ((Radio2Widget)self)->radio2.value >= m_len(((Radio2Widget)self)->radio2.lst) ) ((Radio2Widget)self)->radio2.value=0;
        if( ((Radio2Widget)self)->radio2.value < ((Radio2Widget)self)->composite.num_children )
            wradio_select(((Radio2Widget)self)->composite.children[((Radio2Widget)self)->radio2.value]);
}
#line 57 "Radio2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 57 "Radio2.widget"
static void change_cb(Widget  caller,Widget self,XtPointer  class)
#else
#line 57 "Radio2.widget"
static void change_cb(caller,self,class)Widget  caller;Widget self;XtPointer  class;
#endif
#line 58 "Radio2.widget"
{
        ((Radio2Widget)self)->radio2.value = (intptr_t) wradio_active_data(caller);
}

static XtResource resources[] = {
#line 9 "Radio2.widget"
{XtNlst,XtCLst,XtRStringMArray,sizeof(((Radio2Rec*)NULL)->radio2.lst),XtOffsetOf(Radio2Rec,radio2.lst),XtRString,(XtPointer)"Hello,World"},
#line 10 "Radio2.widget"
{XtNvalue,XtCValue,XtRInt,sizeof(((Radio2Rec*)NULL)->radio2.value),XtOffsetOf(Radio2Rec,radio2.value),XtRImmediate,(XtPointer)0 },
};

Radio2ClassRec radio2ClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &gridboxClassRec,
/* class_name   	*/  "Radio2",
/* widget_size  	*/  sizeof(Radio2Rec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  2,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  FALSE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  destroy,
/* resize       	*/  XtInheritResize,
/* expose       	*/  XtInheritExpose,
/* set_values   	*/  NULL,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  NULL,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* composite_class part */
XtInheritGeometryManager,
XtInheritChangeManaged,
XtInheritInsertChild,
XtInheritDeleteChild,
NULL
},
{ /* constraint_class part */
/* constraint_resources     */  NULL,
/* num_constraint_resources */  0,
/* constraint_size          */  sizeof(Radio2ConstraintRec),
/* constraint_initialize    */  NULL,
/* constraint_destroy       */  NULL,
/* constraint_set_values    */  NULL,
/* constraint_extension     */  NULL 
},
{ /* Gridbox_class part */
 /* dummy */  0
},
{ /* Radio2_class part */
 /* dummy */  0
},
};
WidgetClass radio2WidgetClass = (WidgetClass) &radio2ClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  Radio2WidgetClass c __attribute__((unused)) = (Radio2WidgetClass) class;
  Radio2WidgetClass super __attribute__((unused));
  static CompositeClassExtensionRec extension_rec = {
    NULL, NULLQUARK, XtCompositeExtensionVersion,
    sizeof(CompositeClassExtensionRec), True};
  CompositeClassExtensionRec *ext;
  ext = (XtPointer)XtMalloc(sizeof(*ext));
  *ext = extension_rec;
  ext->next_extension = c->composite_class.extension;
  c->composite_class.extension = ext;
  if (class == radio2WidgetClass) return;
  super = (Radio2WidgetClass)class->core_class.superclass;
}
#line 16 "Radio2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 16 "Radio2.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 16 "Radio2.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 17 "Radio2.widget"
{
        asprintf( & ((Radio2Widget)self)->radio2.radioGroup, "group_%p", (void*)self );
        do_layout(self);
}
#line 22 "Radio2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 22 "Radio2.widget"
static void destroy(Widget self)
#else
#line 22 "Radio2.widget"
static void destroy(self)Widget self;
#endif
#line 23 "Radio2.widget"
{
        free(((Radio2Widget)self)->radio2.radioGroup);
        m_free_strings(((Radio2Widget)self)->radio2.lst,0);
}
