/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 976 "TermEd.widget"
#include <stdint.h>
#line 977 "TermEd.widget"
#include "mls.h"
#line 978 "TermEd.widget"
#include "xutil.h"
#line 979 "TermEd.widget"
#include "micro_vars.h"
#line 980 "TermEd.widget"
#include "converters-xft.h"
#line 981 "TermEd.widget"
#include "subshell.h"
#line 982 "TermEd.widget"
#include "srvconnection.h"
#line 983 "TermEd.widget"
#include "command-parser.h"
#line 984 "TermEd.widget"
#include <X11/Xaw/XawImP.h>
#include <xtcw/TermEdP.h>
#line 882 "TermEd.widget"
static void kill_child(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 891 "TermEd.widget"
static void key_del(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 898 "TermEd.widget"
static void key_backspace(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 907 "TermEd.widget"
static void key_return(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 917 "TermEd.widget"
static void insert_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 942 "TermEd.widget"
static void prev_line(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 949 "TermEd.widget"
static void next_line(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 958 "TermEd.widget"
static void backward_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 965 "TermEd.widget"
static void forward_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);

static XtActionsRec actionsList[] = {
{"kill_child", kill_child},
{"key_del", key_del},
{"key_backspace", key_backspace},
{"key_return", key_return},
{"insert_char", insert_char},
{"prev_line", prev_line},
{"next_line", next_line},
{"backward_char", backward_char},
{"forward_char", forward_char},
};

static char defaultTranslations[] = "\
<Key>Right: forward_char() \n\
<Key>Left: backward_char() \n\
<Key>Up: prev_line() \n\
<Key>Down: next_line() \n\
<Key>Return: key_return() \n\
<Key>Delete: key_del() \n\
<Key>BackSpace: key_backspace() \n\
<Key>Escape: kill_child() \n\
<Key>: insert_char() \n\
";
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 40 "TermEd.widget"
static void class_initialize(
#if NeedFunctionPrototypes
void
#endif
);
#line 42 "TermEd.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 75 "TermEd.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 89 "TermEd.widget"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 99 "TermEd.widget"
static void resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 106 "TermEd.widget"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);
#line 123 "TermEd.widget"
static void font_free(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 130 "TermEd.widget"
static void font_load(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#line 140 "TermEd.widget"
static void draw_glyph_color(
#if NeedFunctionPrototypes
Widget,int ,int ,int ,int ,uint32_t 
#endif
);
#line 159 "TermEd.widget"
static void full_draw(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 170 "TermEd.widget"
static void putcharat(
#if NeedFunctionPrototypes
Widget,int ,int ,uint32_t 
#endif
);
#line 178 "TermEd.widget"
static uint32_t  getcharat(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 188 "TermEd.widget"
static void drawcharat(
#if NeedFunctionPrototypes
Widget,int ,int ,int ,int 
#endif
);
#line 196 "TermEd.widget"
static void draw_string(
#if NeedFunctionPrototypes
Widget,int ,int ,char *
#endif
);
#line 218 "TermEd.widget"
static void test_convert(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 223 "TermEd.widget"
static void selection_timer(
#if NeedFunctionPrototypes
Widget,XtIntervalId *
#endif
);
#line 236 "TermEd.widget"
static void undraw_selection(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 248 "TermEd.widget"
static void selection_draw(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 258 "TermEd.widget"
static void scr_scroll_up(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 265 "TermEd.widget"
static void pix_scroll_up(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 290 "TermEd.widget"
static void te_pos1(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 295 "TermEd.widget"
static void te_tab(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 304 "TermEd.widget"
static void te_down(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 316 "TermEd.widget"
static Bool  te_parse(
#if NeedFunctionPrototypes
Widget,uint32_t 
#endif
);
#line 327 "TermEd.widget"
static void te_right(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 338 "TermEd.widget"
static void pix_del(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 369 "TermEd.widget"
static void pix_ins(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 400 "TermEd.widget"
static void te_ins(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 419 "TermEd.widget"
static void te_del(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 437 "TermEd.widget"
static void te_putc(
#if NeedFunctionPrototypes
Widget,uint32_t 
#endif
);
#line 449 "TermEd.widget"
static void te_left(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 456 "TermEd.widget"
static void exec_line(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 486 "TermEd.widget"
static void prog_interpret(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 494 "TermEd.widget"
static void prog_child_pipe_read(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#line 524 "TermEd.widget"
static void prog_child_read_stdout(
#if NeedFunctionPrototypes
Widget,int *,XtInputId *
#endif
);
#line 529 "TermEd.widget"
static void prog_child_read_stderr(
#if NeedFunctionPrototypes
Widget,int *,XtInputId *
#endif
);
#line 535 "TermEd.widget"
static void prog_run(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 555 "TermEd.widget"
static char * progm_alloc(
#if NeedFunctionPrototypes
Widget,uint32_t ,char *
#endif
);
#line 564 "TermEd.widget"
static void progm_insert(
#if NeedFunctionPrototypes
Widget,int ,uint32_t ,char *
#endif
);
#line 570 "TermEd.widget"
static void progm_overwrite(
#if NeedFunctionPrototypes
Widget,int ,uint32_t ,char *
#endif
);
#line 576 "TermEd.widget"
static void progm_append(
#if NeedFunctionPrototypes
Widget,uint32_t ,char *
#endif
);
#line 589 "TermEd.widget"
static int  progm_find(
#if NeedFunctionPrototypes
Widget,uint32_t ,int *
#endif
);
#line 606 "TermEd.widget"
static void progm_put(
#if NeedFunctionPrototypes
Widget,uint32_t ,char *
#endif
);
#line 622 "TermEd.widget"
static Bool  prog_insert_line(
#if NeedFunctionPrototypes
Widget,char *
#endif
);
#line 640 "TermEd.widget"
static void prog_error(
#if NeedFunctionPrototypes
Widget,char *
#endif
);
#line 650 "TermEd.widget"
static void prog_load(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 677 "TermEd.widget"
static void prog_save(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 702 "TermEd.widget"
static void prog_parse(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 725 "TermEd.widget"
static void prog_list(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 750 "TermEd.widget"
static void te_write(
#if NeedFunctionPrototypes
Widget,char *
#endif
);
#line 766 "TermEd.widget"
static void te_writeln(
#if NeedFunctionPrototypes
Widget,char *
#endif
);
#line 774 "TermEd.widget"
static void prog_print(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#line 789 "TermEd.widget"
static void prog_do_list(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 805 "TermEd.widget"
static void prog_do_parse(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 823 "TermEd.widget"
static void prog_kill(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 834 "TermEd.widget"
static void do_resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 845 "TermEd.widget"
static void comm_exit_cb(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 851 "TermEd.widget"
static void comm_run_cb(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 857 "TermEd.widget"
static void comm_recv_cb(
#if NeedFunctionPrototypes
Widget,void *,void *
#endif
);
#line 123 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 123 "TermEd.widget"
static void font_free(Widget self)
#else
#line 123 "TermEd.widget"
static void font_free(self)Widget self;
#endif
#line 124 "TermEd.widget"
{
    Display *dpy = XtDisplay(self);
    if( ((TermEdWidget)self)->termEd.xftFont ) XftFontClose(dpy, ((TermEdWidget)self)->termEd.xftFont );
    ((TermEdWidget)self)->termEd.xftFont=0;
}
#line 130 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 130 "TermEd.widget"
static void font_load(Widget self,int  size)
#else
#line 130 "TermEd.widget"
static void font_load(self,size)Widget self;int  size;
#endif
#line 131 "TermEd.widget"
{
    Display *dpy = XtDisplay(self);
    int screen = DefaultScreen(dpy);
    char fontname[30];
    sprintf(fontname, "Source Code Pro-%d", ((TermEdWidget)self)->termEd.size );
    font_free(self);
    ((TermEdWidget)self)->termEd.xftFont = XftFontOpenName(dpy,screen, fontname );
}
#line 140 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 140 "TermEd.widget"
static void draw_glyph_color(Widget self,int  x,int  y,int  fg,int  bg,uint32_t  ucs4)
#else
#line 140 "TermEd.widget"
static void draw_glyph_color(self,x,y,fg,bg,ucs4)Widget self;int  x;int  y;int  fg;int  bg;uint32_t  ucs4;
#endif
#line 141 "TermEd.widget"
{
    int x0,y0,w,h;
    uint32_t glyph;

    x0 = x * ((TermEdWidget)self)->termEd.grid_pix_width;
    y0 = y * ((TermEdWidget)self)->termEd.grid_pix_height;
    w = ((TermEdWidget)self)->termEd.grid_pix_width;
    h = ((TermEdWidget)self)->termEd.grid_pix_height;

    if( bg >= 0 ) XftDrawRect(((TermEdWidget)self)->termEd.draw,((TermEdWidget)self)->termEd.col[bg], x0,y0,w,h );
    if( ucs4 == 0 || ucs4 == 32 ) return;

    glyph = XftCharIndex ( XtDisplay(self), ((TermEdWidget)self)->termEd.xftFont, ucs4 );
    XftDrawGlyphs (((TermEdWidget)self)->termEd.draw, ((TermEdWidget)self)->termEd.col[fg], ((TermEdWidget)self)->termEd.xftFont,
                   x0, y0+((TermEdWidget)self)->termEd.xftFont->ascent,
                   &glyph, 1);
}
#line 159 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 159 "TermEd.widget"
static void full_draw(Widget self)
#else
#line 159 "TermEd.widget"
static void full_draw(self)Widget self;
#endif
#line 160 "TermEd.widget"
{
    int x,y;
    XftDrawRect(((TermEdWidget)self)->termEd.draw,((TermEdWidget)self)->termEd.col[1], 0,0, ((TermEdWidget)self)->core.width, ((TermEdWidget)self)->core.height );
    for(x=0;x<((TermEdWidget)self)->termEd.gWidth;x++) {
        for(y=0;y<((TermEdWidget)self)->termEd.gHeight;y++) {
            draw_glyph_color(self,x,y,0,-1,((TermEdWidget)self)->termEd.scr[x + y * ((TermEdWidget)self)->termEd.gWidth ] );
        }
    }
}
#line 170 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 170 "TermEd.widget"
static void putcharat(Widget self,int  x,int  y,uint32_t  ucs4)
#else
#line 170 "TermEd.widget"
static void putcharat(self,x,y,ucs4)Widget self;int  x;int  y;uint32_t  ucs4;
#endif
#line 171 "TermEd.widget"
{
    if( x < ((TermEdWidget)self)->termEd.gWidth && x >= 0 && y < ((TermEdWidget)self)->termEd.gHeight && y >= 0 )
        {
            ((TermEdWidget)self)->termEd.scr[x + y * ((TermEdWidget)self)->termEd.gWidth ] = ucs4;
        }
}
#line 178 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 178 "TermEd.widget"
static uint32_t  getcharat(Widget self,int  x,int  y)
#else
#line 178 "TermEd.widget"
static uint32_t  getcharat(self,x,y)Widget self;int  x;int  y;
#endif
#line 179 "TermEd.widget"
{
    if( x < ((TermEdWidget)self)->termEd.gWidth && x >= 0 && y < ((TermEdWidget)self)->termEd.gHeight && y >= 0 )
        {
            return ((TermEdWidget)self)->termEd.scr[x + y * ((TermEdWidget)self)->termEd.gWidth ];
        }

    return 0;
}
#line 188 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 188 "TermEd.widget"
static void drawcharat(Widget self,int  x,int  y,int  fg,int  bg)
#else
#line 188 "TermEd.widget"
static void drawcharat(self,x,y,fg,bg)Widget self;int  x;int  y;int  fg;int  bg;
#endif
#line 189 "TermEd.widget"
{
    if( x < ((TermEdWidget)self)->termEd.gWidth && x >= 0 && y < ((TermEdWidget)self)->termEd.gHeight && y >= 0 )
        {
            draw_glyph_color(self,x,y,fg,bg,((TermEdWidget)self)->termEd.scr[x + y * ((TermEdWidget)self)->termEd.gWidth ] );
        }
}
#line 196 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 196 "TermEd.widget"
static void draw_string(Widget self,int  x,int  y,char * str)
#else
#line 196 "TermEd.widget"
static void draw_string(self,x,y,str)Widget self;int  x;int  y;char * str;
#endif
#line 197 "TermEd.widget"
{
    int len,l;
    unsigned char *string = (void*) str;
    uint32_t ucs4;
    len = strlen( (char*)string);
    x=0; y=0;
    while(1) {
        l = FcUtf8ToUcs4 (string, &ucs4, len);
        if( l<= 0 || len <=0 ) return;
        if( ucs4 == '\n' ) { x=0; y++; }
        if( x >= ((TermEdWidget)self)->termEd.gWidth ) { x=0; y++; }
        if( y >= ((TermEdWidget)self)->termEd.gHeight ) { y=0; }
        if( ucs4 >=' ' ) {
            putcharat(self,x,y,ucs4);
            x++;
        }
        string += l;
        len -= l;
    }
}
#line 218 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 218 "TermEd.widget"
static void test_convert(Widget self)
#else
#line 218 "TermEd.widget"
static void test_convert(self)Widget self;
#endif
#line 219 "TermEd.widget"
{
    draw_string(self, 0, ((TermEdWidget)self)->termEd.gHeight / 2, ((TermEdWidget)self)->termEd.text );
}
#line 223 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 223 "TermEd.widget"
static void selection_timer(Widget self,XtIntervalId * id)
#else
#line 223 "TermEd.widget"
static void selection_timer(self,id)Widget self;XtIntervalId * id;
#endif
#line 224 "TermEd.widget"
{
    int nr = ((TermEdWidget)self)->termEd.blink ? 2 : 0;
    if( ((TermEdWidget)self)->termEd.selection_visible ) {
        drawcharat(self, ((TermEdWidget)self)->termEd.rsel_old.x, ((TermEdWidget)self)->termEd.rsel_old.y, nr, nr+1 );
        ((TermEdWidget)self)->termEd.blink = ! ((TermEdWidget)self)->termEd.blink;
        if( id==NULL && ((TermEdWidget)self)->termEd.timerid ) XtRemoveTimeOut(((TermEdWidget)self)->termEd.timerid);
        ((TermEdWidget)self)->termEd.timerid = XtAppAddTimeOut(XtWidgetToApplicationContext(self), ((TermEdWidget)self)->termEd.selTime,
                        (void*)selection_timer, self );
    }
    else ((TermEdWidget)self)->termEd.timerid=0;
}
#line 236 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 236 "TermEd.widget"
static void undraw_selection(Widget self)
#else
#line 236 "TermEd.widget"
static void undraw_selection(self)Widget self;
#endif
#line 237 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.selection_visible ) {
        drawcharat(self, ((TermEdWidget)self)->termEd.rsel_old.x, ((TermEdWidget)self)->termEd.rsel_old.y, 0,1 );
        ((TermEdWidget)self)->termEd.selection_visible = False;
        if(((TermEdWidget)self)->termEd.timerid) {
            XtRemoveTimeOut(((TermEdWidget)self)->termEd.timerid);
            ((TermEdWidget)self)->termEd.timerid=0;
        }
    }
}
#line 248 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 248 "TermEd.widget"
static void selection_draw(Widget self)
#else
#line 248 "TermEd.widget"
static void selection_draw(self)Widget self;
#endif
#line 249 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.rsel.x >= ((TermEdWidget)self)->termEd.gWidth ) ((TermEdWidget)self)->termEd.rsel.x = ((TermEdWidget)self)->termEd.gWidth-1;
    if( ((TermEdWidget)self)->termEd.rsel.y >= ((TermEdWidget)self)->termEd.gHeight ) ((TermEdWidget)self)->termEd.rsel.y = ((TermEdWidget)self)->termEd.gHeight-1;
    undraw_selection(self);
    ((TermEdWidget)self)->termEd.selection_visible = True;
    ((TermEdWidget)self)->termEd.rsel_old = ((TermEdWidget)self)->termEd.rsel;
    ((TermEdWidget)self)->termEd.blink = True; selection_timer(self,0);
}
#line 258 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 258 "TermEd.widget"
static void scr_scroll_up(Widget self)
#else
#line 258 "TermEd.widget"
static void scr_scroll_up(self)Widget self;
#endif
#line 259 "TermEd.widget"
{
        memcpy( ((TermEdWidget)self)->termEd.scr, ((TermEdWidget)self)->termEd.scr + ((TermEdWidget)self)->termEd.gWidth,
                (((TermEdWidget)self)->termEd.gWidth*(((TermEdWidget)self)->termEd.gHeight-1))*4 );
        memset( ((TermEdWidget)self)->termEd.scr + ((TermEdWidget)self)->termEd.gWidth*(((TermEdWidget)self)->termEd.gHeight-1), 0, ((TermEdWidget)self)->termEd.gWidth*4 );
}
#line 265 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 265 "TermEd.widget"
static void pix_scroll_up(Widget self)
#else
#line 265 "TermEd.widget"
static void pix_scroll_up(self)Widget self;
#endif
#line 266 "TermEd.widget"
{
/*
      XCopyArea(display, src, dest, gc, src_x, src_y, width, height,  dest_x, dest_y)
      Display *display;
      Drawable src, dest;
      GC gc;
      int src_x, src_y;
      unsigned int width, height;
      int dest_x, dest_y;
*/
    XCopyArea(XtDisplay(self), XtWindow(self), XtWindow(self), DefaultGC(XtDisplay(self),0),
              0, ((TermEdWidget)self)->termEd.grid_pix_height,
              ((TermEdWidget)self)->termEd.grid_pix_width * (((TermEdWidget)self)->termEd.gWidth),
              ((TermEdWidget)self)->termEd.grid_pix_height * (((TermEdWidget)self)->termEd.gHeight-1),
              0,0 );

    /* clear background */
    XftDrawRect(((TermEdWidget)self)->termEd.draw,((TermEdWidget)self)->termEd.col[1],
    0,      ((TermEdWidget)self)->termEd.grid_pix_height * (((TermEdWidget)self)->termEd.gHeight-1),
    ((TermEdWidget)self)->core.width, ((TermEdWidget)self)->termEd.grid_pix_height );

}
#line 290 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 290 "TermEd.widget"
static void te_pos1(Widget self)
#else
#line 290 "TermEd.widget"
static void te_pos1(self)Widget self;
#endif
#line 291 "TermEd.widget"
{
    ((TermEdWidget)self)->termEd.rsel.x = 0;
}
#line 295 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 295 "TermEd.widget"
static void te_tab(Widget self)
#else
#line 295 "TermEd.widget"
static void te_tab(self)Widget self;
#endif
#line 296 "TermEd.widget"
{
    int x = ((TermEdWidget)self)->termEd.rsel.x;
    x /= 8;
    x ++;
    x *= 8;
    if( x < ((TermEdWidget)self)->termEd.gWidth ) ((TermEdWidget)self)->termEd.rsel.x = x;
}
#line 304 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 304 "TermEd.widget"
static void te_down(Widget self)
#else
#line 304 "TermEd.widget"
static void te_down(self)Widget self;
#endif
#line 305 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.rsel.y < (((TermEdWidget)self)->termEd.gHeight-1) ) {
        ((TermEdWidget)self)->termEd.rsel.y++;
        return;
    }

    pix_scroll_up(self);
    scr_scroll_up(self);
}
#line 316 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 316 "TermEd.widget"
static Bool  te_parse(Widget self,uint32_t  ucs4)
#else
#line 316 "TermEd.widget"
static Bool  te_parse(self,ucs4)Widget self;uint32_t  ucs4;
#endif
#line 317 "TermEd.widget"
{
    switch( ucs4 ) {
    default: break;
    case 10: te_pos1(self); te_down(self); return True;
    case '\t': te_tab(self); return True;
    case 13: te_pos1(self); return True;
    }
    return False;
}
#line 327 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 327 "TermEd.widget"
static void te_right(Widget self)
#else
#line 327 "TermEd.widget"
static void te_right(self)Widget self;
#endif
#line 328 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.rsel.x < (((TermEdWidget)self)->termEd.gWidth-1) ) {
        ((TermEdWidget)self)->termEd.rsel.x++;
        return;
    }
    te_pos1(self);
    te_down(self);
}
#line 338 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 338 "TermEd.widget"
static void pix_del(Widget self)
#else
#line 338 "TermEd.widget"
static void pix_del(self)Widget self;
#endif
#line 339 "TermEd.widget"
{
   int x0,y0,x1,y1,w,h,x,y;
   x = ((TermEdWidget)self)->termEd.rsel.x; y=((TermEdWidget)self)->termEd.rsel.y;
   /*-----------------------*/
   /* destination           */
   x0 = x;
   y0 = y;
   /*-----------------------*/
   /* width, height         */
   w = ((TermEdWidget)self)->termEd.gWidth - (x+1);
   h = 1;
   /*-----------------------*/
   /* source                */
   x1 = x0+1;
   y1 = y0;
   /*-----------------------*/
   /* transformation        */
   w   *= ((TermEdWidget)self)->termEd.grid_pix_width;
   x0  *= ((TermEdWidget)self)->termEd.grid_pix_width;
   x1  *= ((TermEdWidget)self)->termEd.grid_pix_width;
   h   *= ((TermEdWidget)self)->termEd.grid_pix_height;
   y0  *= ((TermEdWidget)self)->termEd.grid_pix_height;
   y1  *= ((TermEdWidget)self)->termEd.grid_pix_height;

   XCopyArea(XtDisplay(self), XtWindow(self), XtWindow(self), DefaultGC(XtDisplay(self),0),
             x1,y1,w,h, /* source */
             x0,y0      /* destination */
             );
}
#line 369 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 369 "TermEd.widget"
static void pix_ins(Widget self)
#else
#line 369 "TermEd.widget"
static void pix_ins(self)Widget self;
#endif
#line 370 "TermEd.widget"
{
   int x0,y0,x1,y1,w,h,x,y;
   x = ((TermEdWidget)self)->termEd.rsel.x; y=((TermEdWidget)self)->termEd.rsel.y;
   /*-----------------------*/
   /* destination           */
   x0 = x+1;
   y0 = y;
   /*-----------------------*/
   /* width, height         */
   w = ((TermEdWidget)self)->termEd.gWidth - (x+1);
   h = 1;
   /*-----------------------*/
   /* source                */
   x1 = x;
   y1 = y;
   /*-----------------------*/
   /* transformation        */
   w   *= ((TermEdWidget)self)->termEd.grid_pix_width;
   x0  *= ((TermEdWidget)self)->termEd.grid_pix_width;
   x1  *= ((TermEdWidget)self)->termEd.grid_pix_width;
   h   *= ((TermEdWidget)self)->termEd.grid_pix_height;
   y0  *= ((TermEdWidget)self)->termEd.grid_pix_height;
   y1  *= ((TermEdWidget)self)->termEd.grid_pix_height;

   XCopyArea(XtDisplay(self), XtWindow(self), XtWindow(self), DefaultGC(XtDisplay(self),0),
             x1,y1,w,h, /* source */
             x0,y0      /* destination */
             );
}
#line 400 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 400 "TermEd.widget"
static void te_ins(Widget self)
#else
#line 400 "TermEd.widget"
static void te_ins(self)Widget self;
#endif
#line 401 "TermEd.widget"
{
   int i,x,y;
   x = ((TermEdWidget)self)->termEd.rsel.x; y=((TermEdWidget)self)->termEd.rsel.y;
   uint32_t *s = ((TermEdWidget)self)->termEd.scr+y* ((TermEdWidget)self)->termEd.gWidth;

   /* letztes zeichen der zeile mit <null> füllen */
   if( x == ((TermEdWidget)self)->termEd.gWidth -1 ) {
      s[x] = 0;
      return;
   }

   for(i=((TermEdWidget)self)->termEd.gWidth-2; i>=x ; i-- )
              s[i+1] = s[i];
   pix_ins(self);
   s[x] = 32;
}
#line 419 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 419 "TermEd.widget"
static void te_del(Widget self)
#else
#line 419 "TermEd.widget"
static void te_del(self)Widget self;
#endif
#line 420 "TermEd.widget"
{
   uint16_t i,x,y;
   x = ((TermEdWidget)self)->termEd.rsel.x; y=((TermEdWidget)self)->termEd.rsel.y;
   uint32_t *s = ((TermEdWidget)self)->termEd.scr+y* ((TermEdWidget)self)->termEd.gWidth;

   /* letztes zeichen der zeile mit <null> füllen */
   if( x == ((TermEdWidget)self)->termEd.gWidth -1 ) {
      s[x] = 0;
      return;
   }

   for(i=x+1; i< ((TermEdWidget)self)->termEd.gWidth; i++ )
              s[i-1] = s[i];
   pix_del(self);
}
#line 437 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 437 "TermEd.widget"
static void te_putc(Widget self,uint32_t  ucs4)
#else
#line 437 "TermEd.widget"
static void te_putc(self,ucs4)Widget self;uint32_t  ucs4;
#endif
#line 438 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.rsel.x >= ((TermEdWidget)self)->termEd.gWidth ) ((TermEdWidget)self)->termEd.rsel.x = ((TermEdWidget)self)->termEd.gWidth-1;
    if( ((TermEdWidget)self)->termEd.rsel.y >= ((TermEdWidget)self)->termEd.gHeight ) ((TermEdWidget)self)->termEd.rsel.y = ((TermEdWidget)self)->termEd.gHeight-1;
    if( te_parse(self,ucs4) ) return;
    putcharat(self, ((TermEdWidget)self)->termEd.rsel.x, ((TermEdWidget)self)->termEd.rsel.y,ucs4);
    drawcharat(self, ((TermEdWidget)self)->termEd.rsel.x, ((TermEdWidget)self)->termEd.rsel.y, 0,1 );
    ((TermEdWidget)self)->termEd.selection_visible = False;
    te_right(self);
}
#line 449 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 449 "TermEd.widget"
static void te_left(Widget self)
#else
#line 449 "TermEd.widget"
static void te_left(self)Widget self;
#endif
#line 450 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.rsel.x == 0 ) return;
    ((TermEdWidget)self)->termEd.rsel.x--;
}
#line 456 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 456 "TermEd.widget"
static void exec_line(Widget self)
#else
#line 456 "TermEd.widget"
static void exec_line(self)Widget self;
#endif
#line 457 "TermEd.widget"
{
    int i,len, space_left;
    unsigned char *dest;
    // char *string = malloc( ((TermEdWidget)self)->termEd.gWidth * 6 + 2 );
    char *string = (void*)((TermEdWidget)self)->termEd.cmd;
    uint32_t *s = ((TermEdWidget)self)->termEd.scr + ((TermEdWidget)self)->termEd.rsel.y * ((TermEdWidget)self)->termEd.gWidth;
    dest = (void*)string;
    space_left = ((TermEdWidget)self)->termEd.cmd_len;
    for( i=0; i< ((TermEdWidget)self)->termEd.gWidth; i++ )
        {
            if( space_left < 7 ) break;
            len = FcUcs4ToUtf8( *s++, dest );
            dest+=len;
            space_left -= len;
        }
    *dest = 0;
    printf("str: %s\n", string );

    /* check if there is a line number prefix */
    if(! prog_insert_line(self, string) ) return;

    if( strncmp( string, "list", 4 ) == 0 ) prog_list(self);
    else if( strncmp( string, "save", 4 ) == 0 ) prog_save(self);
    else if( strncmp( string, "load", 4 ) == 0 ) prog_load(self);
    else if( strncmp( string, "run", 3 ) == 0 ) prog_run(self);
    else if( strncmp( string, "parse", 5 ) == 0 ) prog_parse(self);
    else if( ((TermEdWidget)self)->termEd.child ) prog_interpret(self);
}
#line 486 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 486 "TermEd.widget"
static void prog_interpret(Widget self)
#else
#line 486 "TermEd.widget"
static void prog_interpret(self)Widget self;
#endif
#line 487 "TermEd.widget"
{
    char *s = (void*)((TermEdWidget)self)->termEd.cmd;
    while(*s && *s == '>' ) s++;
    dprintf( ((TermEdWidget)self)->termEd.child->fd[3], "%s\n", s );
}
#line 494 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 494 "TermEd.widget"
static void prog_child_pipe_read(Widget self,int  pipe)
#else
#line 494 "TermEd.widget"
static void prog_child_pipe_read(self,pipe)Widget self;int  pipe;
#endif
#line 495 "TermEd.widget"
{
   if( ! ((TermEdWidget)self)->termEd.child ) ERR("memory corruption");

   if( fork2_read(((TermEdWidget)self)->termEd.child, pipe) ) {	
        prog_kill(self);
 	return;
   }

   int buf = m_create(50,1);	

   undraw_selection(self);
   
   while(! fork2_getline(((TermEdWidget)self)->termEd.child, pipe, buf ) ) {

      te_writeln(self, m_buf(buf));
      
      if( strncmp(m_buf(buf),"RUN",3)==0 ) {
      	  ((TermEdWidget)self)->termEd.INTERACTIVE=0;
	  fprintf(stderr, "interactive mode off\n" );
      }
      else if( strncmp(m_buf(buf),"EXIT",4)==0 ) {
      	  fprintf(stderr, "interactive mode ON\n" );
      	  ((TermEdWidget)self)->termEd.INTERACTIVE=1;
      }
   }
   selection_draw(self);

}
#line 524 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 524 "TermEd.widget"
static void prog_child_read_stdout(Widget self,int * source,XtInputId * id)
#else
#line 524 "TermEd.widget"
static void prog_child_read_stdout(self,source,id)Widget self;int * source;XtInputId * id;
#endif
#line 525 "TermEd.widget"
{
    prog_child_pipe_read(self, CHILD_STDOUT_RD );
}
#line 529 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 529 "TermEd.widget"
static void prog_child_read_stderr(Widget self,int * source,XtInputId * id)
#else
#line 529 "TermEd.widget"
static void prog_child_read_stderr(self,source,id)Widget self;int * source;XtInputId * id;
#endif
#line 530 "TermEd.widget"
{
    prog_child_pipe_read(self, CHILD_STDERR_RD );
}
#line 535 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 535 "TermEd.widget"
static void prog_run(Widget self)
#else
#line 535 "TermEd.widget"
static void prog_run(self)Widget self;
#endif
#line 536 "TermEd.widget"
{
        if( ((TermEdWidget)self)->termEd.child ) prog_kill(self);
        ((TermEdWidget)self)->termEd.child = fork2_open( "./interpreter.sh", "-i", NULL, "-e", "_PROMPT=''", NULL );
        ((TermEdWidget)self)->termEd.cid = XtAppAddInput( XtWidgetToApplicationContext(self),
                       ((TermEdWidget)self)->termEd.child->fd[CHILD_STDOUT_RD],
                       (XtPointer)XtInputReadMask,
                       (XtInputCallbackProc)prog_child_read_stdout,
                       self );

        ((TermEdWidget)self)->termEd.eid = XtAppAddInput( XtWidgetToApplicationContext(self),
                       ((TermEdWidget)self)->termEd.child->fd[CHILD_STDERR_RD],
                       (XtPointer)XtInputReadMask,
                       (XtInputCallbackProc)prog_child_read_stderr,
                       self );

         if( ((TermEdWidget)self)->termEd.child ) fork2_write(((TermEdWidget)self)->termEd.child, "hello world\n");
}
#line 555 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 555 "TermEd.widget"
static char * progm_alloc(Widget self,uint32_t  ln,char * s)
#else
#line 555 "TermEd.widget"
static char * progm_alloc(self,ln,s)Widget self;uint32_t  ln;char * s;
#endif
#line 556 "TermEd.widget"
{
        char *buf = malloc( 5 + strlen(s) );
        *(uint32_t *)buf = ln;
        while( isspace(*s) ) s++;
        strcpy( buf +4, s );
        return buf;
}
#line 564 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 564 "TermEd.widget"
static void progm_insert(Widget self,int  i,uint32_t  arg,char * s)
#else
#line 564 "TermEd.widget"
static void progm_insert(self,i,arg,s)Widget self;int  i;uint32_t  arg;char * s;
#endif
#line 565 "TermEd.widget"
{
        m_ins(((TermEdWidget)self)->termEd.progm,i, 1);
        STR(((TermEdWidget)self)->termEd.progm, i) = progm_alloc(self,arg,s);
}
#line 570 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 570 "TermEd.widget"
static void progm_overwrite(Widget self,int  i,uint32_t  arg,char * s)
#else
#line 570 "TermEd.widget"
static void progm_overwrite(self,i,arg,s)Widget self;int  i;uint32_t  arg;char * s;
#endif
#line 571 "TermEd.widget"
{
        free( STR(((TermEdWidget)self)->termEd.progm,i));
        STR(((TermEdWidget)self)->termEd.progm, i) = progm_alloc(self,arg,s);
}
#line 576 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 576 "TermEd.widget"
static void progm_append(Widget self,uint32_t  arg,char * s)
#else
#line 576 "TermEd.widget"
static void progm_append(self,arg,s)Widget self;uint32_t  arg;char * s;
#endif
#line 577 "TermEd.widget"
{
        char *buf = progm_alloc(self,arg,s);
        m_put( ((TermEdWidget)self)->termEd.progm, &buf );
}
#line 589 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 589 "TermEd.widget"
static int  progm_find(Widget self,uint32_t  num,int * pos)
#else
#line 589 "TermEd.widget"
static int  progm_find(self,num,pos)Widget self;uint32_t  num;int * pos;
#endif
#line 590 "TermEd.widget"
{
        int i;
        uint32_t n;
        char *s;

        for(i=0;i<m_len(((TermEdWidget)self)->termEd.progm);i++) {
          s= STR(((TermEdWidget)self)->termEd.progm,i);
          n = *(uint32_t *) s;
          if( n == num ) { *pos=i; return 0; }
          else if( n > num ) { *pos=i; return 1; };
        }
        *pos = i;
        return -1;
}
#line 606 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 606 "TermEd.widget"
static void progm_put(Widget self,uint32_t  arg,char * ln)
#else
#line 606 "TermEd.widget"
static void progm_put(self,arg,ln)Widget self;uint32_t  arg;char * ln;
#endif
#line 607 "TermEd.widget"
{
        int i;
        uint32_t n;
        char *s;

        for(i=0;i<m_len(((TermEdWidget)self)->termEd.progm);i++) {
          s= STR(((TermEdWidget)self)->termEd.progm,i);
          n = *(uint32_t *) s;
          if( n == arg ) { progm_overwrite( self, i, arg, ln ); return; }
          else if( n > arg ) { progm_insert(self, i, arg, ln ); return; }
        }
        progm_append(self,arg, ln );
}
#line 622 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 622 "TermEd.widget"
static Bool  prog_insert_line(Widget self,char * buf)
#else
#line 622 "TermEd.widget"
static Bool  prog_insert_line(self,buf)Widget self;char * buf;
#endif
#line 623 "TermEd.widget"
{
        char *s = (void*) buf;
        char *endp;
        int arg;

        arg = strtol( s,&endp,10);
        if( s == endp ) { return 1; }

        progm_put(self, arg, endp );
        return 0;
}
#line 640 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 640 "TermEd.widget"
static void prog_error(Widget self,char * s)
#else
#line 640 "TermEd.widget"
static void prog_error(self,s)Widget self;char * s;
#endif
#line 641 "TermEd.widget"
{
        te_down(self);
        te_pos1(self);
        te_write(self,s);
        te_down(self);
        te_pos1(self);
}
#line 650 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 650 "TermEd.widget"
static void prog_load(Widget self)
#else
#line 650 "TermEd.widget"
static void prog_load(self)Widget self;
#endif
#line 651 "TermEd.widget"
{
        char *s = (void*)((TermEdWidget)self)->termEd.cmd+5;
        int p = m_create(20,1);

        while( *s && ! isspace(*s) )
               m_putc( p, *s++ );
        m_putc(p,0);

        FILE *fp = fopen( m_buf(p), "r" );
        if( !fp ) { prog_error( self, "file read error" ); goto leave; }
        m_clear(p);


        while( m_fscan2( p, '\n', fp ) == '\n' ) {
                prog_insert_line(self,m_buf(p));
                m_clear(p);
        }

        fclose(fp);
        leave: m_free(p);

}
#line 677 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 677 "TermEd.widget"
static void prog_save(Widget self)
#else
#line 677 "TermEd.widget"
static void prog_save(self)Widget self;
#endif
#line 678 "TermEd.widget"
{
        /* get two integer args */
        char *s = (void*)((TermEdWidget)self)->termEd.cmd+5;
        int p = m_create(20,1);
        int i;

        while( *s && ! isspace(*s) )
               m_putc( p, *s++ );
        m_putc(p,0);

        FILE *fp = fopen( m_buf(p), "w" );
        if( !fp ) { prog_error( self, "file write error" ); goto leave; }

        for(i=0;i<m_len(((TermEdWidget)self)->termEd.progm);i++)
        {
                s = STR(((TermEdWidget)self)->termEd.progm,i);
                uint32_t n = *(uint32_t *)s; s+=4;
                fprintf(fp,"%u %s\n", n,s );
        }

        fclose(fp);
        leave: m_free(p);
}
#line 702 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 702 "TermEd.widget"
static void prog_parse(Widget self)
#else
#line 702 "TermEd.widget"
static void prog_parse(self)Widget self;
#endif
#line 703 "TermEd.widget"
{

    if(! ((TermEdWidget)self)->termEd.child ) {
        prog_error(self,"starting subshell with 'run'");
        prog_run(self);
    }

    int from,len;

    from = 0;
    len  = m_len(((TermEdWidget)self)->termEd.progm);

    /* get two integer args */
    char *s = (void*)((TermEdWidget)self)->termEd.cmd+6;
    char *endp;
    from = strtol( s,&endp,10);
    if( s == endp ) { from=0; goto cont; }

 cont:
    prog_do_parse(self, from, len);
}
#line 725 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 725 "TermEd.widget"
static void prog_list(Widget self)
#else
#line 725 "TermEd.widget"
static void prog_list(self)Widget self;
#endif
#line 726 "TermEd.widget"
{
        int arg,from,len;

        from = 0;
        len  = 10;

        /* get two integer args */
        char *s = (void*)((TermEdWidget)self)->termEd.cmd+5;
        char *endp;
        arg = strtol( s,&endp,10);
        if( s == endp ) { arg=0; goto cont; }

        s=endp; if( *s == ',' ) s++;
        from = arg;
        arg = strtol( s,&endp,10);
        if( s == endp ) { arg=0; goto cont; }
        len = arg;

        cont:
        te_pos1(self); te_down(self);
        prog_do_list(self, from, len);
}
#line 750 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 750 "TermEd.widget"
static void te_write(Widget self,char * str)
#else
#line 750 "TermEd.widget"
static void te_write(self,str)Widget self;char * str;
#endif
#line 751 "TermEd.widget"
{
    int len,l;
    unsigned char *string = (void*) str;
    uint32_t ucs4;
    len = strlen( (char*)string);

    while(1) {
        l = FcUtf8ToUcs4 (string, &ucs4, len);
        if( l<= 0 || len <=0 ) return;
        te_putc(self,ucs4);
        string += l;
        len -= l;
    }
}
#line 766 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 766 "TermEd.widget"
static void te_writeln(Widget self,char * s)
#else
#line 766 "TermEd.widget"
static void te_writeln(self,s)Widget self;char * s;
#endif
#line 767 "TermEd.widget"
{
        te_write(self,s);
        te_pos1(self);
        te_down(self);
}
#line 774 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 774 "TermEd.widget"
static void prog_print(Widget self,int  i)
#else
#line 774 "TermEd.widget"
static void prog_print(self,i)Widget self;int  i;
#endif
#line 775 "TermEd.widget"
{
        char buf[20];


        char *s = STR(((TermEdWidget)self)->termEd.progm,i);
        uint32_t num = *(uint32_t *)s;
        s+=4;

        sprintf(buf,"%d", num);
        te_write(self,buf);
        te_putc(self,32);
        te_write(self,s);
}
#line 789 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 789 "TermEd.widget"
static void prog_do_list(Widget self,int  from,int  len)
#else
#line 789 "TermEd.widget"
static void prog_do_list(self,from,len)Widget self;int  from;int  len;
#endif
#line 790 "TermEd.widget"
{
        int i;
        int line;

        int match  = progm_find( self, from, &line );
        if( match < 0 ) return;

        for(i=line;i<line+len;i++) {
                if( i >= m_len(((TermEdWidget)self)->termEd.progm) ) break;
                prog_print(self,i);
                te_pos1(self);
                te_down(self);
        }
}
#line 805 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 805 "TermEd.widget"
static void prog_do_parse(Widget self,int  from,int  len)
#else
#line 805 "TermEd.widget"
static void prog_do_parse(self,from,len)Widget self;int  from;int  len;
#endif
#line 806 "TermEd.widget"
{
        int i;
        int line;

        int match  = progm_find( self, from, &line );
        if( match < 0 ) return;

        for(i=line;i<line+len;i++) {
                if( i >= m_len(((TermEdWidget)self)->termEd.progm) ) break;
                char *s = STR(((TermEdWidget)self)->termEd.progm,i);
                s+=4;
                dprintf( ((TermEdWidget)self)->termEd.child->fd[3], "%s\n", s );
        }
}
#line 823 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 823 "TermEd.widget"
static void prog_kill(Widget self)
#else
#line 823 "TermEd.widget"
static void prog_kill(self)Widget self;
#endif
#line 824 "TermEd.widget"
{
        if( ((TermEdWidget)self)->termEd.child ) {
            fork2_close( ((TermEdWidget)self)->termEd.child );
            ((TermEdWidget)self)->termEd.child=0;
        }
        if( ((TermEdWidget)self)->termEd.cid ) { XtRemoveInput(((TermEdWidget)self)->termEd.cid); ((TermEdWidget)self)->termEd.cid=0; }
        if( ((TermEdWidget)self)->termEd.eid ) { XtRemoveInput(((TermEdWidget)self)->termEd.eid); ((TermEdWidget)self)->termEd.eid=0; }
	((TermEdWidget)self)->termEd.INTERACTIVE=1;
}
#line 834 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 834 "TermEd.widget"
static void do_resize(Widget self)
#else
#line 834 "TermEd.widget"
static void do_resize(self)Widget self;
#endif
#line 835 "TermEd.widget"
{
    ((TermEdWidget)self)->termEd.scr=realloc(((TermEdWidget)self)->termEd.scr, ((TermEdWidget)self)->termEd.gWidth * ((TermEdWidget)self)->termEd.gHeight * 4 );
    memset(((TermEdWidget)self)->termEd.scr,0,((TermEdWidget)self)->termEd.gWidth * ((TermEdWidget)self)->termEd.gHeight * 4 );
    ((TermEdWidget)self)->termEd.cmd=realloc(((TermEdWidget)self)->termEd.cmd,((TermEdWidget)self)->termEd.cmd_len = (((TermEdWidget)self)->termEd.gWidth+2) * 6 );
    printf("WxH=%dx%d\n",((TermEdWidget)self)->termEd.gWidth, ((TermEdWidget)self)->termEd.gHeight );
    printf("pix WxH=%dx%d\n",((TermEdWidget)self)->termEd.grid_pix_width, ((TermEdWidget)self)->termEd.grid_pix_height );
    printf("w WxH=%dx%d\n",((TermEdWidget)self)->core.width, ((TermEdWidget)self)->core.height );
}
#line 845 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 845 "TermEd.widget"
static void comm_exit_cb(Widget self)
#else
#line 845 "TermEd.widget"
static void comm_exit_cb(self)Widget self;
#endif
#line 846 "TermEd.widget"
{
	TRACE(2,"exit");
	((TermEdWidget)self)->termEd.INTERACTIVE=0;
}
#line 851 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 851 "TermEd.widget"
static void comm_run_cb(Widget self)
#else
#line 851 "TermEd.widget"
static void comm_run_cb(self)Widget self;
#endif
#line 852 "TermEd.widget"
{
	TRACE(2,"run");
	((TermEdWidget)self)->termEd.INTERACTIVE=1;
}
#line 857 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 857 "TermEd.widget"
static void comm_recv_cb(Widget self,void * u,void * d)
#else
#line 857 "TermEd.widget"
static void comm_recv_cb(self,u,d)Widget self;void * u;void * d;
#endif
#line 858 "TermEd.widget"
{
    TRACE(2,"read line");	
    int line = (intptr_t) d;
    if( line < 1 ) return;
    cp_func_t func = cp_lookup(line);
    if( func ) func(self);
}

static XtResource resources[] = {
#line 4 "TermEd.widget"
{XtNgWidth,XtCGWidth,XtRInt,sizeof(((TermEdRec*)NULL)->termEd.gWidth),XtOffsetOf(TermEdRec,termEd.gWidth),XtRImmediate,(XtPointer)40 },
#line 5 "TermEd.widget"
{XtNgHeight,XtCGHeight,XtRInt,sizeof(((TermEdRec*)NULL)->termEd.gHeight),XtOffsetOf(TermEdRec,termEd.gHeight),XtRImmediate,(XtPointer)25 },
#line 6 "TermEd.widget"
{XtNsize,XtCSize,XtRInt,sizeof(((TermEdRec*)NULL)->termEd.size),XtOffsetOf(TermEdRec,termEd.size),XtRImmediate,(XtPointer)8 },
#line 7 "TermEd.widget"
{XtNselTime,XtCSelTime,XtRInt,sizeof(((TermEdRec*)NULL)->termEd.selTime),XtOffsetOf(TermEdRec,termEd.selTime),XtRImmediate,(XtPointer)400 },
#line 8 "TermEd.widget"
{XtNtext,XtCText,XtRString,sizeof(((TermEdRec*)NULL)->termEd.text),XtOffsetOf(TermEdRec,termEd.text),XtRString,(XtPointer)"Hello World\nHow are you?"},
#line 9 "TermEd.widget"
{XtNfg,XtCFg,XtRXftColor,sizeof(((TermEdRec*)NULL)->termEd.fg),XtOffsetOf(TermEdRec,termEd.fg),XtRString,(XtPointer)"White"},
#line 10 "TermEd.widget"
{XtNbg,XtCBg,XtRXftColor,sizeof(((TermEdRec*)NULL)->termEd.bg),XtOffsetOf(TermEdRec,termEd.bg),XtRString,(XtPointer)"Darkgreen"},
#line 11 "TermEd.widget"
{XtNcbg,XtCCbg,XtRXftColor,sizeof(((TermEdRec*)NULL)->termEd.cbg),XtOffsetOf(TermEdRec,termEd.cbg),XtRString,(XtPointer)"Red"},
#line 12 "TermEd.widget"
{XtNcfg,XtCCfg,XtRXftColor,sizeof(((TermEdRec*)NULL)->termEd.cfg),XtOffsetOf(TermEdRec,termEd.cfg),XtRString,(XtPointer)"Green"},
#line 13 "TermEd.widget"
{XtNhost,XtCHost,XtRString,sizeof(((TermEdRec*)NULL)->termEd.host),XtOffsetOf(TermEdRec,termEd.host),XtRString,(XtPointer)"localhost"},
#line 14 "TermEd.widget"
{XtNport,XtCPort,XtRString,sizeof(((TermEdRec*)NULL)->termEd.port),XtOffsetOf(TermEdRec,termEd.port),XtRString,(XtPointer)"10002"},
};

TermEdClassRec termEdClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &coreClassRec,
/* class_name   	*/  "TermEd",
/* widget_size  	*/  sizeof(TermEdRec),
/* class_initialize 	*/  class_initialize,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  actionsList,
/* num_actions  	*/  9,
/* resources    	*/  resources,
/* num_resources 	*/  11,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  FALSE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  destroy,
/* resize       	*/  resize,
/* expose       	*/  expose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  defaultTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* TermEd_class part */
 /* dummy */  0
},
};
WidgetClass termEdWidgetClass = (WidgetClass) &termEdClassRec;
/*ARGSUSED*/
#line 882 "TermEd.widget"
static void kill_child(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    undraw_selection(self);
    te_writeln(self, "kill");
    prog_kill(self);

    selection_draw(self);
}

/*ARGSUSED*/
#line 891 "TermEd.widget"
static void key_del(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    undraw_selection(self);
    te_del(self);
    selection_draw(self);
}

/*ARGSUSED*/
#line 898 "TermEd.widget"
static void key_backspace(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    undraw_selection(self);
    te_left(self);
    te_del(self);
    selection_draw(self);
}

/*ARGSUSED*/
#line 907 "TermEd.widget"
static void key_return(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    undraw_selection(self);
    exec_line(self);
    te_pos1(self);
    te_down(self);
    selection_draw(self);
}

/*ARGSUSED*/
#line 917 "TermEd.widget"
static void insert_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    int len;
    unsigned char buf[32];
    KeySym key_sim;
    uint32_t ucs4;

    len = _XawLookupString(self,(XKeyEvent *) event, (char*)buf,sizeof buf, &key_sim );
    if (len <= 0) return;

    if(! ((TermEdWidget)self)->termEd.INTERACTIVE && ((TermEdWidget)self)->termEd.child ) {
    	     dprintf(((TermEdWidget)self)->termEd.child->fd[CHILD_STDIN_WR],"KEY: %*s\n",len,buf);	
             return;
    }
    

    FcUtf8ToUcs4 (buf, &ucs4, len);
    undraw_selection(self);
    te_ins(self);
    te_putc(self,ucs4);
    selection_draw(self);
}

/*ARGSUSED*/
#line 942 "TermEd.widget"
static void prev_line(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    if( ((TermEdWidget)self)->termEd.rsel.y == 0 ) return;
    ((TermEdWidget)self)->termEd.rsel.y--;
    selection_draw(self);
}

/*ARGSUSED*/
#line 949 "TermEd.widget"
static void next_line(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    undraw_selection(self);
    te_down(self);
    // if( ((TermEdWidget)self)->termEd.rsel.y < (((TermEdWidget)self)->termEd.gHeight-1) )
    // ((TermEdWidget)self)->termEd.rsel.y++;
    selection_draw(self);
}

/*ARGSUSED*/
#line 958 "TermEd.widget"
static void backward_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    if( ((TermEdWidget)self)->termEd.rsel.x == 0 ) return;
    ((TermEdWidget)self)->termEd.rsel.x--;
    selection_draw(self);
}

/*ARGSUSED*/
#line 965 "TermEd.widget"
static void forward_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    if( ((TermEdWidget)self)->termEd.rsel.x < (((TermEdWidget)self)->termEd.gWidth-1) )
        ((TermEdWidget)self)->termEd.rsel.x ++;
    selection_draw(self);
}

static void _resolve_inheritance(class)
WidgetClass class;
{
  TermEdWidgetClass c __attribute__((unused)) = (TermEdWidgetClass) class;
  TermEdWidgetClass super __attribute__((unused));
  if (class == termEdWidgetClass) return;
  super = (TermEdWidgetClass)class->core_class.superclass;
}
#line 40 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 40 "TermEd.widget"
static void class_initialize(void)
#else
#line 40 "TermEd.widget"
static void class_initialize()
#endif
#line 41 "TermEd.widget"
{ converters_xft_init(); }
#line 42 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 42 "TermEd.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 42 "TermEd.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 43 "TermEd.widget"
{
    FcChar32 bat = 0x42;
    XGlyphInfo extents;
    Display *dpy = XtDisplay(self);
    font_load(self,((TermEdWidget)self)->termEd.size);
    XftTextExtents32(dpy, ((TermEdWidget)self)->termEd.xftFont, &bat, 1, &extents);
    ((TermEdWidget)self)->core.height = (((TermEdWidget)self)->termEd.grid_pix_height = ((TermEdWidget)self)->termEd.xftFont->ascent + ((TermEdWidget)self)->termEd.xftFont->descent) * ((TermEdWidget)self)->termEd.gHeight;
    ((TermEdWidget)self)->core.width  = (((TermEdWidget)self)->termEd.grid_pix_width = extents.width) * ((TermEdWidget)self)->termEd.gWidth;
    ((TermEdWidget)self)->termEd.draw=0;
    ((TermEdWidget)self)->termEd.cmd=0;
    ((TermEdWidget)self)->termEd.scr=0;
    ((TermEdWidget)self)->termEd.child=0;
    ((TermEdWidget)self)->termEd.col[0] = & ((TermEdWidget)self)->termEd.fg;
    ((TermEdWidget)self)->termEd.col[1] = & ((TermEdWidget)self)->termEd.bg;
    ((TermEdWidget)self)->termEd.col[2] = & ((TermEdWidget)self)->termEd.cfg;
    ((TermEdWidget)self)->termEd.col[3] = & ((TermEdWidget)self)->termEd.cbg;
    ((TermEdWidget)self)->termEd.selection_visible = False;
    ((TermEdWidget)self)->termEd.timerid = 0;
    ((TermEdWidget)self)->termEd.gc_copy =  XtGetGC(self, 0,0 );
    ((TermEdWidget)self)->termEd.progm = m_create(100,sizeof(char*));
    do_resize(self);
    ((TermEdWidget)self)->termEd.INTERACTIVE=1;


    cp_init();
    cp_add( "EXIT", comm_exit_cb );
    cp_add( "RUN", comm_run_cb );
    
    ((TermEdWidget)self)->termEd.server_id = srvc_connect(self,((TermEdWidget)self)->termEd.host,((TermEdWidget)self)->termEd.port, comm_recv_cb, self);
}
#line 75 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 75 "TermEd.widget"
static void destroy(Widget self)
#else
#line 75 "TermEd.widget"
static void destroy(self)Widget self;
#endif
#line 76 "TermEd.widget"
{
	cp_destroy();
	
    if( ((TermEdWidget)self)->termEd.draw) XftDrawDestroy( ((TermEdWidget)self)->termEd.draw );
    ((TermEdWidget)self)->termEd.draw=0;
    font_free(self);
    if( ((TermEdWidget)self)->termEd.scr ) { free(((TermEdWidget)self)->termEd.scr); ((TermEdWidget)self)->termEd.scr=0; }
    if( ((TermEdWidget)self)->termEd.cmd ) { free(((TermEdWidget)self)->termEd.cmd); ((TermEdWidget)self)->termEd.cmd=0; }
    if( ((TermEdWidget)self)->termEd.progm ) { m_free_strings( ((TermEdWidget)self)->termEd.progm, 0); ((TermEdWidget)self)->termEd.progm=0; }
    if( ((TermEdWidget)self)->termEd.child ) prog_kill(self);

}
#line 89 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 89 "TermEd.widget"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 89 "TermEd.widget"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 90 "TermEd.widget"
{
    if( ((TermEdWidget)old)->termEd.size != ((TermEdWidget)self)->termEd.size ) {
        font_free(self);
        font_load(self,((TermEdWidget)self)->termEd.size);
        ((TermEdWidgetClass)self->core.widget_class)->core_class.resize( self );
    }
    return True; /* call expose */
}
#line 99 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 99 "TermEd.widget"
static void resize(Widget self)
#else
#line 99 "TermEd.widget"
static void resize(self)Widget self;
#endif
#line 100 "TermEd.widget"
{
    ((TermEdWidget)self)->termEd.gWidth  = ((TermEdWidget)self)->core.width / ((TermEdWidget)self)->termEd.grid_pix_width;
    ((TermEdWidget)self)->termEd.gHeight = ((TermEdWidget)self)->core.height / ((TermEdWidget)self)->termEd.grid_pix_height;
    do_resize(self);
}
#line 106 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 106 "TermEd.widget"
static void expose(Widget self,XEvent * event,Region  region)
#else
#line 106 "TermEd.widget"
static void expose(self,event,region)Widget self;XEvent * event;Region  region;
#endif
#line 107 "TermEd.widget"
{
    Display *dpy = XtDisplay(self);
    if(!((TermEdWidget)self)->termEd.draw )
        ((TermEdWidget)self)->termEd.draw = XftDrawCreate(dpy, XtWindow(self),
                              DefaultVisual(dpy, DefaultScreen(dpy)), None);
    test_convert(self);
    full_draw(self);
    selection_draw(self);
    /*   FcChar32 bat = 0xf240 + $status;
        XftDrawString32($draw, $col[$status],$xftFont,0,$xftFont->ascent,&bat,1);
    */
    printf("w WxH=%dx%d\n",((TermEdWidget)self)->core.width, ((TermEdWidget)self)->core.height );
}
