/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 919 "TermEd.widget"
#include <stdint.h>
#line 920 "TermEd.widget"
#include "mls.h"
#line 921 "TermEd.widget"
#include "xutil.h"
#line 922 "TermEd.widget"
#include "micro_vars.h"
#line 923 "TermEd.widget"
#include "converters-xft.h"
#line 924 "TermEd.widget"
#include "subshell.h"
#line 926 "TermEd.widget"
#include <X11/Xaw/XawImP.h>
#include <xtcw/TermEdP.h>
#line 832 "TermEd.widget"
static void kill_child(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 841 "TermEd.widget"
static void key_del(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 848 "TermEd.widget"
static void key_backspace(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 857 "TermEd.widget"
static void key_return(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 867 "TermEd.widget"
static void insert_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 885 "TermEd.widget"
static void prev_line(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 892 "TermEd.widget"
static void next_line(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 901 "TermEd.widget"
static void backward_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);
#line 908 "TermEd.widget"
static void forward_char(
#if NeedFunctionPrototypes
Widget,XEvent*,String*,Cardinal*
#endif
);

static XtActionsRec actionsList[] = {
{"kill_child", kill_child},
{"key_del", key_del},
{"key_backspace", key_backspace},
{"key_return", key_return},
{"insert_char", insert_char},
{"prev_line", prev_line},
{"next_line", next_line},
{"backward_char", backward_char},
{"forward_char", forward_char},
};

static char defaultTranslations[] = "\
<Key>Right: forward_char() \n\
<Key>Left: backward_char() \n\
<Key>Up: prev_line() \n\
<Key>Down: next_line() \n\
<Key>Return: key_return() \n\
<Key>Delete: key_del() \n\
<Key>BackSpace: key_backspace() \n\
<Key>Escape: kill_child() \n\
<Key>: insert_char() \n\
";
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 35 "TermEd.widget"
static void class_initialize(
#if NeedFunctionPrototypes
void
#endif
);
#line 37 "TermEd.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 62 "TermEd.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 74 "TermEd.widget"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 84 "TermEd.widget"
static void resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 91 "TermEd.widget"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);
#line 108 "TermEd.widget"
static void font_free(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 115 "TermEd.widget"
static void font_load(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#line 125 "TermEd.widget"
static void draw_glyph_color(
#if NeedFunctionPrototypes
Widget,int ,int ,int ,int ,uint32_t 
#endif
);
#line 144 "TermEd.widget"
static void full_draw(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 155 "TermEd.widget"
static void putcharat(
#if NeedFunctionPrototypes
Widget,int ,int ,uint32_t 
#endif
);
#line 163 "TermEd.widget"
static uint32_t  getcharat(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 173 "TermEd.widget"
static void drawcharat(
#if NeedFunctionPrototypes
Widget,int ,int ,int ,int 
#endif
);
#line 181 "TermEd.widget"
static void draw_string(
#if NeedFunctionPrototypes
Widget,int ,int ,char *
#endif
);
#line 203 "TermEd.widget"
static void test_convert(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 208 "TermEd.widget"
static void selection_timer(
#if NeedFunctionPrototypes
Widget,XtIntervalId *
#endif
);
#line 221 "TermEd.widget"
static void undraw_selection(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 233 "TermEd.widget"
static void selection_draw(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 243 "TermEd.widget"
static void scr_scroll_up(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 250 "TermEd.widget"
static void pix_scroll_up(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 275 "TermEd.widget"
static void te_pos1(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 280 "TermEd.widget"
static void te_tab(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 289 "TermEd.widget"
static void te_down(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 301 "TermEd.widget"
static Bool  te_parse(
#if NeedFunctionPrototypes
Widget,uint32_t 
#endif
);
#line 312 "TermEd.widget"
static void te_right(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 323 "TermEd.widget"
static void pix_del(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 354 "TermEd.widget"
static void pix_ins(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 385 "TermEd.widget"
static void te_ins(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 404 "TermEd.widget"
static void te_del(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 422 "TermEd.widget"
static void te_putc(
#if NeedFunctionPrototypes
Widget,uint32_t 
#endif
);
#line 434 "TermEd.widget"
static void te_left(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 441 "TermEd.widget"
static void exec_line(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 471 "TermEd.widget"
static void prog_interpret(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 479 "TermEd.widget"
static void prog_child_read(
#if NeedFunctionPrototypes
Widget,int *,XtInputId *
#endif
);
#line 493 "TermEd.widget"
static void prog_child_err_read(
#if NeedFunctionPrototypes
Widget,int *,XtInputId *
#endif
);
#line 508 "TermEd.widget"
static void prog_run(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 529 "TermEd.widget"
static char * progm_alloc(
#if NeedFunctionPrototypes
Widget,uint32_t ,char *
#endif
);
#line 538 "TermEd.widget"
static void progm_insert(
#if NeedFunctionPrototypes
Widget,int ,uint32_t ,char *
#endif
);
#line 544 "TermEd.widget"
static void progm_overwrite(
#if NeedFunctionPrototypes
Widget,int ,uint32_t ,char *
#endif
);
#line 550 "TermEd.widget"
static void progm_append(
#if NeedFunctionPrototypes
Widget,uint32_t ,char *
#endif
);
#line 563 "TermEd.widget"
static int  progm_find(
#if NeedFunctionPrototypes
Widget,uint32_t ,int *
#endif
);
#line 580 "TermEd.widget"
static void progm_put(
#if NeedFunctionPrototypes
Widget,uint32_t ,char *
#endif
);
#line 596 "TermEd.widget"
static Bool  prog_insert_line(
#if NeedFunctionPrototypes
Widget,char *
#endif
);
#line 614 "TermEd.widget"
static void prog_error(
#if NeedFunctionPrototypes
Widget,char *
#endif
);
#line 624 "TermEd.widget"
static void prog_load(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 651 "TermEd.widget"
static void prog_save(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 676 "TermEd.widget"
static void prog_parse(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 699 "TermEd.widget"
static void prog_list(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 724 "TermEd.widget"
static void te_write(
#if NeedFunctionPrototypes
Widget,char *
#endif
);
#line 740 "TermEd.widget"
static void te_writeln(
#if NeedFunctionPrototypes
Widget,char *
#endif
);
#line 748 "TermEd.widget"
static void prog_print(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#line 763 "TermEd.widget"
static void prog_do_list(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 779 "TermEd.widget"
static void prog_do_parse(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 797 "TermEd.widget"
static void prog_kill(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 807 "TermEd.widget"
static void do_resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 108 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 108 "TermEd.widget"
static void font_free(Widget self)
#else
#line 108 "TermEd.widget"
static void font_free(self)Widget self;
#endif
#line 109 "TermEd.widget"
{
    Display *dpy = XtDisplay(self);
    if( ((TermEdWidget)self)->termEd.xftFont ) XftFontClose(dpy, ((TermEdWidget)self)->termEd.xftFont );
    ((TermEdWidget)self)->termEd.xftFont=0;
}
#line 115 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 115 "TermEd.widget"
static void font_load(Widget self,int  size)
#else
#line 115 "TermEd.widget"
static void font_load(self,size)Widget self;int  size;
#endif
#line 116 "TermEd.widget"
{
    Display *dpy = XtDisplay(self);
    int screen = DefaultScreen(dpy);
    char fontname[30];
    sprintf(fontname, "Source Code Pro-%d", ((TermEdWidget)self)->termEd.size );
    font_free(self);
    ((TermEdWidget)self)->termEd.xftFont = XftFontOpenName(dpy,screen, fontname );
}
#line 125 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 125 "TermEd.widget"
static void draw_glyph_color(Widget self,int  x,int  y,int  fg,int  bg,uint32_t  ucs4)
#else
#line 125 "TermEd.widget"
static void draw_glyph_color(self,x,y,fg,bg,ucs4)Widget self;int  x;int  y;int  fg;int  bg;uint32_t  ucs4;
#endif
#line 126 "TermEd.widget"
{
    int x0,y0,w,h;
    uint32_t glyph;

    x0 = x * ((TermEdWidget)self)->termEd.grid_pix_width;
    y0 = y * ((TermEdWidget)self)->termEd.grid_pix_height;
    w = ((TermEdWidget)self)->termEd.grid_pix_width;
    h = ((TermEdWidget)self)->termEd.grid_pix_height;

    if( bg >= 0 ) XftDrawRect(((TermEdWidget)self)->termEd.draw,((TermEdWidget)self)->termEd.col[bg], x0,y0,w,h );
    if( ucs4 == 0 || ucs4 == 32 ) return;

    glyph = XftCharIndex ( XtDisplay(self), ((TermEdWidget)self)->termEd.xftFont, ucs4 );
    XftDrawGlyphs (((TermEdWidget)self)->termEd.draw, ((TermEdWidget)self)->termEd.col[fg], ((TermEdWidget)self)->termEd.xftFont,
                   x0, y0+((TermEdWidget)self)->termEd.xftFont->ascent,
                   &glyph, 1);
}
#line 144 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 144 "TermEd.widget"
static void full_draw(Widget self)
#else
#line 144 "TermEd.widget"
static void full_draw(self)Widget self;
#endif
#line 145 "TermEd.widget"
{
    int x,y;
    XftDrawRect(((TermEdWidget)self)->termEd.draw,((TermEdWidget)self)->termEd.col[1], 0,0, ((TermEdWidget)self)->core.width, ((TermEdWidget)self)->core.height );
    for(x=0;x<((TermEdWidget)self)->termEd.gWidth;x++) {
        for(y=0;y<((TermEdWidget)self)->termEd.gHeight;y++) {
            draw_glyph_color(self,x,y,0,-1,((TermEdWidget)self)->termEd.scr[x + y * ((TermEdWidget)self)->termEd.gWidth ] );
        }
    }
}
#line 155 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 155 "TermEd.widget"
static void putcharat(Widget self,int  x,int  y,uint32_t  ucs4)
#else
#line 155 "TermEd.widget"
static void putcharat(self,x,y,ucs4)Widget self;int  x;int  y;uint32_t  ucs4;
#endif
#line 156 "TermEd.widget"
{
    if( x < ((TermEdWidget)self)->termEd.gWidth && x >= 0 && y < ((TermEdWidget)self)->termEd.gHeight && y >= 0 )
        {
            ((TermEdWidget)self)->termEd.scr[x + y * ((TermEdWidget)self)->termEd.gWidth ] = ucs4;
        }
}
#line 163 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 163 "TermEd.widget"
static uint32_t  getcharat(Widget self,int  x,int  y)
#else
#line 163 "TermEd.widget"
static uint32_t  getcharat(self,x,y)Widget self;int  x;int  y;
#endif
#line 164 "TermEd.widget"
{
    if( x < ((TermEdWidget)self)->termEd.gWidth && x >= 0 && y < ((TermEdWidget)self)->termEd.gHeight && y >= 0 )
        {
            return ((TermEdWidget)self)->termEd.scr[x + y * ((TermEdWidget)self)->termEd.gWidth ];
        }

    return 0;
}
#line 173 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 173 "TermEd.widget"
static void drawcharat(Widget self,int  x,int  y,int  fg,int  bg)
#else
#line 173 "TermEd.widget"
static void drawcharat(self,x,y,fg,bg)Widget self;int  x;int  y;int  fg;int  bg;
#endif
#line 174 "TermEd.widget"
{
    if( x < ((TermEdWidget)self)->termEd.gWidth && x >= 0 && y < ((TermEdWidget)self)->termEd.gHeight && y >= 0 )
        {
            draw_glyph_color(self,x,y,fg,bg,((TermEdWidget)self)->termEd.scr[x + y * ((TermEdWidget)self)->termEd.gWidth ] );
        }
}
#line 181 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 181 "TermEd.widget"
static void draw_string(Widget self,int  x,int  y,char * str)
#else
#line 181 "TermEd.widget"
static void draw_string(self,x,y,str)Widget self;int  x;int  y;char * str;
#endif
#line 182 "TermEd.widget"
{
    int len,l;
    unsigned char *string = (void*) str;
    uint32_t ucs4;
    len = strlen( (char*)string);
    x=0; y=0;
    while(1) {
        l = FcUtf8ToUcs4 (string, &ucs4, len);
        if( l<= 0 || len <=0 ) return;
        if( ucs4 == '\n' ) { x=0; y++; }
        if( x >= ((TermEdWidget)self)->termEd.gWidth ) { x=0; y++; }
        if( y >= ((TermEdWidget)self)->termEd.gHeight ) { y=0; }
        if( ucs4 >=' ' ) {
            putcharat(self,x,y,ucs4);
            x++;
        }
        string += l;
        len -= l;
    }
}
#line 203 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 203 "TermEd.widget"
static void test_convert(Widget self)
#else
#line 203 "TermEd.widget"
static void test_convert(self)Widget self;
#endif
#line 204 "TermEd.widget"
{
    draw_string(self, 0, ((TermEdWidget)self)->termEd.gHeight / 2, ((TermEdWidget)self)->termEd.text );
}
#line 208 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 208 "TermEd.widget"
static void selection_timer(Widget self,XtIntervalId * id)
#else
#line 208 "TermEd.widget"
static void selection_timer(self,id)Widget self;XtIntervalId * id;
#endif
#line 209 "TermEd.widget"
{
    int nr = ((TermEdWidget)self)->termEd.blink ? 2 : 0;
    if( ((TermEdWidget)self)->termEd.selection_visible ) {
        drawcharat(self, ((TermEdWidget)self)->termEd.rsel_old.x, ((TermEdWidget)self)->termEd.rsel_old.y, nr, nr+1 );
        ((TermEdWidget)self)->termEd.blink = ! ((TermEdWidget)self)->termEd.blink;
        if( id==NULL && ((TermEdWidget)self)->termEd.timerid ) XtRemoveTimeOut(((TermEdWidget)self)->termEd.timerid);
        ((TermEdWidget)self)->termEd.timerid = XtAppAddTimeOut(XtWidgetToApplicationContext(self), ((TermEdWidget)self)->termEd.selTime,
                        (void*)selection_timer, self );
    }
    else ((TermEdWidget)self)->termEd.timerid=0;
}
#line 221 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 221 "TermEd.widget"
static void undraw_selection(Widget self)
#else
#line 221 "TermEd.widget"
static void undraw_selection(self)Widget self;
#endif
#line 222 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.selection_visible ) {
        drawcharat(self, ((TermEdWidget)self)->termEd.rsel_old.x, ((TermEdWidget)self)->termEd.rsel_old.y, 0,1 );
        ((TermEdWidget)self)->termEd.selection_visible = False;
        if(((TermEdWidget)self)->termEd.timerid) {
            XtRemoveTimeOut(((TermEdWidget)self)->termEd.timerid);
            ((TermEdWidget)self)->termEd.timerid=0;
        }
    }
}
#line 233 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 233 "TermEd.widget"
static void selection_draw(Widget self)
#else
#line 233 "TermEd.widget"
static void selection_draw(self)Widget self;
#endif
#line 234 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.rsel.x >= ((TermEdWidget)self)->termEd.gWidth ) ((TermEdWidget)self)->termEd.rsel.x = ((TermEdWidget)self)->termEd.gWidth-1;
    if( ((TermEdWidget)self)->termEd.rsel.y >= ((TermEdWidget)self)->termEd.gHeight ) ((TermEdWidget)self)->termEd.rsel.y = ((TermEdWidget)self)->termEd.gHeight-1;
    undraw_selection(self);
    ((TermEdWidget)self)->termEd.selection_visible = True;
    ((TermEdWidget)self)->termEd.rsel_old = ((TermEdWidget)self)->termEd.rsel;
    ((TermEdWidget)self)->termEd.blink = True; selection_timer(self,0);
}
#line 243 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 243 "TermEd.widget"
static void scr_scroll_up(Widget self)
#else
#line 243 "TermEd.widget"
static void scr_scroll_up(self)Widget self;
#endif
#line 244 "TermEd.widget"
{
        memcpy( ((TermEdWidget)self)->termEd.scr, ((TermEdWidget)self)->termEd.scr + ((TermEdWidget)self)->termEd.gWidth,
                (((TermEdWidget)self)->termEd.gWidth*(((TermEdWidget)self)->termEd.gHeight-1))*4 );
        memset( ((TermEdWidget)self)->termEd.scr + ((TermEdWidget)self)->termEd.gWidth*(((TermEdWidget)self)->termEd.gHeight-1), 0, ((TermEdWidget)self)->termEd.gWidth*4 );
}
#line 250 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 250 "TermEd.widget"
static void pix_scroll_up(Widget self)
#else
#line 250 "TermEd.widget"
static void pix_scroll_up(self)Widget self;
#endif
#line 251 "TermEd.widget"
{
/*
      XCopyArea(display, src, dest, gc, src_x, src_y, width, height,  dest_x, dest_y)
      Display *display;
      Drawable src, dest;
      GC gc;
      int src_x, src_y;
      unsigned int width, height;
      int dest_x, dest_y;
*/
    XCopyArea(XtDisplay(self), XtWindow(self), XtWindow(self), DefaultGC(XtDisplay(self),0),
              0, ((TermEdWidget)self)->termEd.grid_pix_height,
              ((TermEdWidget)self)->termEd.grid_pix_width * (((TermEdWidget)self)->termEd.gWidth),
              ((TermEdWidget)self)->termEd.grid_pix_height * (((TermEdWidget)self)->termEd.gHeight-1),
              0,0 );

    /* clear background */
    XftDrawRect(((TermEdWidget)self)->termEd.draw,((TermEdWidget)self)->termEd.col[1],
    0,      ((TermEdWidget)self)->termEd.grid_pix_height * (((TermEdWidget)self)->termEd.gHeight-1),
    ((TermEdWidget)self)->core.width, ((TermEdWidget)self)->termEd.grid_pix_height );

}
#line 275 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 275 "TermEd.widget"
static void te_pos1(Widget self)
#else
#line 275 "TermEd.widget"
static void te_pos1(self)Widget self;
#endif
#line 276 "TermEd.widget"
{
    ((TermEdWidget)self)->termEd.rsel.x = 0;
}
#line 280 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 280 "TermEd.widget"
static void te_tab(Widget self)
#else
#line 280 "TermEd.widget"
static void te_tab(self)Widget self;
#endif
#line 281 "TermEd.widget"
{
    int x = ((TermEdWidget)self)->termEd.rsel.x;
    x /= 8;
    x ++;
    x *= 8;
    if( x < ((TermEdWidget)self)->termEd.gWidth ) ((TermEdWidget)self)->termEd.rsel.x = x;
}
#line 289 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 289 "TermEd.widget"
static void te_down(Widget self)
#else
#line 289 "TermEd.widget"
static void te_down(self)Widget self;
#endif
#line 290 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.rsel.y < (((TermEdWidget)self)->termEd.gHeight-1) ) {
        ((TermEdWidget)self)->termEd.rsel.y++;
        return;
    }

    pix_scroll_up(self);
    scr_scroll_up(self);
}
#line 301 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 301 "TermEd.widget"
static Bool  te_parse(Widget self,uint32_t  ucs4)
#else
#line 301 "TermEd.widget"
static Bool  te_parse(self,ucs4)Widget self;uint32_t  ucs4;
#endif
#line 302 "TermEd.widget"
{
    switch( ucs4 ) {
    default: break;
    case 10: te_pos1(self); te_down(self); return True;
    case '\t': te_tab(self); return True;
    case 13: te_pos1(self); return True;
    }
    return False;
}
#line 312 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 312 "TermEd.widget"
static void te_right(Widget self)
#else
#line 312 "TermEd.widget"
static void te_right(self)Widget self;
#endif
#line 313 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.rsel.x < (((TermEdWidget)self)->termEd.gWidth-1) ) {
        ((TermEdWidget)self)->termEd.rsel.x++;
        return;
    }
    te_pos1(self);
    te_down(self);
}
#line 323 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 323 "TermEd.widget"
static void pix_del(Widget self)
#else
#line 323 "TermEd.widget"
static void pix_del(self)Widget self;
#endif
#line 324 "TermEd.widget"
{
   int x0,y0,x1,y1,w,h,x,y;
   x = ((TermEdWidget)self)->termEd.rsel.x; y=((TermEdWidget)self)->termEd.rsel.y;
   /*-----------------------*/
   /* destination           */
   x0 = x;
   y0 = y;
   /*-----------------------*/
   /* width, height         */
   w = ((TermEdWidget)self)->termEd.gWidth - (x+1);
   h = 1;
   /*-----------------------*/
   /* source                */
   x1 = x0+1;
   y1 = y0;
   /*-----------------------*/
   /* transformation        */
   w   *= ((TermEdWidget)self)->termEd.grid_pix_width;
   x0  *= ((TermEdWidget)self)->termEd.grid_pix_width;
   x1  *= ((TermEdWidget)self)->termEd.grid_pix_width;
   h   *= ((TermEdWidget)self)->termEd.grid_pix_height;
   y0  *= ((TermEdWidget)self)->termEd.grid_pix_height;
   y1  *= ((TermEdWidget)self)->termEd.grid_pix_height;

   XCopyArea(XtDisplay(self), XtWindow(self), XtWindow(self), DefaultGC(XtDisplay(self),0),
             x1,y1,w,h, /* source */
             x0,y0      /* destination */
             );
}
#line 354 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 354 "TermEd.widget"
static void pix_ins(Widget self)
#else
#line 354 "TermEd.widget"
static void pix_ins(self)Widget self;
#endif
#line 355 "TermEd.widget"
{
   int x0,y0,x1,y1,w,h,x,y;
   x = ((TermEdWidget)self)->termEd.rsel.x; y=((TermEdWidget)self)->termEd.rsel.y;
   /*-----------------------*/
   /* destination           */
   x0 = x+1;
   y0 = y;
   /*-----------------------*/
   /* width, height         */
   w = ((TermEdWidget)self)->termEd.gWidth - (x+1);
   h = 1;
   /*-----------------------*/
   /* source                */
   x1 = x;
   y1 = y;
   /*-----------------------*/
   /* transformation        */
   w   *= ((TermEdWidget)self)->termEd.grid_pix_width;
   x0  *= ((TermEdWidget)self)->termEd.grid_pix_width;
   x1  *= ((TermEdWidget)self)->termEd.grid_pix_width;
   h   *= ((TermEdWidget)self)->termEd.grid_pix_height;
   y0  *= ((TermEdWidget)self)->termEd.grid_pix_height;
   y1  *= ((TermEdWidget)self)->termEd.grid_pix_height;

   XCopyArea(XtDisplay(self), XtWindow(self), XtWindow(self), DefaultGC(XtDisplay(self),0),
             x1,y1,w,h, /* source */
             x0,y0      /* destination */
             );
}
#line 385 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 385 "TermEd.widget"
static void te_ins(Widget self)
#else
#line 385 "TermEd.widget"
static void te_ins(self)Widget self;
#endif
#line 386 "TermEd.widget"
{
   int i,x,y;
   x = ((TermEdWidget)self)->termEd.rsel.x; y=((TermEdWidget)self)->termEd.rsel.y;
   uint32_t *s = ((TermEdWidget)self)->termEd.scr+y* ((TermEdWidget)self)->termEd.gWidth;

   /* letztes zeichen der zeile mit <null> füllen */
   if( x == ((TermEdWidget)self)->termEd.gWidth -1 ) {
      s[x] = 0;
      return;
   }

   for(i=((TermEdWidget)self)->termEd.gWidth-2; i>=x ; i-- )
              s[i+1] = s[i];
   pix_ins(self);
   s[x] = 32;
}
#line 404 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 404 "TermEd.widget"
static void te_del(Widget self)
#else
#line 404 "TermEd.widget"
static void te_del(self)Widget self;
#endif
#line 405 "TermEd.widget"
{
   uint16_t i,x,y;
   x = ((TermEdWidget)self)->termEd.rsel.x; y=((TermEdWidget)self)->termEd.rsel.y;
   uint32_t *s = ((TermEdWidget)self)->termEd.scr+y* ((TermEdWidget)self)->termEd.gWidth;

   /* letztes zeichen der zeile mit <null> füllen */
   if( x == ((TermEdWidget)self)->termEd.gWidth -1 ) {
      s[x] = 0;
      return;
   }

   for(i=x+1; i< ((TermEdWidget)self)->termEd.gWidth; i++ )
              s[i-1] = s[i];
   pix_del(self);
}
#line 422 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 422 "TermEd.widget"
static void te_putc(Widget self,uint32_t  ucs4)
#else
#line 422 "TermEd.widget"
static void te_putc(self,ucs4)Widget self;uint32_t  ucs4;
#endif
#line 423 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.rsel.x >= ((TermEdWidget)self)->termEd.gWidth ) ((TermEdWidget)self)->termEd.rsel.x = ((TermEdWidget)self)->termEd.gWidth-1;
    if( ((TermEdWidget)self)->termEd.rsel.y >= ((TermEdWidget)self)->termEd.gHeight ) ((TermEdWidget)self)->termEd.rsel.y = ((TermEdWidget)self)->termEd.gHeight-1;
    if( te_parse(self,ucs4) ) return;
    putcharat(self, ((TermEdWidget)self)->termEd.rsel.x, ((TermEdWidget)self)->termEd.rsel.y,ucs4);
    drawcharat(self, ((TermEdWidget)self)->termEd.rsel.x, ((TermEdWidget)self)->termEd.rsel.y, 0,1 );
    ((TermEdWidget)self)->termEd.selection_visible = False;
    te_right(self);
}
#line 434 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 434 "TermEd.widget"
static void te_left(Widget self)
#else
#line 434 "TermEd.widget"
static void te_left(self)Widget self;
#endif
#line 435 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.rsel.x == 0 ) return;
    ((TermEdWidget)self)->termEd.rsel.x--;
}
#line 441 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 441 "TermEd.widget"
static void exec_line(Widget self)
#else
#line 441 "TermEd.widget"
static void exec_line(self)Widget self;
#endif
#line 442 "TermEd.widget"
{
    int i,len, space_left;
    unsigned char *dest;
    // char *string = malloc( ((TermEdWidget)self)->termEd.gWidth * 6 + 2 );
    char *string = (void*)((TermEdWidget)self)->termEd.cmd;
    uint32_t *s = ((TermEdWidget)self)->termEd.scr + ((TermEdWidget)self)->termEd.rsel.y * ((TermEdWidget)self)->termEd.gWidth;
    dest = (void*)string;
    space_left = ((TermEdWidget)self)->termEd.cmd_len;
    for( i=0; i< ((TermEdWidget)self)->termEd.gWidth; i++ )
        {
            if( space_left < 7 ) break;
            len = FcUcs4ToUtf8( *s++, dest );
            dest+=len;
            space_left -= len;
        }
    *dest = 0;
    printf("str: %s\n", string );

    /* check if there is a line number prefix */
    if(! prog_insert_line(self, string) ) return;

    if( strncmp( string, "list", 4 ) == 0 ) prog_list(self);
    else if( strncmp( string, "save", 4 ) == 0 ) prog_save(self);
    else if( strncmp( string, "load", 4 ) == 0 ) prog_load(self);
    else if( strncmp( string, "run", 3 ) == 0 ) prog_run(self);
    else if( strncmp( string, "parse", 5 ) == 0 ) prog_parse(self);
    else if( ((TermEdWidget)self)->termEd.child ) prog_interpret(self);
}
#line 471 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 471 "TermEd.widget"
static void prog_interpret(Widget self)
#else
#line 471 "TermEd.widget"
static void prog_interpret(self)Widget self;
#endif
#line 472 "TermEd.widget"
{
    char *s = (void*)((TermEdWidget)self)->termEd.cmd;
    while(*s && *s == '>' ) s++;
    dprintf( ((TermEdWidget)self)->termEd.child->fd[3], "%s\n", s );
}
#line 479 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 479 "TermEd.widget"
static void prog_child_read(Widget self,int * source,XtInputId * id)
#else
#line 479 "TermEd.widget"
static void prog_child_read(self,source,id)Widget self;int * source;XtInputId * id;
#endif
#line 480 "TermEd.widget"
{
    int ch;
    if( ! ((TermEdWidget)self)->termEd.child ) ERR("memory corruption");
    if( fork2_read(((TermEdWidget)self)->termEd.child) ) {
        prog_kill(self);
        return;
    }
    undraw_selection(self);
    while( (ch=mrb_get(((TermEdWidget)self)->termEd.child->buf)) >= 0 )
        te_putc( self, ch );
    selection_draw(self);
}
#line 493 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 493 "TermEd.widget"
static void prog_child_err_read(Widget self,int * source,XtInputId * id)
#else
#line 493 "TermEd.widget"
static void prog_child_err_read(self,source,id)Widget self;int * source;XtInputId * id;
#endif
#line 494 "TermEd.widget"
{
    int len, i;

    if( ! ((TermEdWidget)self)->termEd.child ) ERR("memory corruption");
    char buf[1024];
    len = read( *source, buf, sizeof(buf) );

    undraw_selection(self);
    for(i=0;i<len;i++)
        te_putc( self, buf[i] );
    selection_draw(self);
}
#line 508 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 508 "TermEd.widget"
static void prog_run(Widget self)
#else
#line 508 "TermEd.widget"
static void prog_run(self)Widget self;
#endif
#line 509 "TermEd.widget"
{
        if( ((TermEdWidget)self)->termEd.child ) prog_kill(self);
        ((TermEdWidget)self)->termEd.child = fork2_open( "lua5.3", "-i", NULL, "-e", "_PROMPT=''", NULL );
        ((TermEdWidget)self)->termEd.cid = XtAppAddInput( XtWidgetToApplicationContext(self),
                       ((TermEdWidget)self)->termEd.child->fd[0],
                       (XtPointer)XtInputReadMask,
                       (XtInputCallbackProc)prog_child_read,
                       self );

        ((TermEdWidget)self)->termEd.eid = XtAppAddInput( XtWidgetToApplicationContext(self),
                       ((TermEdWidget)self)->termEd.child->fd[4],
                       (XtPointer)XtInputReadMask,
                       (XtInputCallbackProc)prog_child_err_read,
                       self );



}
#line 529 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 529 "TermEd.widget"
static char * progm_alloc(Widget self,uint32_t  ln,char * s)
#else
#line 529 "TermEd.widget"
static char * progm_alloc(self,ln,s)Widget self;uint32_t  ln;char * s;
#endif
#line 530 "TermEd.widget"
{
        char *buf = malloc( 5 + strlen(s) );
        *(uint32_t *)buf = ln;
        while( isspace(*s) ) s++;
        strcpy( buf +4, s );
        return buf;
}
#line 538 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 538 "TermEd.widget"
static void progm_insert(Widget self,int  i,uint32_t  arg,char * s)
#else
#line 538 "TermEd.widget"
static void progm_insert(self,i,arg,s)Widget self;int  i;uint32_t  arg;char * s;
#endif
#line 539 "TermEd.widget"
{
        m_ins(((TermEdWidget)self)->termEd.progm,i, 1);
        STR(((TermEdWidget)self)->termEd.progm, i) = progm_alloc(self,arg,s);
}
#line 544 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 544 "TermEd.widget"
static void progm_overwrite(Widget self,int  i,uint32_t  arg,char * s)
#else
#line 544 "TermEd.widget"
static void progm_overwrite(self,i,arg,s)Widget self;int  i;uint32_t  arg;char * s;
#endif
#line 545 "TermEd.widget"
{
        free( STR(((TermEdWidget)self)->termEd.progm,i));
        STR(((TermEdWidget)self)->termEd.progm, i) = progm_alloc(self,arg,s);
}
#line 550 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 550 "TermEd.widget"
static void progm_append(Widget self,uint32_t  arg,char * s)
#else
#line 550 "TermEd.widget"
static void progm_append(self,arg,s)Widget self;uint32_t  arg;char * s;
#endif
#line 551 "TermEd.widget"
{
        char *buf = progm_alloc(self,arg,s);
        m_put( ((TermEdWidget)self)->termEd.progm, &buf );
}
#line 563 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 563 "TermEd.widget"
static int  progm_find(Widget self,uint32_t  num,int * pos)
#else
#line 563 "TermEd.widget"
static int  progm_find(self,num,pos)Widget self;uint32_t  num;int * pos;
#endif
#line 564 "TermEd.widget"
{
        int i;
        uint32_t n;
        char *s;

        for(i=0;i<m_len(((TermEdWidget)self)->termEd.progm);i++) {
          s= STR(((TermEdWidget)self)->termEd.progm,i);
          n = *(uint32_t *) s;
          if( n == num ) { *pos=i; return 0; }
          else if( n > num ) { *pos=i; return 1; };
        }
        *pos = i;
        return -1;
}
#line 580 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 580 "TermEd.widget"
static void progm_put(Widget self,uint32_t  arg,char * ln)
#else
#line 580 "TermEd.widget"
static void progm_put(self,arg,ln)Widget self;uint32_t  arg;char * ln;
#endif
#line 581 "TermEd.widget"
{
        int i;
        uint32_t n;
        char *s;

        for(i=0;i<m_len(((TermEdWidget)self)->termEd.progm);i++) {
          s= STR(((TermEdWidget)self)->termEd.progm,i);
          n = *(uint32_t *) s;
          if( n == arg ) { progm_overwrite( self, i, arg, ln ); return; }
          else if( n > arg ) { progm_insert(self, i, arg, ln ); return; }
        }
        progm_append(self,arg, ln );
}
#line 596 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 596 "TermEd.widget"
static Bool  prog_insert_line(Widget self,char * buf)
#else
#line 596 "TermEd.widget"
static Bool  prog_insert_line(self,buf)Widget self;char * buf;
#endif
#line 597 "TermEd.widget"
{
        char *s = (void*) buf;
        char *endp;
        int arg;

        arg = strtol( s,&endp,10);
        if( s == endp ) { return 1; }

        progm_put(self, arg, endp );
        return 0;
}
#line 614 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 614 "TermEd.widget"
static void prog_error(Widget self,char * s)
#else
#line 614 "TermEd.widget"
static void prog_error(self,s)Widget self;char * s;
#endif
#line 615 "TermEd.widget"
{
        te_down(self);
        te_pos1(self);
        te_write(self,s);
        te_down(self);
        te_pos1(self);
}
#line 624 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 624 "TermEd.widget"
static void prog_load(Widget self)
#else
#line 624 "TermEd.widget"
static void prog_load(self)Widget self;
#endif
#line 625 "TermEd.widget"
{
        char *s = (void*)((TermEdWidget)self)->termEd.cmd+5;
        int p = m_create(20,1);

        while( *s && ! isspace(*s) )
               m_putc( p, *s++ );
        m_putc(p,0);

        FILE *fp = fopen( m_buf(p), "r" );
        if( !fp ) { prog_error( self, "file read error" ); goto leave; }
        m_clear(p);


        while( m_fscan2( p, '\n', fp ) == '\n' ) {
                prog_insert_line(self,m_buf(p));
                m_clear(p);
        }

        fclose(fp);
        leave: m_free(p);

}
#line 651 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 651 "TermEd.widget"
static void prog_save(Widget self)
#else
#line 651 "TermEd.widget"
static void prog_save(self)Widget self;
#endif
#line 652 "TermEd.widget"
{
        /* get two integer args */
        char *s = (void*)((TermEdWidget)self)->termEd.cmd+5;
        int p = m_create(20,1);
        int i;

        while( *s && ! isspace(*s) )
               m_putc( p, *s++ );
        m_putc(p,0);

        FILE *fp = fopen( m_buf(p), "w" );
        if( !fp ) { prog_error( self, "file write error" ); goto leave; }

        for(i=0;i<m_len(((TermEdWidget)self)->termEd.progm);i++)
        {
                s = STR(((TermEdWidget)self)->termEd.progm,i);
                uint32_t n = *(uint32_t *)s; s+=4;
                fprintf(fp,"%u %s\n", n,s );
        }

        fclose(fp);
        leave: m_free(p);
}
#line 676 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 676 "TermEd.widget"
static void prog_parse(Widget self)
#else
#line 676 "TermEd.widget"
static void prog_parse(self)Widget self;
#endif
#line 677 "TermEd.widget"
{

    if(! ((TermEdWidget)self)->termEd.child ) {
        prog_error(self,"starting subshell with 'run'");
        prog_run(self);
    }

    int from,len;

    from = 0;
    len  = m_len(((TermEdWidget)self)->termEd.progm);

    /* get two integer args */
    char *s = (void*)((TermEdWidget)self)->termEd.cmd+6;
    char *endp;
    from = strtol( s,&endp,10);
    if( s == endp ) { from=0; goto cont; }

 cont:
    prog_do_parse(self, from, len);
}
#line 699 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 699 "TermEd.widget"
static void prog_list(Widget self)
#else
#line 699 "TermEd.widget"
static void prog_list(self)Widget self;
#endif
#line 700 "TermEd.widget"
{
        int arg,from,len;

        from = 0;
        len  = 10;

        /* get two integer args */
        char *s = (void*)((TermEdWidget)self)->termEd.cmd+5;
        char *endp;
        arg = strtol( s,&endp,10);
        if( s == endp ) { arg=0; goto cont; }

        s=endp; if( *s == ',' ) s++;
        from = arg;
        arg = strtol( s,&endp,10);
        if( s == endp ) { arg=0; goto cont; }
        len = arg;

        cont:
        te_pos1(self); te_down(self);
        prog_do_list(self, from, len);
}
#line 724 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 724 "TermEd.widget"
static void te_write(Widget self,char * str)
#else
#line 724 "TermEd.widget"
static void te_write(self,str)Widget self;char * str;
#endif
#line 725 "TermEd.widget"
{
    int len,l;
    unsigned char *string = (void*) str;
    uint32_t ucs4;
    len = strlen( (char*)string);

    while(1) {
        l = FcUtf8ToUcs4 (string, &ucs4, len);
        if( l<= 0 || len <=0 ) return;
        te_putc(self,ucs4);
        string += l;
        len -= l;
    }
}
#line 740 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 740 "TermEd.widget"
static void te_writeln(Widget self,char * s)
#else
#line 740 "TermEd.widget"
static void te_writeln(self,s)Widget self;char * s;
#endif
#line 741 "TermEd.widget"
{
        te_write(self,s);
        te_pos1(self);
        te_down(self);
}
#line 748 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 748 "TermEd.widget"
static void prog_print(Widget self,int  i)
#else
#line 748 "TermEd.widget"
static void prog_print(self,i)Widget self;int  i;
#endif
#line 749 "TermEd.widget"
{
        char buf[20];


        char *s = STR(((TermEdWidget)self)->termEd.progm,i);
        uint32_t num = *(uint32_t *)s;
        s+=4;

        sprintf(buf,"%d", num);
        te_write(self,buf);
        te_putc(self,32);
        te_write(self,s);
}
#line 763 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 763 "TermEd.widget"
static void prog_do_list(Widget self,int  from,int  len)
#else
#line 763 "TermEd.widget"
static void prog_do_list(self,from,len)Widget self;int  from;int  len;
#endif
#line 764 "TermEd.widget"
{
        int i;
        int line;

        int match  = progm_find( self, from, &line );
        if( match < 0 ) return;

        for(i=line;i<line+len;i++) {
                if( i >= m_len(((TermEdWidget)self)->termEd.progm) ) break;
                prog_print(self,i);
                te_pos1(self);
                te_down(self);
        }
}
#line 779 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 779 "TermEd.widget"
static void prog_do_parse(Widget self,int  from,int  len)
#else
#line 779 "TermEd.widget"
static void prog_do_parse(self,from,len)Widget self;int  from;int  len;
#endif
#line 780 "TermEd.widget"
{
        int i;
        int line;

        int match  = progm_find( self, from, &line );
        if( match < 0 ) return;

        for(i=line;i<line+len;i++) {
                if( i >= m_len(((TermEdWidget)self)->termEd.progm) ) break;
                char *s = STR(((TermEdWidget)self)->termEd.progm,i);
                s+=4;
                dprintf( ((TermEdWidget)self)->termEd.child->fd[3], "%s\n", s );
        }
}
#line 797 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 797 "TermEd.widget"
static void prog_kill(Widget self)
#else
#line 797 "TermEd.widget"
static void prog_kill(self)Widget self;
#endif
#line 798 "TermEd.widget"
{
        if( ((TermEdWidget)self)->termEd.child ) {
            fork2_close( ((TermEdWidget)self)->termEd.child );
            ((TermEdWidget)self)->termEd.child=0;
        }
        if( ((TermEdWidget)self)->termEd.cid ) { XtRemoveInput(((TermEdWidget)self)->termEd.cid); ((TermEdWidget)self)->termEd.cid=0; }
        if( ((TermEdWidget)self)->termEd.eid ) { XtRemoveInput(((TermEdWidget)self)->termEd.eid); ((TermEdWidget)self)->termEd.eid=0; }
}
#line 807 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 807 "TermEd.widget"
static void do_resize(Widget self)
#else
#line 807 "TermEd.widget"
static void do_resize(self)Widget self;
#endif
#line 808 "TermEd.widget"
{
    ((TermEdWidget)self)->termEd.scr=realloc(((TermEdWidget)self)->termEd.scr, ((TermEdWidget)self)->termEd.gWidth * ((TermEdWidget)self)->termEd.gHeight * 4 );
    memset(((TermEdWidget)self)->termEd.scr,0,((TermEdWidget)self)->termEd.gWidth * ((TermEdWidget)self)->termEd.gHeight * 4 );
    ((TermEdWidget)self)->termEd.cmd=realloc(((TermEdWidget)self)->termEd.cmd,((TermEdWidget)self)->termEd.cmd_len = (((TermEdWidget)self)->termEd.gWidth+2) * 6 );
    printf("WxH=%dx%d\n",((TermEdWidget)self)->termEd.gWidth, ((TermEdWidget)self)->termEd.gHeight );
    printf("pix WxH=%dx%d\n",((TermEdWidget)self)->termEd.grid_pix_width, ((TermEdWidget)self)->termEd.grid_pix_height );
    printf("w WxH=%dx%d\n",((TermEdWidget)self)->core.width, ((TermEdWidget)self)->core.height );
}

static XtResource resources[] = {
#line 4 "TermEd.widget"
{XtNgWidth,XtCGWidth,XtRInt,sizeof(((TermEdRec*)NULL)->termEd.gWidth),XtOffsetOf(TermEdRec,termEd.gWidth),XtRImmediate,(XtPointer)40 },
#line 5 "TermEd.widget"
{XtNgHeight,XtCGHeight,XtRInt,sizeof(((TermEdRec*)NULL)->termEd.gHeight),XtOffsetOf(TermEdRec,termEd.gHeight),XtRImmediate,(XtPointer)25 },
#line 6 "TermEd.widget"
{XtNsize,XtCSize,XtRInt,sizeof(((TermEdRec*)NULL)->termEd.size),XtOffsetOf(TermEdRec,termEd.size),XtRImmediate,(XtPointer)8 },
#line 7 "TermEd.widget"
{XtNselTime,XtCSelTime,XtRInt,sizeof(((TermEdRec*)NULL)->termEd.selTime),XtOffsetOf(TermEdRec,termEd.selTime),XtRImmediate,(XtPointer)400 },
#line 8 "TermEd.widget"
{XtNtext,XtCText,XtRString,sizeof(((TermEdRec*)NULL)->termEd.text),XtOffsetOf(TermEdRec,termEd.text),XtRString,(XtPointer)"Hello World\nHow are you?"},
#line 9 "TermEd.widget"
{XtNfg,XtCFg,XtRXftColor,sizeof(((TermEdRec*)NULL)->termEd.fg),XtOffsetOf(TermEdRec,termEd.fg),XtRString,(XtPointer)"White"},
#line 10 "TermEd.widget"
{XtNbg,XtCBg,XtRXftColor,sizeof(((TermEdRec*)NULL)->termEd.bg),XtOffsetOf(TermEdRec,termEd.bg),XtRString,(XtPointer)"Darkgreen"},
#line 11 "TermEd.widget"
{XtNcbg,XtCCbg,XtRXftColor,sizeof(((TermEdRec*)NULL)->termEd.cbg),XtOffsetOf(TermEdRec,termEd.cbg),XtRString,(XtPointer)"Red"},
#line 12 "TermEd.widget"
{XtNcfg,XtCCfg,XtRXftColor,sizeof(((TermEdRec*)NULL)->termEd.cfg),XtOffsetOf(TermEdRec,termEd.cfg),XtRString,(XtPointer)"Green"},
};

TermEdClassRec termEdClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &coreClassRec,
/* class_name   	*/  "TermEd",
/* widget_size  	*/  sizeof(TermEdRec),
/* class_initialize 	*/  class_initialize,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  actionsList,
/* num_actions  	*/  9,
/* resources    	*/  resources,
/* num_resources 	*/  9,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  FALSE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  destroy,
/* resize       	*/  resize,
/* expose       	*/  expose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  defaultTranslations,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* TermEd_class part */
 /* dummy */  0
},
};
WidgetClass termEdWidgetClass = (WidgetClass) &termEdClassRec;
/*ARGSUSED*/
#line 832 "TermEd.widget"
static void kill_child(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    undraw_selection(self);
    te_writeln(self, "kill");
    prog_kill(self);

    selection_draw(self);
}

/*ARGSUSED*/
#line 841 "TermEd.widget"
static void key_del(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    undraw_selection(self);
    te_del(self);
    selection_draw(self);
}

/*ARGSUSED*/
#line 848 "TermEd.widget"
static void key_backspace(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    undraw_selection(self);
    te_left(self);
    te_del(self);
    selection_draw(self);
}

/*ARGSUSED*/
#line 857 "TermEd.widget"
static void key_return(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    undraw_selection(self);
    exec_line(self);
    te_pos1(self);
    te_down(self);
    selection_draw(self);
}

/*ARGSUSED*/
#line 867 "TermEd.widget"
static void insert_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    int len;
    unsigned char buf[32];
    KeySym key_sim;
    uint32_t ucs4;

    len = _XawLookupString(self,(XKeyEvent *) event, (char*)buf,sizeof buf, &key_sim );
    if (len <= 0) return;
    FcUtf8ToUcs4 (buf, &ucs4, len);
    undraw_selection(self);
    te_ins(self);
    te_putc(self,ucs4);
    selection_draw(self);
}

/*ARGSUSED*/
#line 885 "TermEd.widget"
static void prev_line(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    if( ((TermEdWidget)self)->termEd.rsel.y == 0 ) return;
    ((TermEdWidget)self)->termEd.rsel.y--;
    selection_draw(self);
}

/*ARGSUSED*/
#line 892 "TermEd.widget"
static void next_line(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    undraw_selection(self);
    te_down(self);
    // if( ((TermEdWidget)self)->termEd.rsel.y < (((TermEdWidget)self)->termEd.gHeight-1) )
    // ((TermEdWidget)self)->termEd.rsel.y++;
    selection_draw(self);
}

/*ARGSUSED*/
#line 901 "TermEd.widget"
static void backward_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    if( ((TermEdWidget)self)->termEd.rsel.x == 0 ) return;
    ((TermEdWidget)self)->termEd.rsel.x--;
    selection_draw(self);
}

/*ARGSUSED*/
#line 908 "TermEd.widget"
static void forward_char(self,event,params,num_params)Widget self;XEvent*event;String*params;Cardinal*num_params;
{
    if( ((TermEdWidget)self)->termEd.rsel.x < (((TermEdWidget)self)->termEd.gWidth-1) )
        ((TermEdWidget)self)->termEd.rsel.x ++;
    selection_draw(self);
}

static void _resolve_inheritance(class)
WidgetClass class;
{
  TermEdWidgetClass c __attribute__((unused)) = (TermEdWidgetClass) class;
  TermEdWidgetClass super __attribute__((unused));
  if (class == termEdWidgetClass) return;
  super = (TermEdWidgetClass)class->core_class.superclass;
}
#line 35 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 35 "TermEd.widget"
static void class_initialize(void)
#else
#line 35 "TermEd.widget"
static void class_initialize()
#endif
#line 36 "TermEd.widget"
{ converters_xft_init(); }
#line 37 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 37 "TermEd.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 37 "TermEd.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 38 "TermEd.widget"
{
    FcChar32 bat = 0x42;
    XGlyphInfo extents;
    Display *dpy = XtDisplay(self);
    font_load(self,((TermEdWidget)self)->termEd.size);
    XftTextExtents32(dpy, ((TermEdWidget)self)->termEd.xftFont, &bat, 1, &extents);
    ((TermEdWidget)self)->core.height = (((TermEdWidget)self)->termEd.grid_pix_height = ((TermEdWidget)self)->termEd.xftFont->ascent + ((TermEdWidget)self)->termEd.xftFont->descent) * ((TermEdWidget)self)->termEd.gHeight;
    ((TermEdWidget)self)->core.width  = (((TermEdWidget)self)->termEd.grid_pix_width = extents.width) * ((TermEdWidget)self)->termEd.gWidth;
    ((TermEdWidget)self)->termEd.draw=0;
    ((TermEdWidget)self)->termEd.cmd=0;
    ((TermEdWidget)self)->termEd.scr=0;
    ((TermEdWidget)self)->termEd.child=0;
    ((TermEdWidget)self)->termEd.col[0] = & ((TermEdWidget)self)->termEd.fg;
    ((TermEdWidget)self)->termEd.col[1] = & ((TermEdWidget)self)->termEd.bg;
    ((TermEdWidget)self)->termEd.col[2] = & ((TermEdWidget)self)->termEd.cfg;
    ((TermEdWidget)self)->termEd.col[3] = & ((TermEdWidget)self)->termEd.cbg;
    ((TermEdWidget)self)->termEd.selection_visible = False;
    ((TermEdWidget)self)->termEd.timerid = 0;
    ((TermEdWidget)self)->termEd.gc_copy =  XtGetGC(self, 0,0 );
    ((TermEdWidget)self)->termEd.progm = m_create(100,sizeof(char*));
    do_resize(self);

}
#line 62 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 62 "TermEd.widget"
static void destroy(Widget self)
#else
#line 62 "TermEd.widget"
static void destroy(self)Widget self;
#endif
#line 63 "TermEd.widget"
{
    if( ((TermEdWidget)self)->termEd.draw) XftDrawDestroy( ((TermEdWidget)self)->termEd.draw );
    ((TermEdWidget)self)->termEd.draw=0;
    font_free(self);
    if( ((TermEdWidget)self)->termEd.scr ) { free(((TermEdWidget)self)->termEd.scr); ((TermEdWidget)self)->termEd.scr=0; }
    if( ((TermEdWidget)self)->termEd.cmd ) { free(((TermEdWidget)self)->termEd.cmd); ((TermEdWidget)self)->termEd.cmd=0; }
    if( ((TermEdWidget)self)->termEd.progm ) { m_free_strings( ((TermEdWidget)self)->termEd.progm, 0); ((TermEdWidget)self)->termEd.progm=0; }
    if( ((TermEdWidget)self)->termEd.child ) prog_kill(self);

}
#line 74 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 74 "TermEd.widget"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 74 "TermEd.widget"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 75 "TermEd.widget"
{
    if( ((TermEdWidget)old)->termEd.size != ((TermEdWidget)self)->termEd.size ) {
        font_free(self);
        font_load(self,((TermEdWidget)self)->termEd.size);
        ((TermEdWidgetClass)self->core.widget_class)->core_class.resize( self );
    }
    return True; /* call expose */
}
#line 84 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 84 "TermEd.widget"
static void resize(Widget self)
#else
#line 84 "TermEd.widget"
static void resize(self)Widget self;
#endif
#line 85 "TermEd.widget"
{
    ((TermEdWidget)self)->termEd.gWidth  = ((TermEdWidget)self)->core.width / ((TermEdWidget)self)->termEd.grid_pix_width;
    ((TermEdWidget)self)->termEd.gHeight = ((TermEdWidget)self)->core.height / ((TermEdWidget)self)->termEd.grid_pix_height;
    do_resize(self);
}
#line 91 "TermEd.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 91 "TermEd.widget"
static void expose(Widget self,XEvent * event,Region  region)
#else
#line 91 "TermEd.widget"
static void expose(self,event,region)Widget self;XEvent * event;Region  region;
#endif
#line 92 "TermEd.widget"
{
    Display *dpy = XtDisplay(self);
    if(!((TermEdWidget)self)->termEd.draw )
        ((TermEdWidget)self)->termEd.draw = XftDrawCreate(dpy, XtWindow(self),
                              DefaultVisual(dpy, DefaultScreen(dpy)), None);
    test_convert(self);
    full_draw(self);
    selection_draw(self);
    /*   FcChar32 bat = 0xf240 + $status;
        XftDrawString32($draw, $col[$status],$xftFont,0,$xftFont->ascent,&bat,1);
    */
    printf("w WxH=%dx%d\n",((TermEdWidget)self)->core.width, ((TermEdWidget)self)->core.height );
}
