/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 248 "../wb/Wlabel.widget"
#include <X11/Xft/Xft.h>
#line 249 "../wb/Wlabel.widget"
#include "converters-xft.h"
#line 250 "../wb/Wlabel.widget"
#include <X11/Xmu/Converters.h>
#line 251 "../wb/Wlabel.widget"
#include "mls.h"
#include <xtcw/WlabelP.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 28 "../wb/Wlabel.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 57 "../wb/Wlabel.widget"
static void realize(
#if NeedFunctionPrototypes
Widget,XtValueMask *,XSetWindowAttributes *
#endif
);
#line 64 "../wb/Wlabel.widget"
static void resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 72 "../wb/Wlabel.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 83 "../wb/Wlabel.widget"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 113 "../wb/Wlabel.widget"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);
#line 120 "../wb/Wlabel.widget"
static int  exec_command(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 125 "../wb/Wlabel.widget"
static Bool  cache_hit(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 135 "../wb/Wlabel.widget"
static void reshape_widget(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 146 "../wb/Wlabel.widget"
static void alloc_pixmap(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 161 "../wb/Wlabel.widget"
static void invalidate_cache(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 176 "../wb/Wlabel.widget"
static void update_cache(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 210 "../wb/Wlabel.widget"
static void redraw(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 228 "../wb/Wlabel.widget"
static void default_label_draw(
#if NeedFunctionPrototypes
Widget,void *,void *
#endif
);
#line 135 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 135 "../wb/Wlabel.widget"
static void reshape_widget(Widget self)
#else
#line 135 "../wb/Wlabel.widget"
static void reshape_widget(self)Widget self;
#endif
#line 136 "../wb/Wlabel.widget"
{
	int w;
	if( ((WlabelWidget)self)->wlabel.cornerRoundPercent >0 && ((WlabelWidget)self)->wlabel.cornerRoundPercent < 100 ) {
	    w = Min(((WlabelWidget)self)->core.height,((WlabelWidget)self)->core.width);
	    w = w * ((WlabelWidget)self)->wlabel.cornerRoundPercent / 100;
	    XmuReshapeWidget( self, XmuShapeRoundedRectangle, w, w );
	}
}
#line 146 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 146 "../wb/Wlabel.widget"
static void alloc_pixmap(Widget self)
#else
#line 146 "../wb/Wlabel.widget"
static void alloc_pixmap(self)Widget self;
#endif
#line 147 "../wb/Wlabel.widget"
{
  TRACE(1,"%s", ((WlabelWidget)self)->core.name );
    Display *dpy = XtDisplay(self);
    ((WlabelWidget)self)->wlabel.pixmap = XCreatePixmap(dpy, XtWindow(self), ((WlabelWidget)self)->core.width, ((WlabelWidget)self)->core.height,
                            DefaultDepth(dpy, DefaultScreen(dpy)));
    if( ((WlabelWidget)self)->wlabel.draw ) {
        XftDrawChange(((WlabelWidget)self)->wlabel.draw, ((WlabelWidget)self)->wlabel.pixmap );
    }
    else {
        ((WlabelWidget)self)->wlabel.draw = XftDrawCreate(dpy, ((WlabelWidget)self)->wlabel.pixmap,
                       DefaultVisual(dpy, DefaultScreen(dpy)), None);
    }
}
#line 161 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 161 "../wb/Wlabel.widget"
static void invalidate_cache(Widget self)
#else
#line 161 "../wb/Wlabel.widget"
static void invalidate_cache(self)Widget self;
#endif
#line 162 "../wb/Wlabel.widget"
{
    if( ((WlabelWidget)self)->wlabel.label_cache ) {
        free(((WlabelWidget)self)->wlabel.label_cache);
        ((WlabelWidget)self)->wlabel.label_cache=0;
    }

    if( ((WlabelWidget)self)->wlabel.pixmap ) {
        XFreePixmap( XtDisplay(self), ((WlabelWidget)self)->wlabel.pixmap );
        ((WlabelWidget)self)->wlabel.pixmap=0;
    }
}
#line 176 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 176 "../wb/Wlabel.widget"
static void update_cache(Widget self)
#else
#line 176 "../wb/Wlabel.widget"
static void update_cache(self)Widget self;
#endif
#line 177 "../wb/Wlabel.widget"
{
    if( ((WlabelWidget)self)->wlabel.pixmap == 0 ) alloc_pixmap(self);
    char *s = ((WlabelWidget)self)->wlabel.label;
    if( ((WlabelWidget)self)->wlabel.label_cache ) free(((WlabelWidget)self)->wlabel.label_cache);
    ((WlabelWidget)self)->wlabel.label_cache = strdup(((WlabelWidget)self)->wlabel.label);
    ((WlabelWidget)self)->wlabel.state_cache = ((WlabelWidget)self)->wheel.state;

    /* clear background */
    XFillRectangle(XtDisplay(self),((WlabelWidget)self)->wlabel.pixmap, ((WlabelWidget)self)->wheel.gc[((WlabelWidget)self)->wheel.state], 0,0,((WlabelWidget)self)->core.width,((WlabelWidget)self)->core.height );


    if( ((WlabelWidget)self)->wlabel.draw_override ) {
        ((WlabelWidget)self)->wlabel.draw_override( self, ((WlabelWidget)self)->wlabel.pixmap, ((WlabelWidget)self)->wlabel.draw );
        return;
    }

    /* draw string centered */
    TRACE(1,"draw string");
    int w,h;
    xft_calc_string_size(self,((WlabelWidget)self)->wheel.xftFont, s, &w, &h );
    int x,y;
    x = (((WlabelWidget)self)->core.width - w) / 2;
    if( x < 0 ) x=0;
    y = (((WlabelWidget)self)->core.height - h) / 2;
    if( y < 0 ) y=0;
    TRACE(1,"%s draw string: %s (%dx%d)",((WlabelWidget)self)->core.name, s,x,y );
    XftDrawStringUtf8(((WlabelWidget)self)->wlabel.draw, ((WlabelWidget)self)->wheel.xft_col + ((WlabelWidget)self)->wheel.state, ((WlabelWidget)self)->wheel.xftFont,
    			     x,y+((WlabelWidget)self)->wheel.xftFont->ascent, (FcChar8*)s, strlen(s) );
}
#line 210 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 210 "../wb/Wlabel.widget"
static void redraw(Widget self)
#else
#line 210 "../wb/Wlabel.widget"
static void redraw(self)Widget self;
#endif
#line 211 "../wb/Wlabel.widget"
{
    if( !XtIsRealized(self)) return;
    TRACE(1,"%s dirty=%d", ((WlabelWidget)self)->core.name, ((WlabelWidget)self)->wlabel.dirty );
    int called_by_set_values = ((WlabelWidget)self)->wlabel.dirty;
    ((WlabelWidget)self)->wlabel.dirty = 0;
    Bool eq = ((WlabelWidgetClass)self->core.widget_class)->wlabel_class.cache_hit(self);

    if( eq && called_by_set_values ) return;
    TRACE(1,"%s force update", ((WlabelWidget)self)->core.name );
    if( !eq ) update_cache(self);
    if( !((WlabelWidget)self)->wlabel.pixmap ) return; /* should never happen */
    TRACE(1,"%s draw pixmap: cache=%s", ((WlabelWidget)self)->core.name, ((WlabelWidget)self)->wlabel.label_cache );
    XCopyArea(XtDisplay(self),((WlabelWidget)self)->wlabel.pixmap, XtWindow(self), ((WlabelWidget)self)->wlabel.gc_copy,
              0,0, ((WlabelWidget)self)->core.width, ((WlabelWidget)self)->core.height, /* source pixmap */
              0,0 ); /* target window x,y */
}
#line 228 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 228 "../wb/Wlabel.widget"
static void default_label_draw(Widget self,void * a,void * b)
#else
#line 228 "../wb/Wlabel.widget"
static void default_label_draw(self,a,b)Widget self;void * a;void * b;
#endif
#line 229 "../wb/Wlabel.widget"
{
  int x,y;
  XRectangle rect;
  char *s = ((WlabelWidget)self)->wlabel.label;
  Display *dpy = XtDisplay(self);
  TRACE(1,"%s", ((WlabelWidget)self)->core.name );
  XFillRectangle(dpy,XtWindow(self) , ((WlabelWidget)self)->wheel.gc[((WlabelWidget)self)->wheel.state], 0,0,((WlabelWidget)self)->core.width,((WlabelWidget)self)->core.height );
  if( s && *s ) {
    y = (((WlabelWidget)self)->core.height - ((WlabelWidget)self)->wheel.xftFont->height)/2;
    x = calc_percent( ((WlabelWidget)self)->core.width, ((WlabelWidget)self)->wlabel.leftOffsetPercent ); x = (x+1) / 2;
    rect.x = 0; rect.y=0; rect.width=((WlabelWidget)self)->core.width; rect.height=((WlabelWidget)self)->core.height;
    XftDrawSetClipRectangles( ((WlabelWidget)self)->wlabel.draw,0,0,&rect, 1);
    XftDrawStringUtf8(((WlabelWidget)self)->wlabel.draw, ((WlabelWidget)self)->wheel.xft_col + ((WlabelWidget)self)->wheel.state, ((WlabelWidget)self)->wheel.xftFont,
    			     x,y+((WlabelWidget)self)->wheel.xftFont->ascent, (FcChar8*)s, strlen(s) );
    XftDrawSetClip(((WlabelWidget)self)->wlabel.draw,0);
  }
}

static XtResource resources[] = {
#line 11 "../wb/Wlabel.widget"
{XtNlabel,XtCLabel,XtRString,sizeof(((WlabelRec*)NULL)->wlabel.label),XtOffsetOf(WlabelRec,wlabel.label),XtRString,(XtPointer)NULL },
#line 12 "../wb/Wlabel.widget"
{XtNcornerRoundPercent,XtCCornerRoundPercent,XtRInt,sizeof(((WlabelRec*)NULL)->wlabel.cornerRoundPercent),XtOffsetOf(WlabelRec,wlabel.cornerRoundPercent),XtRImmediate,(XtPointer)0 },
#line 13 "../wb/Wlabel.widget"
{XtNdraw_override,XtCDraw_override,XtRXTCallbackProc,sizeof(((WlabelRec*)NULL)->wlabel.draw_override),XtOffsetOf(WlabelRec,wlabel.draw_override),XtRImmediate,(XtPointer)NULL },
#line 14 "../wb/Wlabel.widget"
{XtNheightIncreasePercent,XtCHeightIncreasePercent,XtRInt,sizeof(((WlabelRec*)NULL)->wlabel.heightIncreasePercent),XtOffsetOf(WlabelRec,wlabel.heightIncreasePercent),XtRImmediate,(XtPointer)0 },
#line 15 "../wb/Wlabel.widget"
{XtNleftOffsetPercent,XtCLeftOffsetPercent,XtRInt,sizeof(((WlabelRec*)NULL)->wlabel.leftOffsetPercent),XtOffsetOf(WlabelRec,wlabel.leftOffsetPercent),XtRImmediate,(XtPointer)5 },
#line 16 "../wb/Wlabel.widget"
{XtNupdate,XtCUpdate,XtRInt,sizeof(((WlabelRec*)NULL)->wlabel.update),XtOffsetOf(WlabelRec,wlabel.update),XtRImmediate,(XtPointer)0 },
};

WlabelClassRec wlabelClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &wheelClassRec,
/* class_name   	*/  "Wlabel",
/* widget_size  	*/  sizeof(WlabelRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  realize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  6,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  TRUE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  destroy,
/* resize       	*/  resize,
/* expose       	*/  expose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  NULL,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* Wheel_class part */
exec_command,
XtInherit_sig_recv,
},
{ /* Wlabel_class part */
cache_hit,
},
};
WidgetClass wlabelWidgetClass = (WidgetClass) &wlabelClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  WlabelWidgetClass c __attribute__((unused)) = (WlabelWidgetClass) class;
  WlabelWidgetClass super __attribute__((unused));
  if (class == wlabelWidgetClass) return;
  super = (WlabelWidgetClass)class->core_class.superclass;
  if (c->wlabel_class.cache_hit == XtInherit_cache_hit)
    c->wlabel_class.cache_hit = super->wlabel_class.cache_hit;
}
#line 28 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 28 "../wb/Wlabel.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 28 "../wb/Wlabel.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 29 "../wb/Wlabel.widget"
{
  XGlyphInfo extents;
  Display *dpy = XtDisplay(self);
  char *s = ((WlabelWidget)self)->wlabel.label;

  if( ! s || ! *s )
    s=((WlabelWidget)self)->core.name;

  ((WlabelWidget)self)->wlabel.label = XtNewString(s);

  if( ((WlabelWidget)self)->core.width == 0 ) {
    XftTextExtentsUtf8(dpy, ((WlabelWidget)self)->wheel.xftFont, (FcChar8*)  s,
		       strlen( s ), &extents);

    ((WlabelWidget)self)->core.width = increase_by_percent( extents.xOff, ((WlabelWidget)self)->wlabel.leftOffsetPercent );
  }

  if( ((WlabelWidget)self)->core.height == 0 )
    ((WlabelWidget)self)->core.height = increase_by_percent( ((WlabelWidget)self)->wheel.xftFont->height, ((WlabelWidget)self)->wlabel.heightIncreasePercent);

  ((WlabelWidget)self)->wlabel.dirty=0;
  ((WlabelWidget)self)->wlabel.label_cache = 0;
  ((WlabelWidget)self)->wlabel.pixmap = 0;
  ((WlabelWidget)self)->wlabel.draw = 0;
  ((WlabelWidget)self)->wlabel.gc_copy =  XtGetGC(self, 0,0 );

}
#line 57 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 57 "../wb/Wlabel.widget"
static void realize(Widget self,XtValueMask * mask,XSetWindowAttributes * attributes)
#else
#line 57 "../wb/Wlabel.widget"
static void realize(self,mask,attributes)Widget self;XtValueMask * mask;XSetWindowAttributes * attributes;
#endif
#line 58 "../wb/Wlabel.widget"
{
	XtCreateWindow(self, (unsigned int) InputOutput,
        		  (Visual *) CopyFromParent, *mask, attributes);
  	reshape_widget(self);
}
#line 64 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 64 "../wb/Wlabel.widget"
static void resize(Widget self)
#else
#line 64 "../wb/Wlabel.widget"
static void resize(self)Widget self;
#endif
#line 65 "../wb/Wlabel.widget"
{
    TRACE(3, "%s: resize: %dx%d", ((WlabelWidget)self)->core.name, ((WlabelWidget)self)->core.width, ((WlabelWidget)self)->core.height );
    if (XtIsRealized(self)) reshape_widget(self);
    invalidate_cache(self);
}
#line 72 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 72 "../wb/Wlabel.widget"
static void destroy(Widget self)
#else
#line 72 "../wb/Wlabel.widget"
static void destroy(self)Widget self;
#endif
#line 73 "../wb/Wlabel.widget"
{
  if( ((WlabelWidget)self)->wlabel.draw) XftDrawDestroy( ((WlabelWidget)self)->wlabel.draw );
  XtFree(((WlabelWidget)self)->wlabel.label);
  XtFree(((WlabelWidget)self)->wlabel.label_cache);
  XtReleaseGC(self,((WlabelWidget)self)->wlabel.gc_copy);
  XFreePixmap(XtDisplay(self),((WlabelWidget)self)->wlabel.pixmap);
}
#line 83 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 83 "../wb/Wlabel.widget"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 83 "../wb/Wlabel.widget"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 84 "../wb/Wlabel.widget"
{
  int do_expose = 0;

  if (((WlabelWidget)self)->wlabel.label != ((WlabelWidget)old)->wlabel.label) {
      XtFree(((WlabelWidget)old)->wlabel.label);
      if( ((WlabelWidget)self)->wlabel.label == 0) ((WlabelWidget)self)->wlabel.label="";
      ((WlabelWidget)self)->wlabel.label = XtNewString(((WlabelWidget)self)->wlabel.label);
      do_expose = 0;
      ((WlabelWidget)self)->wlabel.dirty=1;
      redraw(self); /* redraw only if neccessary */
  }

  if( ((WlabelWidget)self)->wheel.state != ((WlabelWidget)old)->wheel.state) {
      do_expose=0;
      ((WlabelWidget)self)->wlabel.dirty=1;
      redraw(self); /* redraw only if neccessary */
  }

  if( ((WlabelWidget)old)->wlabel.update != ((WlabelWidget)self)->wlabel.update )
  {
      do_expose=0;
      ((WlabelWidget)self)->wlabel.dirty=1;
      redraw(self); /* redraw only if neccessary */
  }

  return do_expose;
}
#line 113 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 113 "../wb/Wlabel.widget"
static void expose(Widget self,XEvent * event,Region  region)
#else
#line 113 "../wb/Wlabel.widget"
static void expose(self,event,region)Widget self;XEvent * event;Region  region;
#endif
#line 114 "../wb/Wlabel.widget"
{
  TRACE(1,"%s", ((WlabelWidget)self)->core.name );
  redraw(self);
}
#line 120 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 120 "../wb/Wlabel.widget"
static int  exec_command(Widget self,int  cmd,int  val)
#else
#line 120 "../wb/Wlabel.widget"
static int  exec_command(self,cmd,val)Widget self;int  cmd;int  val;
#endif
#line 121 "../wb/Wlabel.widget"
{
  return 0;
}
#line 125 "../wb/Wlabel.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 125 "../wb/Wlabel.widget"
static Bool  cache_hit(Widget self)
#else
#line 125 "../wb/Wlabel.widget"
static Bool  cache_hit(self)Widget self;
#endif
#line 126 "../wb/Wlabel.widget"
{
    Bool eq = ((WlabelWidget)self)->wlabel.label && ((WlabelWidget)self)->wlabel.label_cache && strcmp( ((WlabelWidget)self)->wlabel.label_cache, ((WlabelWidget)self)->wlabel.label ) == 0
         && ((WlabelWidget)self)->wheel.state == ((WlabelWidget)self)->wlabel.state_cache ;
    return eq;
}
