/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 301 "Wlab.widget"
#include <X11/Xregion.h>
#line 302 "Wlab.widget"
#include <X11/Xft/Xft.h>
#line 303 "Wlab.widget"
#include "converters-xft.h"
#line 304 "Wlab.widget"
#include <X11/Xmu/Converters.h>
#line 305 "Wlab.widget"
#include "mls.h"
#include <xtcw/WlabP.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 32 "Wlab.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 53 "Wlab.widget"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);
#line 69 "Wlab.widget"
static void realize(
#if NeedFunctionPrototypes
Widget,XtValueMask *,XSetWindowAttributes *
#endif
);
#line 81 "Wlab.widget"
static void resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 87 "Wlab.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 96 "Wlab.widget"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 143 "Wlab.widget"
static int  exec_command(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 148 "Wlab.widget"
static Bool  cache_hit(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 153 "Wlab.widget"
static void  minimal_size(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#line 166 "Wlab.widget"
static void  prefered_size(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#line 175 "Wlab.widget"
static void clear_pixmap(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 181 "Wlab.widget"
static void copy_pixmap_to_window(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 190 "Wlab.widget"
static void copy_region_to_window(
#if NeedFunctionPrototypes
Widget,Region 
#endif
);
#line 214 "Wlab.widget"
static void draw_text(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 238 "Wlab.widget"
static void join_text_with_region(
#if NeedFunctionPrototypes
Widget,Region 
#endif
);
#line 243 "Wlab.widget"
static void clear_old_text(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 252 "Wlab.widget"
static void reshape_widget(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 264 "Wlab.widget"
static void alloc_pixmap(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 290 "Wlab.widget"
static void free_pixmap(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 175 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 175 "Wlab.widget"
static void clear_pixmap(Widget self)
#else
#line 175 "Wlab.widget"
static void clear_pixmap(self)Widget self;
#endif
#line 176 "Wlab.widget"
{
        TRACE(debug, "%s", ((WlabWidget)self)->core.name );
  XFillRectangle(XtDisplay(self),((WlabWidget)self)->wlab.pixmap, ((WlabWidget)self)->wheel.gc[((WlabWidget)self)->wheel.state], 0,0,((WlabWidget)self)->core.width,((WlabWidget)self)->core.height);
}
#line 181 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 181 "Wlab.widget"
static void copy_pixmap_to_window(Widget self)
#else
#line 181 "Wlab.widget"
static void copy_pixmap_to_window(self)Widget self;
#endif
#line 182 "Wlab.widget"
{
    if( ((WlabWidget)self)->core.visible )
       XCopyArea(XtDisplay(self),((WlabWidget)self)->wlab.pixmap, XtWindow(self), ((WlabWidget)self)->wlab.gc_copy,
            0,0, ((WlabWidget)self)->core.width,((WlabWidget)self)->core.height,  /* source pixmap */
            0,0  ); /* target window x,y */

}
#line 190 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 190 "Wlab.widget"
static void copy_region_to_window(Widget self,Region  region)
#else
#line 190 "Wlab.widget"
static void copy_region_to_window(self,region)Widget self;Region  region;
#endif
#line 191 "Wlab.widget"
{
    TRACE(debug,"%s", ((WlabWidget)self)->core.name );
    int x=0,y=0,w,h;
    if( region ) {
          Box *b = & region->extents;

          w = b->x2 - b->x1 +1;
          h = b->y2 - b->y1 +1;
          x = b->x1;
          y = b->y1;
  } else {
          w = ((WlabWidget)self)->core.width;
          h = ((WlabWidget)self)->core.height;
  }

  TRACE(debug, "%s: copy extents %dx%d,%dx%d",
        ((WlabWidget)self)->core.name, x,y,w,h );

  XCopyArea(XtDisplay(self),((WlabWidget)self)->wlab.pixmap, XtWindow(self), ((WlabWidget)self)->wlab.gc_copy,
            x,y, w,h,  /* source pixmap */
            x,y  ); /* target window x,y */
}
#line 214 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 214 "Wlab.widget"
static void draw_text(Widget self)
#else
#line 214 "Wlab.widget"
static void draw_text(self)Widget self;
#endif
#line 215 "Wlab.widget"
{
    TRACE(debug,"%s", ((WlabWidget)self)->core.name );

    int w,h;
    minimal_size( self, &w, &h );
    if( w > ((WlabWidget)self)->core.width ) w=((WlabWidget)self)->core.width;
    if( h > ((WlabWidget)self)->core.height ) h=((WlabWidget)self)->core.height;

    int x,y;
    char *s=((WlabWidget)self)->wlab.label;
    x = (((WlabWidget)self)->core.width - w) / 2;
    y = (((WlabWidget)self)->core.height -h) / 2;

    printf( "%s: %u %u\n",((WlabWidget)self)->core.name, ((unsigned char*)s)[0], ((unsigned char *)s)[1] );

    XftDrawStringUtf8(((WlabWidget)self)->wlab.draw, ((WlabWidget)self)->wheel.xft_col + ((WlabWidget)self)->wheel.state, ((WlabWidget)self)->wheel.xftFont,
    			     x,y+((WlabWidget)self)->wheel.xftFont->ascent, (FcChar8*)s, strlen(s) );
    ((WlabWidget)self)->wlab.r_label.x = x;
    ((WlabWidget)self)->wlab.r_label.y = y;
    ((WlabWidget)self)->wlab.r_label.width  = w;
    ((WlabWidget)self)->wlab.r_label.height = h;
}
#line 238 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 238 "Wlab.widget"
static void join_text_with_region(Widget self,Region  region)
#else
#line 238 "Wlab.widget"
static void join_text_with_region(self,region)Widget self;Region  region;
#endif
#line 239 "Wlab.widget"
{
    XUnionRectWithRegion(&((WlabWidget)self)->wlab.r_label, region, region);
}
#line 243 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 243 "Wlab.widget"
static void clear_old_text(Widget self)
#else
#line 243 "Wlab.widget"
static void clear_old_text(self)Widget self;
#endif
#line 244 "Wlab.widget"
{
        Display *dpy = XtDisplay(self);
        XFillRectangle(dpy,((WlabWidget)self)->wlab.pixmap, ((WlabWidget)self)->wheel.gc[((WlabWidget)self)->wheel.state],
                       ((WlabWidget)self)->wlab.r_label.x,((WlabWidget)self)->wlab.r_label.y, ((WlabWidget)self)->wlab.r_label.width, ((WlabWidget)self)->wlab.r_label.height );
}
#line 252 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 252 "Wlab.widget"
static void reshape_widget(Widget self)
#else
#line 252 "Wlab.widget"
static void reshape_widget(self)Widget self;
#endif
#line 253 "Wlab.widget"
{
	int w;
	if( ((WlabWidget)self)->wlab.cornerRoundPercent >0 && ((WlabWidget)self)->wlab.cornerRoundPercent < 100 ) {
	    w = Min(((WlabWidget)self)->core.height,((WlabWidget)self)->core.width);
	    w = w * ((WlabWidget)self)->wlab.cornerRoundPercent / 100;
	    XmuReshapeWidget( self, XmuShapeRoundedRectangle, w, w );
	}
}
#line 264 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 264 "Wlab.widget"
static void alloc_pixmap(Widget self)
#else
#line 264 "Wlab.widget"
static void alloc_pixmap(self)Widget self;
#endif
#line 265 "Wlab.widget"
{
    Display *dpy = XtDisplay(self);

    /* falls eine pixmap mit ausreichender größe vorhanden ist,
       keine neue pixmap erzeugen, sondern alte weiterverwenden */
    if( ((WlabWidget)self)->wlab.pixmap &&  (((WlabWidget)self)->wlab.pm_w >= ((WlabWidget)self)->core.width) && (((WlabWidget)self)->wlab.pm_h >= ((WlabWidget)self)->core.height) )
        return;

    TRACE(debug,"%s", ((WlabWidget)self)->core.name );

    if( ((WlabWidget)self)->wlab.pixmap ) XFreePixmap(dpy,((WlabWidget)self)->wlab.pixmap);

    ((WlabWidget)self)->wlab.pixmap = XCreatePixmap(dpy, XtWindow(self), ((WlabWidget)self)->core.width, ((WlabWidget)self)->core.height,
                            DefaultDepth(dpy, DefaultScreen(dpy)));
    ((WlabWidget)self)->wlab.pm_w = ((WlabWidget)self)->core.width; ((WlabWidget)self)->wlab.pm_h = ((WlabWidget)self)->core.height;

    if( ((WlabWidget)self)->wlab.draw ) {
        XftDrawChange(((WlabWidget)self)->wlab.draw, ((WlabWidget)self)->wlab.pixmap );
    }
    else {
        ((WlabWidget)self)->wlab.draw = XftDrawCreate(dpy, ((WlabWidget)self)->wlab.pixmap,
                       DefaultVisual(dpy, DefaultScreen(dpy)), None);
    }
}
#line 290 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 290 "Wlab.widget"
static void free_pixmap(Widget self)
#else
#line 290 "Wlab.widget"
static void free_pixmap(self)Widget self;
#endif
#line 291 "Wlab.widget"
{
        if( !((WlabWidget)self)->wlab.pixmap ) return;
        Display *dpy = XtDisplay(self);
        XFreePixmap(dpy,((WlabWidget)self)->wlab.pixmap);
        ((WlabWidget)self)->wlab.pixmap = 0;
    }

static XtResource resources[] = {
#line 12 "Wlab.widget"
{XtNlabel,XtCLabel,XtRString,sizeof(((WlabRec*)NULL)->wlab.label),XtOffsetOf(WlabRec,wlab.label),XtRString,(XtPointer)NULL },
#line 13 "Wlab.widget"
{XtNcornerRoundPercent,XtCCornerRoundPercent,XtRInt,sizeof(((WlabRec*)NULL)->wlab.cornerRoundPercent),XtOffsetOf(WlabRec,wlab.cornerRoundPercent),XtRImmediate,(XtPointer)0 },
#line 14 "Wlab.widget"
{XtNinnerBorder,XtCInnerBorder,XtRInt,sizeof(((WlabRec*)NULL)->wlab.innerBorder),XtOffsetOf(WlabRec,wlab.innerBorder),XtRImmediate,(XtPointer)0 },
#line 15 "Wlab.widget"
{XtNupdate,XtCUpdate,XtRInt,sizeof(((WlabRec*)NULL)->wlab.update),XtOffsetOf(WlabRec,wlab.update),XtRImmediate,(XtPointer)0 },
};

WlabClassRec wlabClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &wheelClassRec,
/* class_name   	*/  "Wlab",
/* widget_size  	*/  sizeof(WlabRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  realize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  4,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  XtExposeCompressSeries ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  True ,
/* destroy      	*/  destroy,
/* resize       	*/  resize,
/* expose       	*/  expose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  NULL,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* Wheel_class part */
exec_command,
XtInherit_sig_recv,
},
{ /* Wlab_class part */
cache_hit,
minimal_size,
prefered_size,
},
};
WidgetClass wlabWidgetClass = (WidgetClass) &wlabClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  WlabWidgetClass c __attribute__((unused)) = (WlabWidgetClass) class;
  WlabWidgetClass super __attribute__((unused));
  if (class == wlabWidgetClass) return;
  super = (WlabWidgetClass)class->core_class.superclass;
  if (c->wlab_class.cache_hit == XtInherit_cache_hit)
    c->wlab_class.cache_hit = super->wlab_class.cache_hit;
  if (c->wlab_class.minimal_size == XtInherit_minimal_size)
    c->wlab_class.minimal_size = super->wlab_class.minimal_size;
  if (c->wlab_class.prefered_size == XtInherit_prefered_size)
    c->wlab_class.prefered_size = super->wlab_class.prefered_size;
}
#line 32 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 32 "Wlab.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 32 "Wlab.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 33 "Wlab.widget"
{
        ((WlabWidget)self)->wlab.do_init = 1;
        ((WlabWidget)self)->wlab.pixmap = 0;
        ((WlabWidget)self)->wlab.draw = 0;
        ((WlabWidget)self)->wlab.gc_copy =  XtGetGC(self, 0,0 );
        if( is_empty(((WlabWidget)self)->wlab.label) ) ((WlabWidget)self)->wlab.label = ((WlabWidget)self)->core.name;

        int w, h;
        prefered_size( self, &w, &h );
        if( ((WlabWidget)self)->core.width == 0 ) ((WlabWidget)self)->core.width = w;
        if( ((WlabWidget)self)->core.height == 0 ) ((WlabWidget)self)->core.height = h;
}
#line 53 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 53 "Wlab.widget"
static void expose(Widget self,XEvent * event,Region  region)
#else
#line 53 "Wlab.widget"
static void expose(self,event,region)Widget self;XEvent * event;Region  region;
#endif
#line 54 "Wlab.widget"
{
  TRACE(debug,"%s", ((WlabWidget)self)->core.name );

  if( ((WlabWidget)self)->wlab.do_init ) {
      alloc_pixmap(self);
      clear_pixmap(self);
      draw_text(self);
      copy_pixmap_to_window(self);
      ((WlabWidget)self)->wlab.do_init = 0;
      return;
  }

  copy_region_to_window(self,region);
}
#line 69 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 69 "Wlab.widget"
static void realize(Widget self,XtValueMask * mask,XSetWindowAttributes * attributes)
#else
#line 69 "Wlab.widget"
static void realize(self,mask,attributes)Widget self;XtValueMask * mask;XSetWindowAttributes * attributes;
#endif
#line 70 "Wlab.widget"
{
     TRACE(debug, "%s: %dx%d", ((WlabWidget)self)->core.name, ((WlabWidget)self)->core.width, ((WlabWidget)self)->core.height );
     XtCreateWindow(self, (unsigned int) InputOutput,
        		  (Visual *) CopyFromParent, *mask, attributes);
     reshape_widget(self);
}
#line 81 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 81 "Wlab.widget"
static void resize(Widget self)
#else
#line 81 "Wlab.widget"
static void resize(self)Widget self;
#endif
#line 82 "Wlab.widget"
{
    if( XtIsRealized(self) ) reshape_widget(self);
    ((WlabWidget)self)->wlab.do_init=1;
}
#line 87 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 87 "Wlab.widget"
static void destroy(Widget self)
#else
#line 87 "Wlab.widget"
static void destroy(self)Widget self;
#endif
#line 88 "Wlab.widget"
{
  if( ((WlabWidget)self)->wlab.draw) XftDrawDestroy( ((WlabWidget)self)->wlab.draw );
  XtReleaseGC(self,((WlabWidget)self)->wlab.gc_copy);
  free_pixmap(self);
}
#line 96 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 96 "Wlab.widget"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 96 "Wlab.widget"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 97 "Wlab.widget"
{
    /* window erst neu zeichnen wenn es sichtbar geworden ist */
    if( !((WlabWidget)self)->core.visible ) { ((WlabWidget)self)->wlab.do_init = 1; return 0; }

  /* falls das widget noch nicht initialisiert ist
       oder ein resize stattgefunden hat wird bei
       expose alles neu gezeichnet. daher keine
       aktion notwendig
  */
  if( ((WlabWidget)self)->wlab.do_init ) return 1; /* call expose */

  if( ((WlabWidget)self)->core.border_width != ((WlabWidget)old)->core.border_width )
  {
        reshape_widget(self);
  }


  /* bei einem state change wird alles neu gezeichnet,
     also gibt es keinen grund noch die anderen änderungen
     zu überprüfen
  */
  if( (((WlabWidget)self)->wheel.state != ((WlabWidget)old)->wheel.state) ||  (((WlabWidget)old)->wlab.update != ((WlabWidget)self)->wlab.update)  ) {
      clear_pixmap(self);
      draw_text(self);
      copy_pixmap_to_window(self);
      return 0;
  }

  /* das label hat sich geändert, dann muss das alte
     label gelöscht werden und das neue gezeichnet.
     da keine weiteren attribute vorgesehen sind
     kann hier beendet werden
  */
  if( (((WlabWidget)self)->wlab.label != ((WlabWidget)old)->wlab.label) || strcmp(((WlabWidget)self)->wlab.label,((WlabWidget)old)->wlab.label) ) {
      if( ((WlabWidget)self)->wlab.label == 0) ((WlabWidget)self)->wlab.label="";
      clear_old_text(self);
      draw_text(self);
      copy_pixmap_to_window(self);
      return 0;
  }

  return 0;

}
#line 143 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 143 "Wlab.widget"
static int  exec_command(Widget self,int  cmd,int  val)
#else
#line 143 "Wlab.widget"
static int  exec_command(self,cmd,val)Widget self;int  cmd;int  val;
#endif
#line 144 "Wlab.widget"
{
  return 0;
}
#line 148 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 148 "Wlab.widget"
static Bool  cache_hit(Widget self)
#else
#line 148 "Wlab.widget"
static Bool  cache_hit(self)Widget self;
#endif
#line 149 "Wlab.widget"
{
    return 0;
}
#line 153 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 153 "Wlab.widget"
static void  minimal_size(Widget self,int * w0,int * h0)
#else
#line 153 "Wlab.widget"
static void  minimal_size(self,w0,h0)Widget self;int * w0;int * h0;
#endif
#line 154 "Wlab.widget"
{
        XGlyphInfo extents;
        Display *dpy = XtDisplay(self);
        int w,h;
        XftTextExtentsUtf8(dpy, ((WlabWidget)self)->wheel.xftFont, (FcChar8*)  ((WlabWidget)self)->wlab.label,
		       strlen( ((WlabWidget)self)->wlab.label ), &extents);
        w = extents.xOff;
        h = ((WlabWidget)self)->wheel.xftFont->ascent + ((WlabWidget)self)->wheel.xftFont->descent;
        if( w0 ) *w0 = w;
        if( h0 ) *h0 = h;
}
#line 166 "Wlab.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 166 "Wlab.widget"
static void  prefered_size(Widget self,int * w0,int * h0)
#else
#line 166 "Wlab.widget"
static void  prefered_size(self,w0,h0)Widget self;int * w0;int * h0;
#endif
#line 167 "Wlab.widget"
{
    minimal_size(self,w0,h0);
    if( w0 ) *w0 +=2 * ((WlabWidget)self)->wlab.innerBorder;
    if( h0 ) *h0 +=2 * ((WlabWidget)self)->wlab.innerBorder;
}
