/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 344 "Wsel2.widget"
#include <X11/Xregion.h>
#line 345 "Wsel2.widget"
#include <X11/Xft/Xft.h>
#line 346 "Wsel2.widget"
#include "converters.h"
#line 347 "Wsel2.widget"
#include <X11/Xmu/Converters.h>
#line 348 "Wsel2.widget"
#include "mls.h"
#include <xtcw/Wsel2P.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 40 "Wsel2.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 64 "Wsel2.widget"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);
#line 80 "Wsel2.widget"
static void realize(
#if NeedFunctionPrototypes
Widget,XtValueMask *,XSetWindowAttributes *
#endif
);
#line 92 "Wsel2.widget"
static void resize(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 98 "Wsel2.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 107 "Wsel2.widget"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 152 "Wsel2.widget"
static int  exec_command(
#if NeedFunctionPrototypes
Widget,int ,int 
#endif
);
#line 157 "Wsel2.widget"
static Bool  cache_hit(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 163 "Wsel2.widget"
static void  minimal_size(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#line 190 "Wsel2.widget"
static void  prefered_size(
#if NeedFunctionPrototypes
Widget,int *,int *
#endif
);
#line 200 "Wsel2.widget"
static void clear_pixmap(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 206 "Wsel2.widget"
static void copy_pixmap_to_window(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 215 "Wsel2.widget"
static void copy_region_to_window(
#if NeedFunctionPrototypes
Widget,Region 
#endif
);
#line 239 "Wsel2.widget"
static void draw_text(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 281 "Wsel2.widget"
static void clear_old_text(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 288 "Wsel2.widget"
static void reshape_widget(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 300 "Wsel2.widget"
static void alloc_pixmap(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 326 "Wsel2.widget"
static void free_pixmap(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 334 "Wsel2.widget"
static String  get_name(
#if NeedFunctionPrototypes
Widget,int 
#endif
);
#line 200 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 200 "Wsel2.widget"
static void clear_pixmap(Widget self)
#else
#line 200 "Wsel2.widget"
static void clear_pixmap(self)Widget self;
#endif
#line 201 "Wsel2.widget"
{
        TRACE(debug, "%s", ((Wsel2Widget)self)->core.name );
  XFillRectangle(XtDisplay(self),((Wsel2Widget)self)->wsel2.pixmap, ((Wsel2Widget)self)->wheel.gc[((Wsel2Widget)self)->wheel.state], 0,0,((Wsel2Widget)self)->core.width,((Wsel2Widget)self)->core.height);
}
#line 206 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 206 "Wsel2.widget"
static void copy_pixmap_to_window(Widget self)
#else
#line 206 "Wsel2.widget"
static void copy_pixmap_to_window(self)Widget self;
#endif
#line 207 "Wsel2.widget"
{
    if( ((Wsel2Widget)self)->core.visible )
       XCopyArea(XtDisplay(self),((Wsel2Widget)self)->wsel2.pixmap, XtWindow(self), ((Wsel2Widget)self)->wsel2.gc_copy,
            0,0, ((Wsel2Widget)self)->core.width,((Wsel2Widget)self)->core.height,  /* source pixmap */
            0,0  ); /* target window x,y */

}
#line 215 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 215 "Wsel2.widget"
static void copy_region_to_window(Widget self,Region  region)
#else
#line 215 "Wsel2.widget"
static void copy_region_to_window(self,region)Widget self;Region  region;
#endif
#line 216 "Wsel2.widget"
{
    TRACE(debug,"%s", ((Wsel2Widget)self)->core.name );
    int x=0,y=0,w,h;
    if( region ) {
          Box *b = & region->extents;

          w = b->x2 - b->x1 +1;
          h = b->y2 - b->y1 +1;
          x = b->x1;
          y = b->y1;
  } else {
          w = ((Wsel2Widget)self)->core.width;
          h = ((Wsel2Widget)self)->core.height;
  }

  TRACE(debug, "%s: copy extents %dx%d,%dx%d",
        ((Wsel2Widget)self)->core.name, x,y,w,h );

  XCopyArea(XtDisplay(self),((Wsel2Widget)self)->wsel2.pixmap, XtWindow(self), ((Wsel2Widget)self)->wsel2.gc_copy,
            x,y, w,h,  /* source pixmap */
            x,y  ); /* target window x,y */
}
#line 239 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 239 "Wsel2.widget"
static void draw_text(Widget self)
#else
#line 239 "Wsel2.widget"
static void draw_text(self)Widget self;
#endif
#line 240 "Wsel2.widget"
{
    TRACE(debug,"%s", ((Wsel2Widget)self)->core.name );
    if( ((Wsel2Widget)self)->wsel2.max_value == 0 ) return;

    int w,h;
    minimal_size( self, &w, &h );
    if( w > ((Wsel2Widget)self)->core.width ) w=((Wsel2Widget)self)->core.width;
    if( h > ((Wsel2Widget)self)->core.height ) h=((Wsel2Widget)self)->core.height;

    int x = (((Wsel2Widget)self)->core.width - w) / 2;
    int y = (((Wsel2Widget)self)->core.height -h) / 2 ;
    char *s;
    XRectangle *r;
    XftColor *fg,*bg;

    int p;
    m_foreach( ((Wsel2Widget)self)->wsel2.rects, p, r ) {

        if( p == ((Wsel2Widget)self)->wsel2.value ) {
            fg = ((Wsel2Widget)self)->wheel.xft_col + COLOR_FG_SEL;
            bg = ((Wsel2Widget)self)->wheel.xft_col + COLOR_BG_SEL;
        }
        else {
            fg = ((Wsel2Widget)self)->wheel.xft_col + COLOR_FG_NORM;
            bg = ((Wsel2Widget)self)->wheel.xft_col + COLOR_BG_NORM;
        }

        s = get_name(self,p);
        r->x = x; r->y = y;

        XftDrawRect(((Wsel2Widget)self)->wsel2.draw,bg, r->x, r->y, r->width, r->height );
        XftDrawStringUtf8(((Wsel2Widget)self)->wsel2.draw, fg, ((Wsel2Widget)self)->wheel.xftFont,
    			     x,y+ ((Wsel2Widget)self)->wheel.xftFont->ascent, (FcChar8*)s, strlen(s) );

        x+= ((Wsel2Widget)self)->wsel2.hgap + r->width;
    }

    ((Wsel2Widget)self)->wsel2.last_value = ((Wsel2Widget)self)->wsel2.value;

}
#line 281 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 281 "Wsel2.widget"
static void clear_old_text(Widget self)
#else
#line 281 "Wsel2.widget"
static void clear_old_text(self)Widget self;
#endif
#line 282 "Wsel2.widget"
{
    clear_pixmap(self);
}
#line 288 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 288 "Wsel2.widget"
static void reshape_widget(Widget self)
#else
#line 288 "Wsel2.widget"
static void reshape_widget(self)Widget self;
#endif
#line 289 "Wsel2.widget"
{
	int w;
	if( ((Wsel2Widget)self)->wsel2.cornerRoundPercent >0 && ((Wsel2Widget)self)->wsel2.cornerRoundPercent < 100 ) {
	    w = Min(((Wsel2Widget)self)->core.height,((Wsel2Widget)self)->core.width);
	    w = w * ((Wsel2Widget)self)->wsel2.cornerRoundPercent / 100;
	    XmuReshapeWidget( self, XmuShapeRoundedRectangle, w, w );
	}
}
#line 300 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 300 "Wsel2.widget"
static void alloc_pixmap(Widget self)
#else
#line 300 "Wsel2.widget"
static void alloc_pixmap(self)Widget self;
#endif
#line 301 "Wsel2.widget"
{
    Display *dpy = XtDisplay(self);

    /* falls eine pixmap mit ausreichender größe vorhanden ist,
       keine neue pixmap erzeugen, sondern alte weiterverwenden */
    if( ((Wsel2Widget)self)->wsel2.pixmap &&  (((Wsel2Widget)self)->wsel2.pm_w >= ((Wsel2Widget)self)->core.width) && (((Wsel2Widget)self)->wsel2.pm_h >= ((Wsel2Widget)self)->core.height) )
        return;

    TRACE(debug,"%s", ((Wsel2Widget)self)->core.name );

    if( ((Wsel2Widget)self)->wsel2.pixmap ) XFreePixmap(dpy,((Wsel2Widget)self)->wsel2.pixmap);

    ((Wsel2Widget)self)->wsel2.pixmap = XCreatePixmap(dpy, XtWindow(self), ((Wsel2Widget)self)->core.width, ((Wsel2Widget)self)->core.height,
                            DefaultDepth(dpy, DefaultScreen(dpy)));
    ((Wsel2Widget)self)->wsel2.pm_w = ((Wsel2Widget)self)->core.width; ((Wsel2Widget)self)->wsel2.pm_h = ((Wsel2Widget)self)->core.height;

    if( ((Wsel2Widget)self)->wsel2.draw ) {
        XftDrawChange(((Wsel2Widget)self)->wsel2.draw, ((Wsel2Widget)self)->wsel2.pixmap );
    }
    else {
        ((Wsel2Widget)self)->wsel2.draw = XftDrawCreate(dpy, ((Wsel2Widget)self)->wsel2.pixmap,
                       DefaultVisual(dpy, DefaultScreen(dpy)), None);
    }
}
#line 326 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 326 "Wsel2.widget"
static void free_pixmap(Widget self)
#else
#line 326 "Wsel2.widget"
static void free_pixmap(self)Widget self;
#endif
#line 327 "Wsel2.widget"
{
        if( !((Wsel2Widget)self)->wsel2.pixmap ) return;
        Display *dpy = XtDisplay(self);
        XFreePixmap(dpy,((Wsel2Widget)self)->wsel2.pixmap);
        ((Wsel2Widget)self)->wsel2.pixmap = 0;
    }
#line 334 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 334 "Wsel2.widget"
static String  get_name(Widget self,int  p)
#else
#line 334 "Wsel2.widget"
static String  get_name(self,p)Widget self;int  p;
#endif
#line 335 "Wsel2.widget"
{
  if( ((Wsel2Widget)self)->wsel2.max_value == 0 ) return "";
  if( p < 0 ) p = ((Wsel2Widget)self)->wsel2.max_value -1;
  else if( p >= ((Wsel2Widget)self)->wsel2.max_value ) p = 0;
  return STR(((Wsel2Widget)self)->wsel2.names,p);
}

static XtResource resources[] = {
#line 14 "Wsel2.widget"
{XtNvalue,XtCValue,XtRInt,sizeof(((Wsel2Rec*)NULL)->wsel2.value),XtOffsetOf(Wsel2Rec,wsel2.value),XtRImmediate,(XtPointer)0 },
#line 15 "Wsel2.widget"
{XtNlocked,XtCLocked,XtRBool,sizeof(((Wsel2Rec*)NULL)->wsel2.locked),XtOffsetOf(Wsel2Rec,wsel2.locked),XtRImmediate,(XtPointer)0 },
#line 16 "Wsel2.widget"
{XtNnames,XtCNames,XtRStringMArray,sizeof(((Wsel2Rec*)NULL)->wsel2.names),XtOffsetOf(Wsel2Rec,wsel2.names),XtRImmediate,(XtPointer)0 },
#line 17 "Wsel2.widget"
{XtNcornerRoundPercent,XtCCornerRoundPercent,XtRInt,sizeof(((Wsel2Rec*)NULL)->wsel2.cornerRoundPercent),XtOffsetOf(Wsel2Rec,wsel2.cornerRoundPercent),XtRImmediate,(XtPointer)0 },
#line 18 "Wsel2.widget"
{XtNinnerBorder,XtCInnerBorder,XtRInt,sizeof(((Wsel2Rec*)NULL)->wsel2.innerBorder),XtOffsetOf(Wsel2Rec,wsel2.innerBorder),XtRImmediate,(XtPointer)0 },
#line 19 "Wsel2.widget"
{XtNupdate,XtCUpdate,XtRInt,sizeof(((Wsel2Rec*)NULL)->wsel2.update),XtOffsetOf(Wsel2Rec,wsel2.update),XtRImmediate,(XtPointer)0 },
#line 20 "Wsel2.widget"
{XtNhgap,XtCHgap,XtRDistance,sizeof(((Wsel2Rec*)NULL)->wsel2.hgap),XtOffsetOf(Wsel2Rec,wsel2.hgap),XtRImmediate,(XtPointer)0 },
};

Wsel2ClassRec wsel2ClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &wheelClassRec,
/* class_name   	*/  "Wsel2",
/* widget_size  	*/  sizeof(Wsel2Rec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  realize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  7,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  XtExposeCompressSeries ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  True ,
/* destroy      	*/  destroy,
/* resize       	*/  resize,
/* expose       	*/  expose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  NULL,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* Wheel_class part */
exec_command,
XtInherit_sig_recv,
},
{ /* Wsel2_class part */
cache_hit,
minimal_size,
prefered_size,
},
};
WidgetClass wsel2WidgetClass = (WidgetClass) &wsel2ClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  Wsel2WidgetClass c __attribute__((unused)) = (Wsel2WidgetClass) class;
  Wsel2WidgetClass super __attribute__((unused));
  if (class == wsel2WidgetClass) return;
  super = (Wsel2WidgetClass)class->core_class.superclass;
  if (c->wsel2_class.cache_hit == XtInherit_cache_hit)
    c->wsel2_class.cache_hit = super->wsel2_class.cache_hit;
  if (c->wsel2_class.minimal_size == XtInherit_minimal_size)
    c->wsel2_class.minimal_size = super->wsel2_class.minimal_size;
  if (c->wsel2_class.prefered_size == XtInherit_prefered_size)
    c->wsel2_class.prefered_size = super->wsel2_class.prefered_size;
}
#line 40 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 40 "Wsel2.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 40 "Wsel2.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 41 "Wsel2.widget"
{
        ((Wsel2Widget)self)->wsel2.do_init = 1;
        ((Wsel2Widget)self)->wsel2.pixmap = 0;
        ((Wsel2Widget)self)->wsel2.draw = 0;
        ((Wsel2Widget)self)->wsel2.gc_copy =  XtGetGC(self, 0,0 );
        ((Wsel2Widget)self)->wsel2.rects = m_create(2,sizeof(XRectangle));

        if( ((Wsel2Widget)self)->wsel2.names == 0 ) ((Wsel2Widget)self)->wsel2.max_value=0;
        else ((Wsel2Widget)self)->wsel2.max_value = m_len(((Wsel2Widget)self)->wsel2.names);

        int w, h;
        prefered_size( self, &w, &h );
        if( ((Wsel2Widget)self)->core.width == 0 ) ((Wsel2Widget)self)->core.width = w;
        if( ((Wsel2Widget)self)->core.height == 0 ) ((Wsel2Widget)self)->core.height = h;
}
#line 64 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 64 "Wsel2.widget"
static void expose(Widget self,XEvent * event,Region  region)
#else
#line 64 "Wsel2.widget"
static void expose(self,event,region)Widget self;XEvent * event;Region  region;
#endif
#line 65 "Wsel2.widget"
{
  TRACE(debug,"%s", ((Wsel2Widget)self)->core.name );

  if( ((Wsel2Widget)self)->wsel2.do_init ) {
      alloc_pixmap(self);
      clear_pixmap(self);
      draw_text(self);
      copy_pixmap_to_window(self);
      ((Wsel2Widget)self)->wsel2.do_init = 0;
      return;
  }

  copy_region_to_window(self,region);
}
#line 80 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 80 "Wsel2.widget"
static void realize(Widget self,XtValueMask * mask,XSetWindowAttributes * attributes)
#else
#line 80 "Wsel2.widget"
static void realize(self,mask,attributes)Widget self;XtValueMask * mask;XSetWindowAttributes * attributes;
#endif
#line 81 "Wsel2.widget"
{
     TRACE(debug, "%s: %dx%d", ((Wsel2Widget)self)->core.name, ((Wsel2Widget)self)->core.width, ((Wsel2Widget)self)->core.height );
     XtCreateWindow(self, (unsigned int) InputOutput,
        		  (Visual *) CopyFromParent, *mask, attributes);
     reshape_widget(self);
}
#line 92 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 92 "Wsel2.widget"
static void resize(Widget self)
#else
#line 92 "Wsel2.widget"
static void resize(self)Widget self;
#endif
#line 93 "Wsel2.widget"
{
    if( XtIsRealized(self) ) reshape_widget(self);
    ((Wsel2Widget)self)->wsel2.do_init=1;
}
#line 98 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 98 "Wsel2.widget"
static void destroy(Widget self)
#else
#line 98 "Wsel2.widget"
static void destroy(self)Widget self;
#endif
#line 99 "Wsel2.widget"
{
  if( ((Wsel2Widget)self)->wsel2.draw) XftDrawDestroy( ((Wsel2Widget)self)->wsel2.draw );
  XtReleaseGC(self,((Wsel2Widget)self)->wsel2.gc_copy);
  free_pixmap(self);
}
#line 107 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 107 "Wsel2.widget"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 107 "Wsel2.widget"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 108 "Wsel2.widget"
{
    /* window erst neu zeichnen wenn es sichtbar geworden ist */
    if( !((Wsel2Widget)self)->core.visible ) { ((Wsel2Widget)self)->wsel2.do_init = 1; return 0; }

  /* falls das widget noch nicht initialisiert ist
       oder ein resize stattgefunden hat wird bei
       expose alles neu gezeichnet. daher keine
       aktion notwendig
  */
  if( ((Wsel2Widget)self)->wsel2.do_init ) return 1; /* call expose */

  if( ((Wsel2Widget)self)->core.border_width != ((Wsel2Widget)old)->core.border_width )
  {
        reshape_widget(self);
  }


  /* bei einem state change wird alles neu gezeichnet,
     also gibt es keinen grund noch die anderen änderungen
     zu überprüfen
  */
  if( (((Wsel2Widget)self)->wheel.state != ((Wsel2Widget)old)->wheel.state) ||  (((Wsel2Widget)old)->wsel2.update != ((Wsel2Widget)self)->wsel2.update)  ) {
      clear_pixmap(self);
      draw_text(self);
      copy_pixmap_to_window(self);
      return 0;
  }

  /* das aktive label hat sich geändert, dann muss das alte
     label gelöscht werden und das neue gezeichnet.
     da keine weiteren attribute vorgesehen sind
     kann hier beendet werden
  */
  if( (((Wsel2Widget)self)->wsel2.value != ((Wsel2Widget)old)->wsel2.value) ) {
      clear_old_text(self);
      draw_text(self);
      copy_pixmap_to_window(self);
      return 0;
  }

  return 0;
}
#line 152 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 152 "Wsel2.widget"
static int  exec_command(Widget self,int  cmd,int  val)
#else
#line 152 "Wsel2.widget"
static int  exec_command(self,cmd,val)Widget self;int  cmd;int  val;
#endif
#line 153 "Wsel2.widget"
{
  return 0;
}
#line 157 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 157 "Wsel2.widget"
static Bool  cache_hit(Widget self)
#else
#line 157 "Wsel2.widget"
static Bool  cache_hit(self)Widget self;
#endif
#line 158 "Wsel2.widget"
{
    return 0;
}
#line 163 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 163 "Wsel2.widget"
static void  minimal_size(Widget self,int * w0,int * h0)
#else
#line 163 "Wsel2.widget"
static void  minimal_size(self,w0,h0)Widget self;int * w0;int * h0;
#endif
#line 164 "Wsel2.widget"
{
        XGlyphInfo extents;
        Display *dpy = XtDisplay(self);
        int i,w = 0, h;
        h = ((Wsel2Widget)self)->wheel.xftFont->ascent + ((Wsel2Widget)self)->wheel.xftFont->descent;
        char *s;

        int len = m_len(((Wsel2Widget)self)->wsel2.names);
        m_clear( ((Wsel2Widget)self)->wsel2.rects );
        XRectangle *r;

        for(i=0; i < len;i++) {
                 s = get_name(self,i);
                 XftTextExtentsUtf8(dpy, ((Wsel2Widget)self)->wheel.xftFont, (FcChar8*)  s,
		       strlen(s), &extents);
                 w += extents.xOff;
                 r = m_add(((Wsel2Widget)self)->wsel2.rects);
                 r->width = extents.xOff;
                 r->height = h;
        }
        ((Wsel2Widget)self)->wsel2.total_width = w;
        if( len ) w += (len-1) * ((Wsel2Widget)self)->wsel2.hgap;
        if( w0 ) *w0 = w;
        if( h0 ) *h0 = h;
}
#line 190 "Wsel2.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 190 "Wsel2.widget"
static void  prefered_size(Widget self,int * w0,int * h0)
#else
#line 190 "Wsel2.widget"
static void  prefered_size(self,w0,h0)Widget self;int * w0;int * h0;
#endif
#line 191 "Wsel2.widget"
{
    minimal_size(self,w0,h0);
    if( w0 ) *w0 +=2 * ((Wsel2Widget)self)->wsel2.innerBorder;
    if( h0 ) *h0 +=2 * ((Wsel2Widget)self)->wsel2.innerBorder;
}
