/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 104 "WviewQV.widget"
#include "mls.h"
#line 105 "WviewQV.widget"
#include "xutil.h"
#line 106 "WviewQV.widget"
#include "micro_vars.h"
#line 107 "WviewQV.widget"
#include "converters.h"
#include <xtcw/WviewQVP.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 15 "WviewQV.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 30 "WviewQV.widget"
static Bool  cache_hit(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 38 "WviewQV.widget"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 58 "WviewQV.widget"
static void change_enable(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 67 "WviewQV.widget"
static void do_update(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 74 "WviewQV.widget"
static void show_data(
#if NeedFunctionPrototypes
Widget,void *,void *
#endif
);
#line 58 "WviewQV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 58 "WviewQV.widget"
static void change_enable(Widget self)
#else
#line 58 "WviewQV.widget"
static void change_enable(self)Widget self;
#endif
#line 59 "WviewQV.widget"
{
        int remove_watcher =  ! *mv_var(((WviewQVWidget)self)->wviewQV.enable);
        TRACE(1, "%s: remove=%d", ((WviewQVWidget)self)->core.name, remove_watcher );
        mv_onwrite(((WviewQVWidget)self)->wviewQV.var, (voidfn_t)do_update, self,  remove_watcher );

        if( !remove_watcher ) do_update(self);
}
#line 67 "WviewQV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 67 "WviewQV.widget"
static void do_update(Widget self)
#else
#line 67 "WviewQV.widget"
static void do_update(self)Widget self;
#endif
#line 68 "WviewQV.widget"
{
        TRACE(1, "%s", ((WviewQVWidget)self)->core.name );
        ((WviewQVWidget)self)->wviewQV.change_val = True;
        XtVaSetValues( self, "update", ((WviewQVWidget)self)->wlabel.update+1, NULL );
}
#line 74 "WviewQV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 74 "WviewQV.widget"
static void show_data(Widget self,void * a,void * b)
#else
#line 74 "WviewQV.widget"
static void show_data(self,a,b)Widget self;void * a;void * b;
#endif
#line 75 "WviewQV.widget"
{

        int wh,val,h,x,y;
        char *s, str[30];
        val = *mv_var( ((WviewQVWidget)self)->wviewQV.var );
        sprintf(str,"%d", val );

        s = ((WviewQVWidget)self)->wlabel.label;
        h = ((WviewQVWidget)self)->wheel.xftFont->height;
        wh = ((WviewQVWidget)self)->core.height / 2;
        x = (((WviewQVWidget)self)->core.width - xft_textwidth( XtDisplay(self), ((WviewQVWidget)self)->wheel.xftFont, s ))/2;
        if( x < 0 ) x=0;
        y = (wh-h) / 2 + ((WviewQVWidget)self)->wheel.xftFont->ascent;
        XftDrawStringUtf8(((WviewQVWidget)self)->wlabel.draw,((WviewQVWidget)self)->wheel.xft_col + ((WviewQVWidget)self)->wheel.state, ((WviewQVWidget)self)->wheel.xftFont,
                                         x,y,(FcChar8*)s, strlen(s) );


        y += wh;
        s = str;

        x = (((WviewQVWidget)self)->core.width - xft_textwidth( XtDisplay(self), ((WviewQVWidget)self)->wheel.xftFont, s ))/2;
        if( x < 0 ) x=0;
        XftDrawStringUtf8(((WviewQVWidget)self)->wlabel.draw,((WviewQVWidget)self)->wheel.xft_col + ((WviewQVWidget)self)->wheel.state, ((WviewQVWidget)self)->wheel.xftFont,
                                         x,y,(FcChar8*)s, strlen(s) );
        ((WviewQVWidget)self)->wviewQV.drawn = val;

}

static XtResource resources[] = {
#line 7 "WviewQV.widget"
{XtNvar,XtCVar,XtRQVar,sizeof(((WviewQVRec*)NULL)->wviewQV.var),XtOffsetOf(WviewQVRec,wviewQV.var),XtRImmediate,(XtPointer)0 },
#line 8 "WviewQV.widget"
{XtNenable,XtCEnable,XtRQVar,sizeof(((WviewQVRec*)NULL)->wviewQV.enable),XtOffsetOf(WviewQVRec,wviewQV.enable),XtRImmediate,(XtPointer)0 },
};

WviewQVClassRec wviewQVClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &wlabelClassRec,
/* class_name   	*/  "WviewQV",
/* widget_size  	*/  sizeof(WviewQVRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  XtInheritRealize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  2,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  TRUE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  NULL,
/* resize       	*/  XtInheritResize,
/* expose       	*/  XtInheritExpose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  NULL,
/* query_geometry 	*/  XtInheritQueryGeometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* Wheel_class part */
XtInherit_exec_command,
XtInherit_sig_recv,
},
{ /* Wlabel_class part */
cache_hit,
},
{ /* WviewQV_class part */
 /* dummy */  0
},
};
WidgetClass wviewQVWidgetClass = (WidgetClass) &wviewQVClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  WviewQVWidgetClass c __attribute__((unused)) = (WviewQVWidgetClass) class;
  WviewQVWidgetClass super __attribute__((unused));
  if (class == wviewQVWidgetClass) return;
  super = (WviewQVWidgetClass)class->core_class.superclass;
}
#line 15 "WviewQV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 15 "WviewQV.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 15 "WviewQV.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 16 "WviewQV.widget"
{

        ((WviewQVWidget)self)->wlabel.draw_override = show_data;
        ((WviewQVWidget)self)->core.height = (((WviewQVWidget)self)->wheel.xftFont->height) * 2.5;

        if( ((WviewQVWidget)self)->wviewQV.enable && ((WviewQVWidget)self)->wviewQV.var ) {
            mv_onwrite( ((WviewQVWidget)self)->wviewQV.enable,(voidfn_t) change_enable, self, 0 );
            change_enable( self );
        }

        ((WviewQVWidget)self)->wviewQV.change_val = False;

}
#line 30 "WviewQV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 30 "WviewQV.widget"
static Bool  cache_hit(Widget self)
#else
#line 30 "WviewQV.widget"
static Bool  cache_hit(self)Widget self;
#endif
#line 31 "WviewQV.widget"
{
        int val = *mv_var( ((WviewQVWidget)self)->wviewQV.var );
        Bool hit = (((WviewQVWidget)self)->wviewQV.drawn == val);
        hit = hit && wlabelClassRec.wlabel_class.cache_hit(self);
        return hit;
}
#line 38 "WviewQV.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 38 "WviewQV.widget"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 38 "WviewQV.widget"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 39 "WviewQV.widget"
{
    int i;
    for(i=0;i<*num_args;i++) {
        if( strcmp(args[i].name, "var" ) == 0 ) {
          if( ((WviewQVWidget)old)->wviewQV.var ) mv_onwrite( ((WviewQVWidget)old)->wviewQV.var,(voidfn_t) do_update,self, 1 );
          change_enable(self);
        }
        else if( strcmp(args[i].name, "enable" ) == 0 ) {
          change_enable(self);
        }
    }
    return False;
}
