/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef VEXMO_WDEMOP_H
#define VEXMO_WDEMOP_H
#include <X11/CoreP.h>
#include <vexmo/Wdemo.h>
_XFUNCPROTOBEGIN
#define CHANGE_SIZE 1 


#define CHANGE_COLOR 2 


#define CHANGE_VALUE1 4 


#define CHANGE_VALUE2 8 


#define CHANGE_ALL 12 


#define BG 0 


#define FG 1 


#define CP 2 



typedef struct {
/* methods */
/* class variables */
int dummy;
} WdemoClassPart;

typedef struct _WdemoClassRec {
CoreClassPart core_class;
WdemoClassPart wdemo_class;
} WdemoClassRec;

typedef struct {
/* resources */
XftFont * xftFont;
Pixel  foreground;
int  lineWidth;
int  cornerRoundPercent;
XtCallbackList  callback;
String  label;
String  value;
/* private state */
XftDraw * draw;
GC  gc[3];
XftColor  xcol[2];
Pixmap  pm;
uint32_t  changed;
} WdemoPart;

typedef struct _WdemoRec {
CorePart core;
WdemoPart wdemo;
} WdemoRec;

externalref WdemoClassRec wdemoClassRec;

_XFUNCPROTOEND
#endif /* VEXMO_WDEMOP_H */
