/* Generated by wbuild
 * (generator version 3.3)
 */
#ifndef VEXMO_WDEMO_H
#define VEXMO_WDEMO_H
#include <X11/Core.h>
_XFUNCPROTOBEGIN
#ifndef XtNxftFont
#define XtNxftFont "xftFont"
#endif
#ifndef XtCXFtFont
#define XtCXFtFont "XFtFont"
#endif
#ifndef XtRXftFont
#define XtRXftFont "XftFont"
#endif

#ifndef XtNforeground
#define XtNforeground "foreground"
#endif
#ifndef XtCForeground
#define XtCForeground "Foreground"
#endif
#ifndef XtRPixel
#define XtRPixel "Pixel"
#endif

#ifndef XtNlineWidth
#define XtNlineWidth "lineWidth"
#endif
#ifndef XtCLineWidth
#define XtCLineWidth "LineWidth"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcornerRoundPercent
#define XtNcornerRoundPercent "cornerRoundPercent"
#endif
#ifndef XtCCornerRoundPercent
#define XtCCornerRoundPercent "CornerRoundPercent"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNcallback
#define XtNcallback "callback"
#endif
#ifndef XtCCallback
#define XtCCallback "Callback"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

#ifndef XtNlabel
#define XtNlabel "label"
#endif
#ifndef XtCLabel
#define XtCLabel "Label"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNvalue
#define XtNvalue "value"
#endif
#ifndef XtCValue
#define XtCValue "Value"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

typedef struct _WdemoClassRec *WdemoWidgetClass;
typedef struct _WdemoRec *WdemoWidget;
externalref WidgetClass wdemoWidgetClass;
_XFUNCPROTOEND
#endif /* VEXMO_WDEMO_H */
