'\" t
.TH "" 3 "" "Version Unknown To Mankind" "Free Widget Foundation"
.SH NAME
Wim2
.SH DESCRIPTION
Widget zur Anzeige verschiedener Images




.SS "Public variables"

.ps -2
.TS
center box;
cBsss
lB|lB|lB|lB
l|l|l|l.
Wim2
Name	Class	Type	Default
XtNpicName	XtCPicName	String 	NULL 
XtNxoff	XtCXOff	int 	100 
XtNyoff	XtCYoff	int 	100 
XtNzoom	XtCZoom	int 	100 
XtNcallback	XtCCallback	Callback	NULL 
XtNuser_data	XtCUser_data	int 	0 

.TE
.ps +2


.TP
.I "XtNpicName"



.TP
.I "XtNxoff"



.TP
.I "XtNyoff"



.TP
.I "XtNzoom"



.TP
.I "XtNcallback"



.TP
.I "XtNuser_data"



.ps -2
.TS
center box;
cBsss
lB|lB|lB|lB
l|l|l|l.
Core
Name	Class	Type	Default
XtNx	XtCX	Position 	0 
XtNy	XtCY	Position 	0 
XtNwidth	XtCWidth	Dimension 	0 
XtNheight	XtCHeight	Dimension 	0 
borderWidth	XtCBorderWidth	Dimension 	0 
XtNcolormap	XtCColormap	Colormap 	NULL 
XtNdepth	XtCDepth	Int 	0 
destroyCallback	XtCDestroyCallback	XTCallbackList 	NULL 
XtNsensitive	XtCSensitive	Boolean 	True 
XtNtm	XtCTm	XTTMRec 	NULL 
ancestorSensitive	XtCAncestorSensitive	Boolean 	False 
accelerators	XtCAccelerators	XTTranslations 	NULL 
borderColor	XtCBorderColor	Pixel 	0 
borderPixmap	XtCBorderPixmap	Pixmap 	NULL 
background	XtCBackground	Pixel 	0 
backgroundPixmap	XtCBackgroundPixmap	Pixmap 	NULL 
mappedWhenManaged	XtCMappedWhenManaged	Boolean 	True 
XtNscreen	XtCScreen	Screen *	NULL 

.TE
.ps +2

.SS "Translations"


.nf
<Btn1Motion>: motion_start() 
.fi



.nf
<Btn3Motion>: b5_start() 
.fi



.nf
<BtnUp>: motion_end() 
.fi


.SS "Actions"


.TP
.I "motion_end




.TP
.I "b5_start




.TP
.I "motion_start



