/* Generated by wbuild
 * (generator version 3.3)
 */
#include <X11/IntrinsicP.h>
#include <X11/StringDefs.h>
#line 125 "Wcap.widget"
#include <X11/extensions/XShm.h>
#line 126 "Wcap.widget"
#include <sys/ipc.h>
#line 127 "Wcap.widget"
#include <sys/shm.h>
#line 128 "Wcap.widget"
#include <mls.h>
#line 129 "Wcap.widget"
#include "xv4l2.h"
#line 130 "Wcap.widget"
#include "xshm-util.h"
#include <xtcw/WcapP.h>
static void _resolve_inheritance(
#if NeedFunctionPrototypes
WidgetClass
#endif
);
#line 20 "Wcap.widget"
static void initialize(
#if NeedFunctionPrototypes
Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 32 "Wcap.widget"
static void destroy(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 39 "Wcap.widget"
static Boolean  set_values(
#if NeedFunctionPrototypes
Widget ,Widget ,Widget,ArgList ,Cardinal *
#endif
);
#line 45 "Wcap.widget"
static void expose(
#if NeedFunctionPrototypes
Widget,XEvent *,Region 
#endif
);
#line 51 "Wcap.widget"
static void realize(
#if NeedFunctionPrototypes
Widget,XtValueMask *,XSetWindowAttributes *
#endif
);
#line 57 "Wcap.widget"
static XtGeometryResult  query_geometry(
#if NeedFunctionPrototypes
Widget,XtWidgetGeometry *,XtWidgetGeometry *
#endif
);
#line 68 "Wcap.widget"
static void paint(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 82 "Wcap.widget"
static void grab(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 90 "Wcap.widget"
static void autoupd_cb(
#if NeedFunctionPrototypes
XtPointer ,XtIntervalId *
#endif
);
#line 101 "Wcap.widget"
static void capture_update(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 114 "Wcap.widget"
static void start_capture(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 119 "Wcap.widget"
static void stop_capture(
#if NeedFunctionPrototypes
Widget
#endif
);
#line 68 "Wcap.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 68 "Wcap.widget"
static void paint(Widget self)
#else
#line 68 "Wcap.widget"
static void paint(self)Widget self;
#endif
#line 69 "Wcap.widget"
{
        if(! ((WcapWidget)self)->wcap.im ) return;

        Display *d = XtDisplay(self);
        Window   w = XtWindow(self);
        if(!XShmPutImage(d,w,((WcapWidget)self)->wcap.gc_copy,((WcapWidget)self)->wcap.im->img,
                0,0, /* source x,y */
                0,0, /* dest x,y */
                ((WcapWidget)self)->wcap.pic_w,((WcapWidget)self)->wcap.pic_h,
                False))
          ERR("ShmPutImage error");
}
#line 82 "Wcap.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 82 "Wcap.widget"
static void grab(Widget self)
#else
#line 82 "Wcap.widget"
static void grab(self)Widget self;
#endif
#line 83 "Wcap.widget"
{
        XImage *img = ((WcapWidget)self)->wcap.im->img;
        xv4l2_grab( (void*)img->data,
                    img->width, img->height,
                    img->bytes_per_line );
}
#line 90 "Wcap.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 90 "Wcap.widget"
static void autoupd_cb(XtPointer  self,XtIntervalId * id)
#else
#line 90 "Wcap.widget"
static void autoupd_cb(self,id)XtPointer  self;XtIntervalId * id;
#endif
#line 91 "Wcap.widget"
{
        if(! ((WcapWidget)self)->wcap.grab ) return;
        grab(self); paint(self);
        XtAppContext ctx = XtWidgetToApplicationContext(self);
        ((WcapWidget)self)->wcap.autoupd_id =
	        XtAppAddTimeOut( ctx,
                                 1000/25,
                                 autoupd_cb, self );
}
#line 101 "Wcap.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 101 "Wcap.widget"
static void capture_update(Widget self)
#else
#line 101 "Wcap.widget"
static void capture_update(self)Widget self;
#endif
#line 102 "Wcap.widget"
{
        if( ((WcapWidget)self)->wcap.grab && !((WcapWidget)self)->wcap.cap ) {
            start_capture(self); ((WcapWidget)self)->wcap.cap=1;
            autoupd_cb(self,NULL);
            return;
        }

        if( ((WcapWidget)self)->wcap.cap && !((WcapWidget)self)->wcap.grab ) {
            stop_capture(self); ((WcapWidget)self)->wcap.cap=0;
        }
}
#line 114 "Wcap.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 114 "Wcap.widget"
static void start_capture(Widget self)
#else
#line 114 "Wcap.widget"
static void start_capture(self)Widget self;
#endif
#line 115 "Wcap.widget"
{
        xv4l2_start_capture();
}
#line 119 "Wcap.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 119 "Wcap.widget"
static void stop_capture(Widget self)
#else
#line 119 "Wcap.widget"
static void stop_capture(self)Widget self;
#endif
#line 120 "Wcap.widget"
{
        xv4l2_stop_capture();
}

static XtResource resources[] = {
#line 7 "Wcap.widget"
{XtNcallback,XtCCallback,XtRCallback,sizeof(((WcapRec*)NULL)->wcap.callback),XtOffsetOf(WcapRec,wcap.callback),XtRImmediate,(XtPointer)NULL },
#line 8 "Wcap.widget"
{XtNgrab,XtCGrab,XtRInt,sizeof(((WcapRec*)NULL)->wcap.grab),XtOffsetOf(WcapRec,wcap.grab),XtRImmediate,(XtPointer)0 },
};

WcapClassRec wcapClassRec = {
{ /* core_class part */
/* superclass   	*/  (WidgetClass) &coreClassRec,
/* class_name   	*/  "Wcap",
/* widget_size  	*/  sizeof(WcapRec),
/* class_initialize 	*/  NULL,
/* class_part_initialize*/  _resolve_inheritance,
/* class_inited 	*/  FALSE,
/* initialize   	*/  initialize,
/* initialize_hook 	*/  NULL,
/* realize      	*/  realize,
/* actions      	*/  NULL,
/* num_actions  	*/  0,
/* resources    	*/  resources,
/* num_resources 	*/  2,
/* xrm_class    	*/  NULLQUARK,
/* compres_motion 	*/  False ,
/* compress_exposure 	*/  TRUE ,
/* compress_enterleave 	*/  False ,
/* visible_interest 	*/  False ,
/* destroy      	*/  destroy,
/* resize       	*/  XtInheritResize,
/* expose       	*/  expose,
/* set_values   	*/  set_values,
/* set_values_hook 	*/  NULL,
/* set_values_almost 	*/  XtInheritSetValuesAlmost,
/* get_values+hook 	*/  NULL,
/* accept_focus 	*/  XtInheritAcceptFocus,
/* version      	*/  XtVersion,
/* callback_private 	*/  NULL,
/* tm_table      	*/  NULL,
/* query_geometry 	*/  query_geometry,
/* display_acceleator 	*/  XtInheritDisplayAccelerator,
/* extension    	*/  NULL 
},
{ /* Wcap_class part */
 /* dummy */  0
},
};
WidgetClass wcapWidgetClass = (WidgetClass) &wcapClassRec;
static void _resolve_inheritance(class)
WidgetClass class;
{
  WcapWidgetClass c __attribute__((unused)) = (WcapWidgetClass) class;
  WcapWidgetClass super __attribute__((unused));
  if (class == wcapWidgetClass) return;
  super = (WcapWidgetClass)class->core_class.superclass;
}
#line 20 "Wcap.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 20 "Wcap.widget"
static void initialize(Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 20 "Wcap.widget"
static void initialize(request,self,args,num_args)Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 21 "Wcap.widget"
{
  ((WcapWidget)self)->wcap.pic_w = 320;
  ((WcapWidget)self)->wcap.pic_h = 240;
  ((WcapWidget)self)->core.width = ((WcapWidget)self)->wcap.pic_w;
  ((WcapWidget)self)->core.height = ((WcapWidget)self)->wcap.pic_h;
  ((WcapWidget)self)->wcap.gc_copy = XtGetGC(self,0,NULL);
  ((WcapWidget)self)->wcap.cap=0;
  ((WcapWidget)self)->wcap.im = shm_create(self, ((WcapWidget)self)->wcap.pic_w, ((WcapWidget)self)->wcap.pic_h );
  xv4l2_init_grab();
}
#line 32 "Wcap.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 32 "Wcap.widget"
static void destroy(Widget self)
#else
#line 32 "Wcap.widget"
static void destroy(self)Widget self;
#endif
#line 33 "Wcap.widget"
{
  XtReleaseGC(self,((WcapWidget)self)->wcap.gc_copy);
  shm_destroy(((WcapWidget)self)->wcap.im);
  xv4l2_destroy();
}
#line 39 "Wcap.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 39 "Wcap.widget"
static Boolean  set_values(Widget  old,Widget  request,Widget self,ArgList  args,Cardinal * num_args)
#else
#line 39 "Wcap.widget"
static Boolean  set_values(old,request,self,args,num_args)Widget  old;Widget  request;Widget self;ArgList  args;Cardinal * num_args;
#endif
#line 40 "Wcap.widget"
{
        capture_update(self);
        return 0;
}
#line 45 "Wcap.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 45 "Wcap.widget"
static void expose(Widget self,XEvent * event,Region  region)
#else
#line 45 "Wcap.widget"
static void expose(self,event,region)Widget self;XEvent * event;Region  region;
#endif
#line 46 "Wcap.widget"
{
        capture_update(self);
        paint(self);
}
#line 51 "Wcap.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 51 "Wcap.widget"
static void realize(Widget self,XtValueMask * mask,XSetWindowAttributes * attributes)
#else
#line 51 "Wcap.widget"
static void realize(self,mask,attributes)Widget self;XtValueMask * mask;XSetWindowAttributes * attributes;
#endif
#line 52 "Wcap.widget"
{
  XtCreateWindow(self, (unsigned int) InputOutput,
  	  (Visual *) CopyFromParent, *mask, attributes);
}
#line 57 "Wcap.widget"
/*ARGSUSED*/
#if NeedFunctionPrototypes
#line 57 "Wcap.widget"
static XtGeometryResult  query_geometry(Widget self,XtWidgetGeometry * request,XtWidgetGeometry * reply)
#else
#line 57 "Wcap.widget"
static XtGeometryResult  query_geometry(self,request,reply)Widget self;XtWidgetGeometry * request;XtWidgetGeometry * reply;
#endif
#line 58 "Wcap.widget"
{
    reply->request_mode = CWX | CWY | CWWidth | CWHeight;
    reply->x=0; reply->y=0;
    reply->width =  ((WcapWidget)self)->wcap.pic_w;
    reply->height = ((WcapWidget)self)->wcap.pic_h;
    return XtGeometryAlmost;
}
